// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/raihan-faza/scriptsea-ept/backend/services/llm_job_service/pb/expense_service (interfaces: ExpenseServiceClient)
//
// Generated by this command:
//
//	mockgen -destination=tests/mocks/mock_expense_client.go -package=mocks github.com/raihan-faza/scriptsea-ept/backend/services/llm_job_service/pb/expense_service ExpenseServiceClient
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	pb "github.com/raihan-faza/scriptsea-ept/backend/services/llm_job_service/pb/expense_service"
	gomock "go.uber.org/mock/gomock"
	grpc "google.golang.org/grpc"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// MockExpenseServiceClient is a mock of ExpenseServiceClient interface.
type MockExpenseServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockExpenseServiceClientMockRecorder
	isgomock struct{}
}

// MockExpenseServiceClientMockRecorder is the mock recorder for MockExpenseServiceClient.
type MockExpenseServiceClientMockRecorder struct {
	mock *MockExpenseServiceClient
}

// NewMockExpenseServiceClient creates a new mock instance.
func NewMockExpenseServiceClient(ctrl *gomock.Controller) *MockExpenseServiceClient {
	mock := &MockExpenseServiceClient{ctrl: ctrl}
	mock.recorder = &MockExpenseServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExpenseServiceClient) EXPECT() *MockExpenseServiceClientMockRecorder {
	return m.recorder
}

// CreateExpense mocks base method.
func (m *MockExpenseServiceClient) CreateExpense(ctx context.Context, in *pb.CreateExpenseRequest, opts ...grpc.CallOption) (*pb.CreateExpenseResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateExpense", varargs...)
	ret0, _ := ret[0].(*pb.CreateExpenseResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateExpense indicates an expected call of CreateExpense.
func (mr *MockExpenseServiceClientMockRecorder) CreateExpense(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateExpense", reflect.TypeOf((*MockExpenseServiceClient)(nil).CreateExpense), varargs...)
}

// CreateExpenseCategory mocks base method.
func (m *MockExpenseServiceClient) CreateExpenseCategory(ctx context.Context, in *pb.CreateExpenseCategoryRequest, opts ...grpc.CallOption) (*pb.CreateExpenseCategoryResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateExpenseCategory", varargs...)
	ret0, _ := ret[0].(*pb.CreateExpenseCategoryResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateExpenseCategory indicates an expected call of CreateExpenseCategory.
func (mr *MockExpenseServiceClientMockRecorder) CreateExpenseCategory(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateExpenseCategory", reflect.TypeOf((*MockExpenseServiceClient)(nil).CreateExpenseCategory), varargs...)
}

// DeleteExpense mocks base method.
func (m *MockExpenseServiceClient) DeleteExpense(ctx context.Context, in *pb.DeleteExpenseRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteExpense", varargs...)
	ret0, _ := ret[0].(*emptypb.Empty)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteExpense indicates an expected call of DeleteExpense.
func (mr *MockExpenseServiceClientMockRecorder) DeleteExpense(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteExpense", reflect.TypeOf((*MockExpenseServiceClient)(nil).DeleteExpense), varargs...)
}

// DeleteExpenseCategory mocks base method.
func (m *MockExpenseServiceClient) DeleteExpenseCategory(ctx context.Context, in *pb.DeleteExpenseCategoryRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteExpenseCategory", varargs...)
	ret0, _ := ret[0].(*emptypb.Empty)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteExpenseCategory indicates an expected call of DeleteExpenseCategory.
func (mr *MockExpenseServiceClientMockRecorder) DeleteExpenseCategory(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteExpenseCategory", reflect.TypeOf((*MockExpenseServiceClient)(nil).DeleteExpenseCategory), varargs...)
}

// GetAllExpenses mocks base method.
func (m *MockExpenseServiceClient) GetAllExpenses(ctx context.Context, in *pb.GetAllExpensesRequest, opts ...grpc.CallOption) (*pb.GetAllExpensesResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetAllExpenses", varargs...)
	ret0, _ := ret[0].(*pb.GetAllExpensesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllExpenses indicates an expected call of GetAllExpenses.
func (mr *MockExpenseServiceClientMockRecorder) GetAllExpenses(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllExpenses", reflect.TypeOf((*MockExpenseServiceClient)(nil).GetAllExpenses), varargs...)
}

// GetAllExpensesCategory mocks base method.
func (m *MockExpenseServiceClient) GetAllExpensesCategory(ctx context.Context, in *pb.GetAllExpensesCategoryRequest, opts ...grpc.CallOption) (*pb.GetAllExpensesCategoryResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetAllExpensesCategory", varargs...)
	ret0, _ := ret[0].(*pb.GetAllExpensesCategoryResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllExpensesCategory indicates an expected call of GetAllExpensesCategory.
func (mr *MockExpenseServiceClientMockRecorder) GetAllExpensesCategory(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllExpensesCategory", reflect.TypeOf((*MockExpenseServiceClient)(nil).GetAllExpensesCategory), varargs...)
}

// UpdateExpense mocks base method.
func (m *MockExpenseServiceClient) UpdateExpense(ctx context.Context, in *pb.UpdateExpenseRequest, opts ...grpc.CallOption) (*pb.UpdateExpenseResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdateExpense", varargs...)
	ret0, _ := ret[0].(*pb.UpdateExpenseResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateExpense indicates an expected call of UpdateExpense.
func (mr *MockExpenseServiceClientMockRecorder) UpdateExpense(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateExpense", reflect.TypeOf((*MockExpenseServiceClient)(nil).UpdateExpense), varargs...)
}

// UpdateExpenseCategory mocks base method.
func (m *MockExpenseServiceClient) UpdateExpenseCategory(ctx context.Context, in *pb.UpdateExpenseCategoryRequest, opts ...grpc.CallOption) (*pb.UpdateExpenseCategoryResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdateExpenseCategory", varargs...)
	ret0, _ := ret[0].(*pb.UpdateExpenseCategoryResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateExpenseCategory indicates an expected call of UpdateExpenseCategory.
func (mr *MockExpenseServiceClientMockRecorder) UpdateExpenseCategory(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateExpenseCategory", reflect.TypeOf((*MockExpenseServiceClient)(nil).UpdateExpenseCategory), varargs...)
}
