// Code generated by MockGen. DO NOT EDIT.
// Source: /home/lahh/skripsi/scriptsea-ept/backend/services/llm_job_service/internal/repository/llm_repository.go
//
// Generated by this command:
//
//	mockgen -source=/home/lahh/skripsi/scriptsea-ept/backend/services/llm_job_service/internal/repository/llm_repository.go -destination=/home/lahh/skripsi/scriptsea-ept/backend/services/llm_job_service/tests/mocks/mock_llm_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	model "github.com/raihan-faza/scriptsea-ept/backend/services/llm_job_service/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockLlmRepository is a mock of LlmRepository interface.
type MockLlmRepository struct {
	ctrl     *gomock.Controller
	recorder *MockLlmRepositoryMockRecorder
	isgomock struct{}
}

// MockLlmRepositoryMockRecorder is the mock recorder for MockLlmRepository.
type MockLlmRepositoryMockRecorder struct {
	mock *MockLlmRepository
}

// NewMockLlmRepository creates a new mock instance.
func NewMockLlmRepository(ctrl *gomock.Controller) *MockLlmRepository {
	mock := &MockLlmRepository{ctrl: ctrl}
	mock.recorder = &MockLlmRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLlmRepository) EXPECT() *MockLlmRepositoryMockRecorder {
	return m.recorder
}

// ClaimExtractExpenseJob mocks base method.
func (m *MockLlmRepository) ClaimExtractExpenseJob(id string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClaimExtractExpenseJob", id)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ClaimExtractExpenseJob indicates an expected call of ClaimExtractExpenseJob.
func (mr *MockLlmRepositoryMockRecorder) ClaimExtractExpenseJob(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClaimExtractExpenseJob", reflect.TypeOf((*MockLlmRepository)(nil).ClaimExtractExpenseJob), id)
}

// CountExtractExpenseJobsCreatedToday mocks base method.
func (m *MockLlmRepository) CountExtractExpenseJobsCreatedToday(userId string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountExtractExpenseJobsCreatedToday", userId)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountExtractExpenseJobsCreatedToday indicates an expected call of CountExtractExpenseJobsCreatedToday.
func (mr *MockLlmRepositoryMockRecorder) CountExtractExpenseJobsCreatedToday(userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountExtractExpenseJobsCreatedToday", reflect.TypeOf((*MockLlmRepository)(nil).CountExtractExpenseJobsCreatedToday), userId)
}

// CreateExtractExpenseJob mocks base method.
func (m *MockLlmRepository) CreateExtractExpenseJob(job *model.ExtractExpenseJob) (*model.ExtractExpenseJob, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateExtractExpenseJob", job)
	ret0, _ := ret[0].(*model.ExtractExpenseJob)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateExtractExpenseJob indicates an expected call of CreateExtractExpenseJob.
func (mr *MockLlmRepositoryMockRecorder) CreateExtractExpenseJob(job any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateExtractExpenseJob", reflect.TypeOf((*MockLlmRepository)(nil).CreateExtractExpenseJob), job)
}

// DeleteExtractExpenseJob mocks base method.
func (m *MockLlmRepository) DeleteExtractExpenseJob(job *model.ExtractExpenseJob) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteExtractExpenseJob", job)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteExtractExpenseJob indicates an expected call of DeleteExtractExpenseJob.
func (mr *MockLlmRepositoryMockRecorder) DeleteExtractExpenseJob(job any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteExtractExpenseJob", reflect.TypeOf((*MockLlmRepository)(nil).DeleteExtractExpenseJob), job)
}

// GetExtractExpenseJobById mocks base method.
func (m *MockLlmRepository) GetExtractExpenseJobById(id string) (*model.ExtractExpenseJob, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetExtractExpenseJobById", id)
	ret0, _ := ret[0].(*model.ExtractExpenseJob)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetExtractExpenseJobById indicates an expected call of GetExtractExpenseJobById.
func (mr *MockLlmRepositoryMockRecorder) GetExtractExpenseJobById(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetExtractExpenseJobById", reflect.TypeOf((*MockLlmRepository)(nil).GetExtractExpenseJobById), id)
}

// GetExtractExpenseJobsByUserId mocks base method.
func (m *MockLlmRepository) GetExtractExpenseJobsByUserId(userId string) ([]model.ExtractExpenseJob, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetExtractExpenseJobsByUserId", userId)
	ret0, _ := ret[0].([]model.ExtractExpenseJob)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetExtractExpenseJobsByUserId indicates an expected call of GetExtractExpenseJobsByUserId.
func (mr *MockLlmRepositoryMockRecorder) GetExtractExpenseJobsByUserId(userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetExtractExpenseJobsByUserId", reflect.TypeOf((*MockLlmRepository)(nil).GetExtractExpenseJobsByUserId), userId)
}

// GetPendingExtractExpenseJobs mocks base method.
func (m *MockLlmRepository) GetPendingExtractExpenseJobs(limit int) ([]model.ExtractExpenseJob, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPendingExtractExpenseJobs", limit)
	ret0, _ := ret[0].([]model.ExtractExpenseJob)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPendingExtractExpenseJobs indicates an expected call of GetPendingExtractExpenseJobs.
func (mr *MockLlmRepositoryMockRecorder) GetPendingExtractExpenseJobs(limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPendingExtractExpenseJobs", reflect.TypeOf((*MockLlmRepository)(nil).GetPendingExtractExpenseJobs), limit)
}

// GetRetryableExtractExpenseJobs mocks base method.
func (m *MockLlmRepository) GetRetryableExtractExpenseJobs(limit int) ([]model.ExtractExpenseJob, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRetryableExtractExpenseJobs", limit)
	ret0, _ := ret[0].([]model.ExtractExpenseJob)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRetryableExtractExpenseJobs indicates an expected call of GetRetryableExtractExpenseJobs.
func (mr *MockLlmRepositoryMockRecorder) GetRetryableExtractExpenseJobs(limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRetryableExtractExpenseJobs", reflect.TypeOf((*MockLlmRepository)(nil).GetRetryableExtractExpenseJobs), limit)
}

// IncrementRetryCount mocks base method.
func (m *MockLlmRepository) IncrementRetryCount(id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrementRetryCount", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// IncrementRetryCount indicates an expected call of IncrementRetryCount.
func (mr *MockLlmRepositoryMockRecorder) IncrementRetryCount(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementRetryCount", reflect.TypeOf((*MockLlmRepository)(nil).IncrementRetryCount), id)
}

// SetNextRetryAt mocks base method.
func (m *MockLlmRepository) SetNextRetryAt(id string, currentRetryCount int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetNextRetryAt", id, currentRetryCount)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetNextRetryAt indicates an expected call of SetNextRetryAt.
func (mr *MockLlmRepositoryMockRecorder) SetNextRetryAt(id, currentRetryCount any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetNextRetryAt", reflect.TypeOf((*MockLlmRepository)(nil).SetNextRetryAt), id, currentRetryCount)
}

// UpdateExpenseStatus mocks base method.
func (m *MockLlmRepository) UpdateExpenseStatus(id, status, errorMessage string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateExpenseStatus", id, status, errorMessage)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateExpenseStatus indicates an expected call of UpdateExpenseStatus.
func (mr *MockLlmRepositoryMockRecorder) UpdateExpenseStatus(id, status, errorMessage any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateExpenseStatus", reflect.TypeOf((*MockLlmRepository)(nil).UpdateExpenseStatus), id, status, errorMessage)
}

// UpdateExtractExpenseJob mocks base method.
func (m *MockLlmRepository) UpdateExtractExpenseJob(job *model.ExtractExpenseJob) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateExtractExpenseJob", job)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateExtractExpenseJob indicates an expected call of UpdateExtractExpenseJob.
func (mr *MockLlmRepositoryMockRecorder) UpdateExtractExpenseJob(job any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateExtractExpenseJob", reflect.TypeOf((*MockLlmRepository)(nil).UpdateExtractExpenseJob), job)
}

// UpdateExtractExpenseJobStatus mocks base method.
func (m *MockLlmRepository) UpdateExtractExpenseJobStatus(id, status, errorMessage string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateExtractExpenseJobStatus", id, status, errorMessage)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateExtractExpenseJobStatus indicates an expected call of UpdateExtractExpenseJobStatus.
func (mr *MockLlmRepositoryMockRecorder) UpdateExtractExpenseJobStatus(id, status, errorMessage any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateExtractExpenseJobStatus", reflect.TypeOf((*MockLlmRepository)(nil).UpdateExtractExpenseJobStatus), id, status, errorMessage)
}

// UpdateLLMResult mocks base method.
func (m *MockLlmRepository) UpdateLLMResult(id, result string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLLMResult", id, result)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateLLMResult indicates an expected call of UpdateLLMResult.
func (mr *MockLlmRepositoryMockRecorder) UpdateLLMResult(id, result any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLLMResult", reflect.TypeOf((*MockLlmRepository)(nil).UpdateLLMResult), id, result)
}

// UpdateLLMStatus mocks base method.
func (m *MockLlmRepository) UpdateLLMStatus(id, status, errorMessage string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLLMStatus", id, status, errorMessage)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateLLMStatus indicates an expected call of UpdateLLMStatus.
func (mr *MockLlmRepositoryMockRecorder) UpdateLLMStatus(id, status, errorMessage any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLLMStatus", reflect.TypeOf((*MockLlmRepository)(nil).UpdateLLMStatus), id, status, errorMessage)
}
