// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/raihan-faza/scriptsea-ept/backend/services/llm_job_service/internal/usecase (interfaces: LLMUsecase)
//
// Generated by this command:
//
//	mockgen -destination=tests/mocks/mock_llm_usecase.go -package=mocks github.com/raihan-faza/scriptsea-ept/backend/services/llm_job_service/internal/usecase LLMUsecase
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	model "github.com/raihan-faza/scriptsea-ept/backend/services/llm_job_service/internal/model"
	dto "github.com/raihan-faza/scriptsea-ept/backend/services/llm_job_service/internal/usecase/dto"
	gomock "go.uber.org/mock/gomock"
)

// MockLLMUsecase is a mock of LLMUsecase interface.
type MockLLMUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockLLMUsecaseMockRecorder
	isgomock struct{}
}

// MockLLMUsecaseMockRecorder is the mock recorder for MockLLMUsecase.
type MockLLMUsecaseMockRecorder struct {
	mock *MockLLMUsecase
}

// NewMockLLMUsecase creates a new mock instance.
func NewMockLLMUsecase(ctrl *gomock.Controller) *MockLLMUsecase {
	mock := &MockLLMUsecase{ctrl: ctrl}
	mock.recorder = &MockLLMUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLLMUsecase) EXPECT() *MockLLMUsecaseMockRecorder {
	return m.recorder
}

// ExtractExpense mocks base method.
func (m *MockLLMUsecase) ExtractExpense(ctx context.Context, in *dto.ExtractExpenseInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExtractExpense", ctx, in)
	ret0, _ := ret[0].(error)
	return ret0
}

// ExtractExpense indicates an expected call of ExtractExpense.
func (mr *MockLLMUsecaseMockRecorder) ExtractExpense(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExtractExpense", reflect.TypeOf((*MockLLMUsecase)(nil).ExtractExpense), ctx, in)
}

// GetLLMJobs mocks base method.
func (m *MockLLMUsecase) GetLLMJobs(ctx context.Context, userId string) ([]model.ExtractExpenseJob, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLLMJobs", ctx, userId)
	ret0, _ := ret[0].([]model.ExtractExpenseJob)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLLMJobs indicates an expected call of GetLLMJobs.
func (mr *MockLLMUsecaseMockRecorder) GetLLMJobs(ctx, userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLLMJobs", reflect.TypeOf((*MockLLMUsecase)(nil).GetLLMJobs), ctx, userId)
}

// RetryJob mocks base method.
func (m *MockLLMUsecase) RetryJob(ctx context.Context, job *model.ExtractExpenseJob) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RetryJob", ctx, job)
	ret0, _ := ret[0].(error)
	return ret0
}

// RetryJob indicates an expected call of RetryJob.
func (mr *MockLLMUsecaseMockRecorder) RetryJob(ctx, job any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RetryJob", reflect.TypeOf((*MockLLMUsecase)(nil).RetryJob), ctx, job)
}
