// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.19.6
// source: expense.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExpenseCategory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExpenseCategory) Reset() {
	*x = ExpenseCategory{}
	mi := &file_expense_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExpenseCategory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpenseCategory) ProtoMessage() {}

func (x *ExpenseCategory) ProtoReflect() protoreflect.Message {
	mi := &file_expense_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpenseCategory.ProtoReflect.Descriptor instead.
func (*ExpenseCategory) Descriptor() ([]byte, []int) {
	return file_expense_proto_rawDescGZIP(), []int{0}
}

func (x *ExpenseCategory) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ExpenseCategory) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ExpenseCategory) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ExpenseCategory) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ExpenseCategory) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ExpenseCategory) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type Expense struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	WalletId      string                 `protobuf:"bytes,3,opt,name=wallet_id,json=walletId,proto3" json:"wallet_id,omitempty"`
	CategoryId    string                 `protobuf:"bytes,4,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	Amount        int64                  `protobuf:"varint,5,opt,name=amount,proto3" json:"amount,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Expense) Reset() {
	*x = Expense{}
	mi := &file_expense_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Expense) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Expense) ProtoMessage() {}

func (x *Expense) ProtoReflect() protoreflect.Message {
	mi := &file_expense_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Expense.ProtoReflect.Descriptor instead.
func (*Expense) Descriptor() ([]byte, []int) {
	return file_expense_proto_rawDescGZIP(), []int{1}
}

func (x *Expense) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Expense) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Expense) GetWalletId() string {
	if x != nil {
		return x.WalletId
	}
	return ""
}

func (x *Expense) GetCategoryId() string {
	if x != nil {
		return x.CategoryId
	}
	return ""
}

func (x *Expense) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Expense) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Expense) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Expense) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CreateExpenseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	WalletId      string                 `protobuf:"bytes,2,opt,name=wallet_id,json=walletId,proto3" json:"wallet_id,omitempty"`
	CategoryId    string                 `protobuf:"bytes,3,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	Amount        int64                  `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateExpenseRequest) Reset() {
	*x = CreateExpenseRequest{}
	mi := &file_expense_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateExpenseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateExpenseRequest) ProtoMessage() {}

func (x *CreateExpenseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_expense_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateExpenseRequest.ProtoReflect.Descriptor instead.
func (*CreateExpenseRequest) Descriptor() ([]byte, []int) {
	return file_expense_proto_rawDescGZIP(), []int{2}
}

func (x *CreateExpenseRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateExpenseRequest) GetWalletId() string {
	if x != nil {
		return x.WalletId
	}
	return ""
}

func (x *CreateExpenseRequest) GetCategoryId() string {
	if x != nil {
		return x.CategoryId
	}
	return ""
}

func (x *CreateExpenseRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type UpdateExpenseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	WalletId      string                 `protobuf:"bytes,3,opt,name=wallet_id,json=walletId,proto3" json:"wallet_id,omitempty"`
	CategoryId    string                 `protobuf:"bytes,4,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	Amount        int64                  `protobuf:"varint,5,opt,name=amount,proto3" json:"amount,omitempty"`
	UpdateMask    *fieldmaskpb.FieldMask `protobuf:"bytes,6,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateExpenseRequest) Reset() {
	*x = UpdateExpenseRequest{}
	mi := &file_expense_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateExpenseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateExpenseRequest) ProtoMessage() {}

func (x *UpdateExpenseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_expense_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateExpenseRequest.ProtoReflect.Descriptor instead.
func (*UpdateExpenseRequest) Descriptor() ([]byte, []int) {
	return file_expense_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateExpenseRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateExpenseRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateExpenseRequest) GetWalletId() string {
	if x != nil {
		return x.WalletId
	}
	return ""
}

func (x *UpdateExpenseRequest) GetCategoryId() string {
	if x != nil {
		return x.CategoryId
	}
	return ""
}

func (x *UpdateExpenseRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *UpdateExpenseRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

type DeleteExpenseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	WalletId      string                 `protobuf:"bytes,3,opt,name=wallet_id,json=walletId,proto3" json:"wallet_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteExpenseRequest) Reset() {
	*x = DeleteExpenseRequest{}
	mi := &file_expense_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteExpenseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteExpenseRequest) ProtoMessage() {}

func (x *DeleteExpenseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_expense_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteExpenseRequest.ProtoReflect.Descriptor instead.
func (*DeleteExpenseRequest) Descriptor() ([]byte, []int) {
	return file_expense_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteExpenseRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeleteExpenseRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DeleteExpenseRequest) GetWalletId() string {
	if x != nil {
		return x.WalletId
	}
	return ""
}

type CreateExpenseCategoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateExpenseCategoryRequest) Reset() {
	*x = CreateExpenseCategoryRequest{}
	mi := &file_expense_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateExpenseCategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateExpenseCategoryRequest) ProtoMessage() {}

func (x *CreateExpenseCategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_expense_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateExpenseCategoryRequest.ProtoReflect.Descriptor instead.
func (*CreateExpenseCategoryRequest) Descriptor() ([]byte, []int) {
	return file_expense_proto_rawDescGZIP(), []int{5}
}

func (x *CreateExpenseCategoryRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateExpenseCategoryRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateExpenseCategoryRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type UpdateExpenseCategoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	UpdateMask    *fieldmaskpb.FieldMask `protobuf:"bytes,4,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateExpenseCategoryRequest) Reset() {
	*x = UpdateExpenseCategoryRequest{}
	mi := &file_expense_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateExpenseCategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateExpenseCategoryRequest) ProtoMessage() {}

func (x *UpdateExpenseCategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_expense_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateExpenseCategoryRequest.ProtoReflect.Descriptor instead.
func (*UpdateExpenseCategoryRequest) Descriptor() ([]byte, []int) {
	return file_expense_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateExpenseCategoryRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateExpenseCategoryRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateExpenseCategoryRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateExpenseCategoryRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

type DeleteExpenseCategoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteExpenseCategoryRequest) Reset() {
	*x = DeleteExpenseCategoryRequest{}
	mi := &file_expense_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteExpenseCategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteExpenseCategoryRequest) ProtoMessage() {}

func (x *DeleteExpenseCategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_expense_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteExpenseCategoryRequest.ProtoReflect.Descriptor instead.
func (*DeleteExpenseCategoryRequest) Descriptor() ([]byte, []int) {
	return file_expense_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteExpenseCategoryRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeleteExpenseCategoryRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetAllExpensesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	WalletId      string                 `protobuf:"bytes,2,opt,name=wallet_id,json=walletId,proto3" json:"wallet_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllExpensesRequest) Reset() {
	*x = GetAllExpensesRequest{}
	mi := &file_expense_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllExpensesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllExpensesRequest) ProtoMessage() {}

func (x *GetAllExpensesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_expense_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllExpensesRequest.ProtoReflect.Descriptor instead.
func (*GetAllExpensesRequest) Descriptor() ([]byte, []int) {
	return file_expense_proto_rawDescGZIP(), []int{8}
}

func (x *GetAllExpensesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetAllExpensesRequest) GetWalletId() string {
	if x != nil {
		return x.WalletId
	}
	return ""
}

type GetAllExpensesCategoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllExpensesCategoryRequest) Reset() {
	*x = GetAllExpensesCategoryRequest{}
	mi := &file_expense_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllExpensesCategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllExpensesCategoryRequest) ProtoMessage() {}

func (x *GetAllExpensesCategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_expense_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllExpensesCategoryRequest.ProtoReflect.Descriptor instead.
func (*GetAllExpensesCategoryRequest) Descriptor() ([]byte, []int) {
	return file_expense_proto_rawDescGZIP(), []int{9}
}

func (x *GetAllExpensesCategoryRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type CreateExpenseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Expense       *Expense               `protobuf:"bytes,2,opt,name=expense,proto3" json:"expense,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateExpenseResponse) Reset() {
	*x = CreateExpenseResponse{}
	mi := &file_expense_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateExpenseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateExpenseResponse) ProtoMessage() {}

func (x *CreateExpenseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_expense_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateExpenseResponse.ProtoReflect.Descriptor instead.
func (*CreateExpenseResponse) Descriptor() ([]byte, []int) {
	return file_expense_proto_rawDescGZIP(), []int{10}
}

func (x *CreateExpenseResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateExpenseResponse) GetExpense() *Expense {
	if x != nil {
		return x.Expense
	}
	return nil
}

type UpdateExpenseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Expense       *Expense               `protobuf:"bytes,2,opt,name=expense,proto3" json:"expense,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateExpenseResponse) Reset() {
	*x = UpdateExpenseResponse{}
	mi := &file_expense_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateExpenseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateExpenseResponse) ProtoMessage() {}

func (x *UpdateExpenseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_expense_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateExpenseResponse.ProtoReflect.Descriptor instead.
func (*UpdateExpenseResponse) Descriptor() ([]byte, []int) {
	return file_expense_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateExpenseResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateExpenseResponse) GetExpense() *Expense {
	if x != nil {
		return x.Expense
	}
	return nil
}

type DeleteExpenseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteExpenseResponse) Reset() {
	*x = DeleteExpenseResponse{}
	mi := &file_expense_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteExpenseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteExpenseResponse) ProtoMessage() {}

func (x *DeleteExpenseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_expense_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteExpenseResponse.ProtoReflect.Descriptor instead.
func (*DeleteExpenseResponse) Descriptor() ([]byte, []int) {
	return file_expense_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteExpenseResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type CreateUsingLLMResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Expense       *Expense               `protobuf:"bytes,2,opt,name=expense,proto3" json:"expense,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUsingLLMResponse) Reset() {
	*x = CreateUsingLLMResponse{}
	mi := &file_expense_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUsingLLMResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUsingLLMResponse) ProtoMessage() {}

func (x *CreateUsingLLMResponse) ProtoReflect() protoreflect.Message {
	mi := &file_expense_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUsingLLMResponse.ProtoReflect.Descriptor instead.
func (*CreateUsingLLMResponse) Descriptor() ([]byte, []int) {
	return file_expense_proto_rawDescGZIP(), []int{13}
}

func (x *CreateUsingLLMResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateUsingLLMResponse) GetExpense() *Expense {
	if x != nil {
		return x.Expense
	}
	return nil
}

type CreateExpenseCategoryResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Success         bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ExpenseCategory *ExpenseCategory       `protobuf:"bytes,2,opt,name=expense_category,json=expenseCategory,proto3" json:"expense_category,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateExpenseCategoryResponse) Reset() {
	*x = CreateExpenseCategoryResponse{}
	mi := &file_expense_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateExpenseCategoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateExpenseCategoryResponse) ProtoMessage() {}

func (x *CreateExpenseCategoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_expense_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateExpenseCategoryResponse.ProtoReflect.Descriptor instead.
func (*CreateExpenseCategoryResponse) Descriptor() ([]byte, []int) {
	return file_expense_proto_rawDescGZIP(), []int{14}
}

func (x *CreateExpenseCategoryResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateExpenseCategoryResponse) GetExpenseCategory() *ExpenseCategory {
	if x != nil {
		return x.ExpenseCategory
	}
	return nil
}

type UpdateExpenseCategoryResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Success         bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ExpenseCategory *ExpenseCategory       `protobuf:"bytes,2,opt,name=expense_category,json=expenseCategory,proto3" json:"expense_category,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateExpenseCategoryResponse) Reset() {
	*x = UpdateExpenseCategoryResponse{}
	mi := &file_expense_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateExpenseCategoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateExpenseCategoryResponse) ProtoMessage() {}

func (x *UpdateExpenseCategoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_expense_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateExpenseCategoryResponse.ProtoReflect.Descriptor instead.
func (*UpdateExpenseCategoryResponse) Descriptor() ([]byte, []int) {
	return file_expense_proto_rawDescGZIP(), []int{15}
}

func (x *UpdateExpenseCategoryResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateExpenseCategoryResponse) GetExpenseCategory() *ExpenseCategory {
	if x != nil {
		return x.ExpenseCategory
	}
	return nil
}

type DeleteExpenseCategoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteExpenseCategoryResponse) Reset() {
	*x = DeleteExpenseCategoryResponse{}
	mi := &file_expense_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteExpenseCategoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteExpenseCategoryResponse) ProtoMessage() {}

func (x *DeleteExpenseCategoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_expense_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteExpenseCategoryResponse.ProtoReflect.Descriptor instead.
func (*DeleteExpenseCategoryResponse) Descriptor() ([]byte, []int) {
	return file_expense_proto_rawDescGZIP(), []int{16}
}

func (x *DeleteExpenseCategoryResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetAllExpensesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Expenses      []*Expense             `protobuf:"bytes,2,rep,name=expenses,proto3" json:"expenses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllExpensesResponse) Reset() {
	*x = GetAllExpensesResponse{}
	mi := &file_expense_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllExpensesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllExpensesResponse) ProtoMessage() {}

func (x *GetAllExpensesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_expense_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllExpensesResponse.ProtoReflect.Descriptor instead.
func (*GetAllExpensesResponse) Descriptor() ([]byte, []int) {
	return file_expense_proto_rawDescGZIP(), []int{17}
}

func (x *GetAllExpensesResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetAllExpensesResponse) GetExpenses() []*Expense {
	if x != nil {
		return x.Expenses
	}
	return nil
}

type GetAllExpensesCategoryResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Success           bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ExpenseCategories []*ExpenseCategory     `protobuf:"bytes,2,rep,name=expense_categories,json=expenseCategories,proto3" json:"expense_categories,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetAllExpensesCategoryResponse) Reset() {
	*x = GetAllExpensesCategoryResponse{}
	mi := &file_expense_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllExpensesCategoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllExpensesCategoryResponse) ProtoMessage() {}

func (x *GetAllExpensesCategoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_expense_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllExpensesCategoryResponse.ProtoReflect.Descriptor instead.
func (*GetAllExpensesCategoryResponse) Descriptor() ([]byte, []int) {
	return file_expense_proto_rawDescGZIP(), []int{18}
}

func (x *GetAllExpensesCategoryResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetAllExpensesCategoryResponse) GetExpenseCategories() []*ExpenseCategory {
	if x != nil {
		return x.ExpenseCategories
	}
	return nil
}

var File_expense_proto protoreflect.FileDescriptor

const file_expense_proto_rawDesc = "" +
	"\n" +
	"\rexpense.proto\x12\aexpense\x1a google/protobuf/field_mask.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe6\x01\n" +
	"\x0fExpenseCategory\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x96\x02\n" +
	"\aExpense\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1b\n" +
	"\twallet_id\x18\x03 \x01(\tR\bwalletId\x12\x1f\n" +
	"\vcategory_id\x18\x04 \x01(\tR\n" +
	"categoryId\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\x03R\x06amount\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x85\x01\n" +
	"\x14CreateExpenseRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\twallet_id\x18\x02 \x01(\tR\bwalletId\x12\x1f\n" +
	"\vcategory_id\x18\x03 \x01(\tR\n" +
	"categoryId\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x03R\x06amount\"\xd2\x01\n" +
	"\x14UpdateExpenseRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1b\n" +
	"\twallet_id\x18\x03 \x01(\tR\bwalletId\x12\x1f\n" +
	"\vcategory_id\x18\x04 \x01(\tR\n" +
	"categoryId\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\x03R\x06amount\x12;\n" +
	"\vupdate_mask\x18\x06 \x01(\v2\x1a.google.protobuf.FieldMaskR\n" +
	"updateMask\"\\\n" +
	"\x14DeleteExpenseRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1b\n" +
	"\twallet_id\x18\x03 \x01(\tR\bwalletId\"m\n" +
	"\x1cCreateExpenseCategoryRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"\xaa\x01\n" +
	"\x1cUpdateExpenseCategoryRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12;\n" +
	"\vupdate_mask\x18\x04 \x01(\v2\x1a.google.protobuf.FieldMaskR\n" +
	"updateMask\"G\n" +
	"\x1cDeleteExpenseCategoryRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"M\n" +
	"\x15GetAllExpensesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\twallet_id\x18\x02 \x01(\tR\bwalletId\"8\n" +
	"\x1dGetAllExpensesCategoryRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"]\n" +
	"\x15CreateExpenseResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12*\n" +
	"\aexpense\x18\x02 \x01(\v2\x10.expense.ExpenseR\aexpense\"]\n" +
	"\x15UpdateExpenseResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12*\n" +
	"\aexpense\x18\x02 \x01(\v2\x10.expense.ExpenseR\aexpense\"1\n" +
	"\x15DeleteExpenseResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"^\n" +
	"\x16CreateUsingLLMResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12*\n" +
	"\aexpense\x18\x02 \x01(\v2\x10.expense.ExpenseR\aexpense\"~\n" +
	"\x1dCreateExpenseCategoryResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12C\n" +
	"\x10expense_category\x18\x02 \x01(\v2\x18.expense.ExpenseCategoryR\x0fexpenseCategory\"~\n" +
	"\x1dUpdateExpenseCategoryResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12C\n" +
	"\x10expense_category\x18\x02 \x01(\v2\x18.expense.ExpenseCategoryR\x0fexpenseCategory\"9\n" +
	"\x1dDeleteExpenseCategoryResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"`\n" +
	"\x16GetAllExpensesResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12,\n" +
	"\bexpenses\x18\x02 \x03(\v2\x10.expense.ExpenseR\bexpenses\"\x83\x01\n" +
	"\x1eGetAllExpensesCategoryResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12G\n" +
	"\x12expense_categories\x18\x02 \x03(\v2\x18.expense.ExpenseCategoryR\x11expenseCategories2\xe1\x06\n" +
	"\x0eExpenseService\x12P\n" +
	"\rCreateExpense\x12\x1d.expense.CreateExpenseRequest\x1a\x1e.expense.CreateExpenseResponse\"\x00\x12P\n" +
	"\rUpdateExpense\x12\x1d.expense.UpdateExpenseRequest\x1a\x1e.expense.UpdateExpenseResponse\"\x00\x12P\n" +
	"\rDeleteExpense\x12\x1d.expense.DeleteExpenseRequest\x1a\x1e.expense.DeleteExpenseResponse\"\x00\x12Y\n" +
	"\x15CreateExpenseUsingLLM\x12\x1d.expense.CreateExpenseRequest\x1a\x1f.expense.CreateUsingLLMResponse\"\x00\x12S\n" +
	"\x0eGetAllExpenses\x12\x1e.expense.GetAllExpensesRequest\x1a\x1f.expense.GetAllExpensesResponse\"\x00\x12h\n" +
	"\x15CreateExpenseCategory\x12%.expense.CreateExpenseCategoryRequest\x1a&.expense.CreateExpenseCategoryResponse\"\x00\x12h\n" +
	"\x15UpdateExpenseCategory\x12%.expense.UpdateExpenseCategoryRequest\x1a&.expense.UpdateExpenseCategoryResponse\"\x00\x12h\n" +
	"\x15DeleteExpenseCategory\x12%.expense.DeleteExpenseCategoryRequest\x1a&.expense.DeleteExpenseCategoryResponse\"\x00\x12k\n" +
	"\x16GetAllExpensesCategory\x12&.expense.GetAllExpensesCategoryRequest\x1a'.expense.GetAllExpensesCategoryResponse\"\x00BJZHgithub.com/raihan-faza/scriptsea-ept/backend/services/expense_service/pbb\x06proto3"

var (
	file_expense_proto_rawDescOnce sync.Once
	file_expense_proto_rawDescData []byte
)

func file_expense_proto_rawDescGZIP() []byte {
	file_expense_proto_rawDescOnce.Do(func() {
		file_expense_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_expense_proto_rawDesc), len(file_expense_proto_rawDesc)))
	})
	return file_expense_proto_rawDescData
}

var file_expense_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_expense_proto_goTypes = []any{
	(*ExpenseCategory)(nil),                // 0: expense.ExpenseCategory
	(*Expense)(nil),                        // 1: expense.Expense
	(*CreateExpenseRequest)(nil),           // 2: expense.CreateExpenseRequest
	(*UpdateExpenseRequest)(nil),           // 3: expense.UpdateExpenseRequest
	(*DeleteExpenseRequest)(nil),           // 4: expense.DeleteExpenseRequest
	(*CreateExpenseCategoryRequest)(nil),   // 5: expense.CreateExpenseCategoryRequest
	(*UpdateExpenseCategoryRequest)(nil),   // 6: expense.UpdateExpenseCategoryRequest
	(*DeleteExpenseCategoryRequest)(nil),   // 7: expense.DeleteExpenseCategoryRequest
	(*GetAllExpensesRequest)(nil),          // 8: expense.GetAllExpensesRequest
	(*GetAllExpensesCategoryRequest)(nil),  // 9: expense.GetAllExpensesCategoryRequest
	(*CreateExpenseResponse)(nil),          // 10: expense.CreateExpenseResponse
	(*UpdateExpenseResponse)(nil),          // 11: expense.UpdateExpenseResponse
	(*DeleteExpenseResponse)(nil),          // 12: expense.DeleteExpenseResponse
	(*CreateUsingLLMResponse)(nil),         // 13: expense.CreateUsingLLMResponse
	(*CreateExpenseCategoryResponse)(nil),  // 14: expense.CreateExpenseCategoryResponse
	(*UpdateExpenseCategoryResponse)(nil),  // 15: expense.UpdateExpenseCategoryResponse
	(*DeleteExpenseCategoryResponse)(nil),  // 16: expense.DeleteExpenseCategoryResponse
	(*GetAllExpensesResponse)(nil),         // 17: expense.GetAllExpensesResponse
	(*GetAllExpensesCategoryResponse)(nil), // 18: expense.GetAllExpensesCategoryResponse
	(*timestamppb.Timestamp)(nil),          // 19: google.protobuf.Timestamp
	(*fieldmaskpb.FieldMask)(nil),          // 20: google.protobuf.FieldMask
}
var file_expense_proto_depIdxs = []int32{
	19, // 0: expense.ExpenseCategory.created_at:type_name -> google.protobuf.Timestamp
	19, // 1: expense.ExpenseCategory.updated_at:type_name -> google.protobuf.Timestamp
	19, // 2: expense.Expense.created_at:type_name -> google.protobuf.Timestamp
	19, // 3: expense.Expense.updated_at:type_name -> google.protobuf.Timestamp
	20, // 4: expense.UpdateExpenseRequest.update_mask:type_name -> google.protobuf.FieldMask
	20, // 5: expense.UpdateExpenseCategoryRequest.update_mask:type_name -> google.protobuf.FieldMask
	1,  // 6: expense.CreateExpenseResponse.expense:type_name -> expense.Expense
	1,  // 7: expense.UpdateExpenseResponse.expense:type_name -> expense.Expense
	1,  // 8: expense.CreateUsingLLMResponse.expense:type_name -> expense.Expense
	0,  // 9: expense.CreateExpenseCategoryResponse.expense_category:type_name -> expense.ExpenseCategory
	0,  // 10: expense.UpdateExpenseCategoryResponse.expense_category:type_name -> expense.ExpenseCategory
	1,  // 11: expense.GetAllExpensesResponse.expenses:type_name -> expense.Expense
	0,  // 12: expense.GetAllExpensesCategoryResponse.expense_categories:type_name -> expense.ExpenseCategory
	2,  // 13: expense.ExpenseService.CreateExpense:input_type -> expense.CreateExpenseRequest
	3,  // 14: expense.ExpenseService.UpdateExpense:input_type -> expense.UpdateExpenseRequest
	4,  // 15: expense.ExpenseService.DeleteExpense:input_type -> expense.DeleteExpenseRequest
	2,  // 16: expense.ExpenseService.CreateExpenseUsingLLM:input_type -> expense.CreateExpenseRequest
	8,  // 17: expense.ExpenseService.GetAllExpenses:input_type -> expense.GetAllExpensesRequest
	5,  // 18: expense.ExpenseService.CreateExpenseCategory:input_type -> expense.CreateExpenseCategoryRequest
	6,  // 19: expense.ExpenseService.UpdateExpenseCategory:input_type -> expense.UpdateExpenseCategoryRequest
	7,  // 20: expense.ExpenseService.DeleteExpenseCategory:input_type -> expense.DeleteExpenseCategoryRequest
	9,  // 21: expense.ExpenseService.GetAllExpensesCategory:input_type -> expense.GetAllExpensesCategoryRequest
	10, // 22: expense.ExpenseService.CreateExpense:output_type -> expense.CreateExpenseResponse
	11, // 23: expense.ExpenseService.UpdateExpense:output_type -> expense.UpdateExpenseResponse
	12, // 24: expense.ExpenseService.DeleteExpense:output_type -> expense.DeleteExpenseResponse
	13, // 25: expense.ExpenseService.CreateExpenseUsingLLM:output_type -> expense.CreateUsingLLMResponse
	17, // 26: expense.ExpenseService.GetAllExpenses:output_type -> expense.GetAllExpensesResponse
	14, // 27: expense.ExpenseService.CreateExpenseCategory:output_type -> expense.CreateExpenseCategoryResponse
	15, // 28: expense.ExpenseService.UpdateExpenseCategory:output_type -> expense.UpdateExpenseCategoryResponse
	16, // 29: expense.ExpenseService.DeleteExpenseCategory:output_type -> expense.DeleteExpenseCategoryResponse
	18, // 30: expense.ExpenseService.GetAllExpensesCategory:output_type -> expense.GetAllExpensesCategoryResponse
	22, // [22:31] is the sub-list for method output_type
	13, // [13:22] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_expense_proto_init() }
func file_expense_proto_init() {
	if File_expense_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_expense_proto_rawDesc), len(file_expense_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_expense_proto_goTypes,
		DependencyIndexes: file_expense_proto_depIdxs,
		MessageInfos:      file_expense_proto_msgTypes,
	}.Build()
	File_expense_proto = out.File
	file_expense_proto_goTypes = nil
	file_expense_proto_depIdxs = nil
}
