// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v3.19.6
// source: report.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import {
  type CallOptions,
  type ChannelCredentials,
  Client,
  type ClientOptions,
  type ClientUnaryCall,
  type handleUnaryCall,
  makeGenericClientConstructor,
  type Metadata,
  type ServiceError,
  type UntypedServiceImplementation,
} from "@grpc/grpc-js";

export const protobufPackage = "report";

export interface GenerateReportRequest {
  userId: string;
  walletId: string;
  dateStart: string;
  dateEnd: string;
  templateName: string;
}

export interface GenerateReportResponse {
  downloadUrl: string;
  filename: string;
  expiresAt: string;
}

export interface UploadTemplateRequest {
  walletId: string;
  templateName: string;
  description: string;
  fileContent: Uint8Array;
}

export interface UploadTemplateResponse {
  templateName: string;
  status: string;
}

export interface DeleteTemplateRequest {
  walletId: string;
  templateName: string;
}

export interface DeleteTemplateResponse {
  status: string;
}

export interface ListTemplatesRequest {
  walletId: string;
}

export interface TemplateInfo {
  templateName: string;
  description: string;
}

export interface ListTemplatesResponse {
  templates: TemplateInfo[];
}

function createBaseGenerateReportRequest(): GenerateReportRequest {
  return { userId: "", walletId: "", dateStart: "", dateEnd: "", templateName: "" };
}

export const GenerateReportRequest: MessageFns<GenerateReportRequest> = {
  encode(message: GenerateReportRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.userId !== "") {
      writer.uint32(10).string(message.userId);
    }
    if (message.walletId !== "") {
      writer.uint32(18).string(message.walletId);
    }
    if (message.dateStart !== "") {
      writer.uint32(26).string(message.dateStart);
    }
    if (message.dateEnd !== "") {
      writer.uint32(34).string(message.dateEnd);
    }
    if (message.templateName !== "") {
      writer.uint32(42).string(message.templateName);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GenerateReportRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGenerateReportRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.userId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.walletId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.dateStart = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.dateEnd = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.templateName = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GenerateReportRequest {
    return {
      userId: isSet(object.userId)
        ? globalThis.String(object.userId)
        : isSet(object.user_id)
        ? globalThis.String(object.user_id)
        : "",
      walletId: isSet(object.walletId)
        ? globalThis.String(object.walletId)
        : isSet(object.wallet_id)
        ? globalThis.String(object.wallet_id)
        : "",
      dateStart: isSet(object.dateStart)
        ? globalThis.String(object.dateStart)
        : isSet(object.date_start)
        ? globalThis.String(object.date_start)
        : "",
      dateEnd: isSet(object.dateEnd)
        ? globalThis.String(object.dateEnd)
        : isSet(object.date_end)
        ? globalThis.String(object.date_end)
        : "",
      templateName: isSet(object.templateName)
        ? globalThis.String(object.templateName)
        : isSet(object.template_name)
        ? globalThis.String(object.template_name)
        : "",
    };
  },

  toJSON(message: GenerateReportRequest): unknown {
    const obj: any = {};
    if (message.userId !== "") {
      obj.userId = message.userId;
    }
    if (message.walletId !== "") {
      obj.walletId = message.walletId;
    }
    if (message.dateStart !== "") {
      obj.dateStart = message.dateStart;
    }
    if (message.dateEnd !== "") {
      obj.dateEnd = message.dateEnd;
    }
    if (message.templateName !== "") {
      obj.templateName = message.templateName;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GenerateReportRequest>, I>>(base?: I): GenerateReportRequest {
    return GenerateReportRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GenerateReportRequest>, I>>(object: I): GenerateReportRequest {
    const message = createBaseGenerateReportRequest();
    message.userId = object.userId ?? "";
    message.walletId = object.walletId ?? "";
    message.dateStart = object.dateStart ?? "";
    message.dateEnd = object.dateEnd ?? "";
    message.templateName = object.templateName ?? "";
    return message;
  },
};

function createBaseGenerateReportResponse(): GenerateReportResponse {
  return { downloadUrl: "", filename: "", expiresAt: "" };
}

export const GenerateReportResponse: MessageFns<GenerateReportResponse> = {
  encode(message: GenerateReportResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.downloadUrl !== "") {
      writer.uint32(10).string(message.downloadUrl);
    }
    if (message.filename !== "") {
      writer.uint32(18).string(message.filename);
    }
    if (message.expiresAt !== "") {
      writer.uint32(26).string(message.expiresAt);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GenerateReportResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGenerateReportResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.downloadUrl = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.filename = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.expiresAt = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GenerateReportResponse {
    return {
      downloadUrl: isSet(object.downloadUrl)
        ? globalThis.String(object.downloadUrl)
        : isSet(object.download_url)
        ? globalThis.String(object.download_url)
        : "",
      filename: isSet(object.filename) ? globalThis.String(object.filename) : "",
      expiresAt: isSet(object.expiresAt)
        ? globalThis.String(object.expiresAt)
        : isSet(object.expires_at)
        ? globalThis.String(object.expires_at)
        : "",
    };
  },

  toJSON(message: GenerateReportResponse): unknown {
    const obj: any = {};
    if (message.downloadUrl !== "") {
      obj.downloadUrl = message.downloadUrl;
    }
    if (message.filename !== "") {
      obj.filename = message.filename;
    }
    if (message.expiresAt !== "") {
      obj.expiresAt = message.expiresAt;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GenerateReportResponse>, I>>(base?: I): GenerateReportResponse {
    return GenerateReportResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GenerateReportResponse>, I>>(object: I): GenerateReportResponse {
    const message = createBaseGenerateReportResponse();
    message.downloadUrl = object.downloadUrl ?? "";
    message.filename = object.filename ?? "";
    message.expiresAt = object.expiresAt ?? "";
    return message;
  },
};

function createBaseUploadTemplateRequest(): UploadTemplateRequest {
  return { walletId: "", templateName: "", description: "", fileContent: new Uint8Array(0) };
}

export const UploadTemplateRequest: MessageFns<UploadTemplateRequest> = {
  encode(message: UploadTemplateRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.walletId !== "") {
      writer.uint32(10).string(message.walletId);
    }
    if (message.templateName !== "") {
      writer.uint32(18).string(message.templateName);
    }
    if (message.description !== "") {
      writer.uint32(26).string(message.description);
    }
    if (message.fileContent.length !== 0) {
      writer.uint32(34).bytes(message.fileContent);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UploadTemplateRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUploadTemplateRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.walletId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.templateName = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.description = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.fileContent = reader.bytes();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UploadTemplateRequest {
    return {
      walletId: isSet(object.walletId)
        ? globalThis.String(object.walletId)
        : isSet(object.wallet_id)
        ? globalThis.String(object.wallet_id)
        : "",
      templateName: isSet(object.templateName)
        ? globalThis.String(object.templateName)
        : isSet(object.template_name)
        ? globalThis.String(object.template_name)
        : "",
      description: isSet(object.description) ? globalThis.String(object.description) : "",
      fileContent: isSet(object.fileContent)
        ? bytesFromBase64(object.fileContent)
        : isSet(object.file_content)
        ? bytesFromBase64(object.file_content)
        : new Uint8Array(0),
    };
  },

  toJSON(message: UploadTemplateRequest): unknown {
    const obj: any = {};
    if (message.walletId !== "") {
      obj.walletId = message.walletId;
    }
    if (message.templateName !== "") {
      obj.templateName = message.templateName;
    }
    if (message.description !== "") {
      obj.description = message.description;
    }
    if (message.fileContent.length !== 0) {
      obj.fileContent = base64FromBytes(message.fileContent);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UploadTemplateRequest>, I>>(base?: I): UploadTemplateRequest {
    return UploadTemplateRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UploadTemplateRequest>, I>>(object: I): UploadTemplateRequest {
    const message = createBaseUploadTemplateRequest();
    message.walletId = object.walletId ?? "";
    message.templateName = object.templateName ?? "";
    message.description = object.description ?? "";
    message.fileContent = object.fileContent ?? new Uint8Array(0);
    return message;
  },
};

function createBaseUploadTemplateResponse(): UploadTemplateResponse {
  return { templateName: "", status: "" };
}

export const UploadTemplateResponse: MessageFns<UploadTemplateResponse> = {
  encode(message: UploadTemplateResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.templateName !== "") {
      writer.uint32(10).string(message.templateName);
    }
    if (message.status !== "") {
      writer.uint32(18).string(message.status);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UploadTemplateResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUploadTemplateResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.templateName = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.status = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UploadTemplateResponse {
    return {
      templateName: isSet(object.templateName)
        ? globalThis.String(object.templateName)
        : isSet(object.template_name)
        ? globalThis.String(object.template_name)
        : "",
      status: isSet(object.status) ? globalThis.String(object.status) : "",
    };
  },

  toJSON(message: UploadTemplateResponse): unknown {
    const obj: any = {};
    if (message.templateName !== "") {
      obj.templateName = message.templateName;
    }
    if (message.status !== "") {
      obj.status = message.status;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UploadTemplateResponse>, I>>(base?: I): UploadTemplateResponse {
    return UploadTemplateResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UploadTemplateResponse>, I>>(object: I): UploadTemplateResponse {
    const message = createBaseUploadTemplateResponse();
    message.templateName = object.templateName ?? "";
    message.status = object.status ?? "";
    return message;
  },
};

function createBaseDeleteTemplateRequest(): DeleteTemplateRequest {
  return { walletId: "", templateName: "" };
}

export const DeleteTemplateRequest: MessageFns<DeleteTemplateRequest> = {
  encode(message: DeleteTemplateRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.walletId !== "") {
      writer.uint32(10).string(message.walletId);
    }
    if (message.templateName !== "") {
      writer.uint32(18).string(message.templateName);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DeleteTemplateRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDeleteTemplateRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.walletId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.templateName = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DeleteTemplateRequest {
    return {
      walletId: isSet(object.walletId)
        ? globalThis.String(object.walletId)
        : isSet(object.wallet_id)
        ? globalThis.String(object.wallet_id)
        : "",
      templateName: isSet(object.templateName)
        ? globalThis.String(object.templateName)
        : isSet(object.template_name)
        ? globalThis.String(object.template_name)
        : "",
    };
  },

  toJSON(message: DeleteTemplateRequest): unknown {
    const obj: any = {};
    if (message.walletId !== "") {
      obj.walletId = message.walletId;
    }
    if (message.templateName !== "") {
      obj.templateName = message.templateName;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DeleteTemplateRequest>, I>>(base?: I): DeleteTemplateRequest {
    return DeleteTemplateRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DeleteTemplateRequest>, I>>(object: I): DeleteTemplateRequest {
    const message = createBaseDeleteTemplateRequest();
    message.walletId = object.walletId ?? "";
    message.templateName = object.templateName ?? "";
    return message;
  },
};

function createBaseDeleteTemplateResponse(): DeleteTemplateResponse {
  return { status: "" };
}

export const DeleteTemplateResponse: MessageFns<DeleteTemplateResponse> = {
  encode(message: DeleteTemplateResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.status !== "") {
      writer.uint32(10).string(message.status);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DeleteTemplateResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDeleteTemplateResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.status = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DeleteTemplateResponse {
    return { status: isSet(object.status) ? globalThis.String(object.status) : "" };
  },

  toJSON(message: DeleteTemplateResponse): unknown {
    const obj: any = {};
    if (message.status !== "") {
      obj.status = message.status;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DeleteTemplateResponse>, I>>(base?: I): DeleteTemplateResponse {
    return DeleteTemplateResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DeleteTemplateResponse>, I>>(object: I): DeleteTemplateResponse {
    const message = createBaseDeleteTemplateResponse();
    message.status = object.status ?? "";
    return message;
  },
};

function createBaseListTemplatesRequest(): ListTemplatesRequest {
  return { walletId: "" };
}

export const ListTemplatesRequest: MessageFns<ListTemplatesRequest> = {
  encode(message: ListTemplatesRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.walletId !== "") {
      writer.uint32(10).string(message.walletId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListTemplatesRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListTemplatesRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.walletId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ListTemplatesRequest {
    return {
      walletId: isSet(object.walletId)
        ? globalThis.String(object.walletId)
        : isSet(object.wallet_id)
        ? globalThis.String(object.wallet_id)
        : "",
    };
  },

  toJSON(message: ListTemplatesRequest): unknown {
    const obj: any = {};
    if (message.walletId !== "") {
      obj.walletId = message.walletId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ListTemplatesRequest>, I>>(base?: I): ListTemplatesRequest {
    return ListTemplatesRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ListTemplatesRequest>, I>>(object: I): ListTemplatesRequest {
    const message = createBaseListTemplatesRequest();
    message.walletId = object.walletId ?? "";
    return message;
  },
};

function createBaseTemplateInfo(): TemplateInfo {
  return { templateName: "", description: "" };
}

export const TemplateInfo: MessageFns<TemplateInfo> = {
  encode(message: TemplateInfo, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.templateName !== "") {
      writer.uint32(10).string(message.templateName);
    }
    if (message.description !== "") {
      writer.uint32(18).string(message.description);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TemplateInfo {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTemplateInfo();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.templateName = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.description = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): TemplateInfo {
    return {
      templateName: isSet(object.templateName)
        ? globalThis.String(object.templateName)
        : isSet(object.template_name)
        ? globalThis.String(object.template_name)
        : "",
      description: isSet(object.description) ? globalThis.String(object.description) : "",
    };
  },

  toJSON(message: TemplateInfo): unknown {
    const obj: any = {};
    if (message.templateName !== "") {
      obj.templateName = message.templateName;
    }
    if (message.description !== "") {
      obj.description = message.description;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TemplateInfo>, I>>(base?: I): TemplateInfo {
    return TemplateInfo.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TemplateInfo>, I>>(object: I): TemplateInfo {
    const message = createBaseTemplateInfo();
    message.templateName = object.templateName ?? "";
    message.description = object.description ?? "";
    return message;
  },
};

function createBaseListTemplatesResponse(): ListTemplatesResponse {
  return { templates: [] };
}

export const ListTemplatesResponse: MessageFns<ListTemplatesResponse> = {
  encode(message: ListTemplatesResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.templates) {
      TemplateInfo.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListTemplatesResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListTemplatesResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.templates.push(TemplateInfo.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ListTemplatesResponse {
    return {
      templates: globalThis.Array.isArray(object?.templates)
        ? object.templates.map((e: any) => TemplateInfo.fromJSON(e))
        : [],
    };
  },

  toJSON(message: ListTemplatesResponse): unknown {
    const obj: any = {};
    if (message.templates?.length) {
      obj.templates = message.templates.map((e) => TemplateInfo.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ListTemplatesResponse>, I>>(base?: I): ListTemplatesResponse {
    return ListTemplatesResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ListTemplatesResponse>, I>>(object: I): ListTemplatesResponse {
    const message = createBaseListTemplatesResponse();
    message.templates = object.templates?.map((e) => TemplateInfo.fromPartial(e)) || [];
    return message;
  },
};

export type ReportServiceService = typeof ReportServiceService;
export const ReportServiceService = {
  generateReport: {
    path: "/report.ReportService/GenerateReport" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: GenerateReportRequest): Buffer =>
      Buffer.from(GenerateReportRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): GenerateReportRequest => GenerateReportRequest.decode(value),
    responseSerialize: (value: GenerateReportResponse): Buffer =>
      Buffer.from(GenerateReportResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): GenerateReportResponse => GenerateReportResponse.decode(value),
  },
  uploadTemplate: {
    path: "/report.ReportService/UploadTemplate" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: UploadTemplateRequest): Buffer =>
      Buffer.from(UploadTemplateRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): UploadTemplateRequest => UploadTemplateRequest.decode(value),
    responseSerialize: (value: UploadTemplateResponse): Buffer =>
      Buffer.from(UploadTemplateResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): UploadTemplateResponse => UploadTemplateResponse.decode(value),
  },
  deleteTemplate: {
    path: "/report.ReportService/DeleteTemplate" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: DeleteTemplateRequest): Buffer =>
      Buffer.from(DeleteTemplateRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): DeleteTemplateRequest => DeleteTemplateRequest.decode(value),
    responseSerialize: (value: DeleteTemplateResponse): Buffer =>
      Buffer.from(DeleteTemplateResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): DeleteTemplateResponse => DeleteTemplateResponse.decode(value),
  },
  listTemplates: {
    path: "/report.ReportService/ListTemplates" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: ListTemplatesRequest): Buffer => Buffer.from(ListTemplatesRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): ListTemplatesRequest => ListTemplatesRequest.decode(value),
    responseSerialize: (value: ListTemplatesResponse): Buffer =>
      Buffer.from(ListTemplatesResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): ListTemplatesResponse => ListTemplatesResponse.decode(value),
  },
} as const;

export interface ReportServiceServer extends UntypedServiceImplementation {
  generateReport: handleUnaryCall<GenerateReportRequest, GenerateReportResponse>;
  uploadTemplate: handleUnaryCall<UploadTemplateRequest, UploadTemplateResponse>;
  deleteTemplate: handleUnaryCall<DeleteTemplateRequest, DeleteTemplateResponse>;
  listTemplates: handleUnaryCall<ListTemplatesRequest, ListTemplatesResponse>;
}

export interface ReportServiceClient extends Client {
  generateReport(
    request: GenerateReportRequest,
    callback: (error: ServiceError | null, response: GenerateReportResponse) => void,
  ): ClientUnaryCall;
  generateReport(
    request: GenerateReportRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: GenerateReportResponse) => void,
  ): ClientUnaryCall;
  generateReport(
    request: GenerateReportRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: GenerateReportResponse) => void,
  ): ClientUnaryCall;
  uploadTemplate(
    request: UploadTemplateRequest,
    callback: (error: ServiceError | null, response: UploadTemplateResponse) => void,
  ): ClientUnaryCall;
  uploadTemplate(
    request: UploadTemplateRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: UploadTemplateResponse) => void,
  ): ClientUnaryCall;
  uploadTemplate(
    request: UploadTemplateRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: UploadTemplateResponse) => void,
  ): ClientUnaryCall;
  deleteTemplate(
    request: DeleteTemplateRequest,
    callback: (error: ServiceError | null, response: DeleteTemplateResponse) => void,
  ): ClientUnaryCall;
  deleteTemplate(
    request: DeleteTemplateRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: DeleteTemplateResponse) => void,
  ): ClientUnaryCall;
  deleteTemplate(
    request: DeleteTemplateRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: DeleteTemplateResponse) => void,
  ): ClientUnaryCall;
  listTemplates(
    request: ListTemplatesRequest,
    callback: (error: ServiceError | null, response: ListTemplatesResponse) => void,
  ): ClientUnaryCall;
  listTemplates(
    request: ListTemplatesRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: ListTemplatesResponse) => void,
  ): ClientUnaryCall;
  listTemplates(
    request: ListTemplatesRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: ListTemplatesResponse) => void,
  ): ClientUnaryCall;
}

export const ReportServiceClient = makeGenericClientConstructor(
  ReportServiceService,
  "report.ReportService",
) as unknown as {
  new (address: string, credentials: ChannelCredentials, options?: Partial<ClientOptions>): ReportServiceClient;
  service: typeof ReportServiceService;
  serviceName: string;
};

function bytesFromBase64(b64: string): Uint8Array {
  if ((globalThis as any).Buffer) {
    return Uint8Array.from((globalThis as any).Buffer.from(b64, "base64"));
  } else {
    const bin = globalThis.atob(b64);
    const arr = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; ++i) {
      arr[i] = bin.charCodeAt(i);
    }
    return arr;
  }
}

function base64FromBytes(arr: Uint8Array): string {
  if ((globalThis as any).Buffer) {
    return (globalThis as any).Buffer.from(arr).toString("base64");
  } else {
    const bin: string[] = [];
    arr.forEach((byte) => {
      bin.push(globalThis.String.fromCharCode(byte));
    });
    return globalThis.btoa(bin.join(""));
  }
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
