// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.19.6
// source: wallet.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JoinRequestStatus int32

const (
	JoinRequestStatus_JOIN_REQUEST_STATUS_UNSPECIFIED JoinRequestStatus = 0
	JoinRequestStatus_JOIN_REQUEST_STATUS_PENDING     JoinRequestStatus = 1
	JoinRequestStatus_JOIN_REQUEST_STATUS_APPROVED    JoinRequestStatus = 2
	JoinRequestStatus_JOIN_REQUEST_STATUS_REJECTED    JoinRequestStatus = 3
)

// Enum value maps for JoinRequestStatus.
var (
	JoinRequestStatus_name = map[int32]string{
		0: "JOIN_REQUEST_STATUS_UNSPECIFIED",
		1: "JOIN_REQUEST_STATUS_PENDING",
		2: "JOIN_REQUEST_STATUS_APPROVED",
		3: "JOIN_REQUEST_STATUS_REJECTED",
	}
	JoinRequestStatus_value = map[string]int32{
		"JOIN_REQUEST_STATUS_UNSPECIFIED": 0,
		"JOIN_REQUEST_STATUS_PENDING":     1,
		"JOIN_REQUEST_STATUS_APPROVED":    2,
		"JOIN_REQUEST_STATUS_REJECTED":    3,
	}
)

func (x JoinRequestStatus) Enum() *JoinRequestStatus {
	p := new(JoinRequestStatus)
	*p = x
	return p
}

func (x JoinRequestStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (JoinRequestStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_wallet_proto_enumTypes[0].Descriptor()
}

func (JoinRequestStatus) Type() protoreflect.EnumType {
	return &file_wallet_proto_enumTypes[0]
}

func (x JoinRequestStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use JoinRequestStatus.Descriptor instead.
func (JoinRequestStatus) EnumDescriptor() ([]byte, []int) {
	return file_wallet_proto_rawDescGZIP(), []int{0}
}

type GetWalletsByUserIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWalletsByUserIdRequest) Reset() {
	*x = GetWalletsByUserIdRequest{}
	mi := &file_wallet_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWalletsByUserIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWalletsByUserIdRequest) ProtoMessage() {}

func (x *GetWalletsByUserIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWalletsByUserIdRequest.ProtoReflect.Descriptor instead.
func (*GetWalletsByUserIdRequest) Descriptor() ([]byte, []int) {
	return file_wallet_proto_rawDescGZIP(), []int{0}
}

func (x *GetWalletsByUserIdRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetWalletsByUserIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Wallets       []*Wallet              `protobuf:"bytes,1,rep,name=wallets,proto3" json:"wallets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWalletsByUserIdResponse) Reset() {
	*x = GetWalletsByUserIdResponse{}
	mi := &file_wallet_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWalletsByUserIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWalletsByUserIdResponse) ProtoMessage() {}

func (x *GetWalletsByUserIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWalletsByUserIdResponse.ProtoReflect.Descriptor instead.
func (*GetWalletsByUserIdResponse) Descriptor() ([]byte, []int) {
	return file_wallet_proto_rawDescGZIP(), []int{1}
}

func (x *GetWalletsByUserIdResponse) GetWallets() []*Wallet {
	if x != nil {
		return x.Wallets
	}
	return nil
}

type RefundWalletMemberBalanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WalletId      string                 `protobuf:"bytes,1,opt,name=wallet_id,json=walletId,proto3" json:"wallet_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Amount        int64                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefundWalletMemberBalanceRequest) Reset() {
	*x = RefundWalletMemberBalanceRequest{}
	mi := &file_wallet_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefundWalletMemberBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefundWalletMemberBalanceRequest) ProtoMessage() {}

func (x *RefundWalletMemberBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefundWalletMemberBalanceRequest.ProtoReflect.Descriptor instead.
func (*RefundWalletMemberBalanceRequest) Descriptor() ([]byte, []int) {
	return file_wallet_proto_rawDescGZIP(), []int{2}
}

func (x *RefundWalletMemberBalanceRequest) GetWalletId() string {
	if x != nil {
		return x.WalletId
	}
	return ""
}

func (x *RefundWalletMemberBalanceRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RefundWalletMemberBalanceRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type ApproveJoinRequestRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	JoinRequestId   string                 `protobuf:"bytes,1,opt,name=join_request_id,json=joinRequestId,proto3" json:"join_request_id,omitempty"`
	AllocationLimit int64                  `protobuf:"varint,2,opt,name=allocation_limit,json=allocationLimit,proto3" json:"allocation_limit,omitempty"`
	Permission      *Permission            `protobuf:"bytes,3,opt,name=permission,proto3" json:"permission,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ApproveJoinRequestRequest) Reset() {
	*x = ApproveJoinRequestRequest{}
	mi := &file_wallet_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApproveJoinRequestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApproveJoinRequestRequest) ProtoMessage() {}

func (x *ApproveJoinRequestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApproveJoinRequestRequest.ProtoReflect.Descriptor instead.
func (*ApproveJoinRequestRequest) Descriptor() ([]byte, []int) {
	return file_wallet_proto_rawDescGZIP(), []int{3}
}

func (x *ApproveJoinRequestRequest) GetJoinRequestId() string {
	if x != nil {
		return x.JoinRequestId
	}
	return ""
}

func (x *ApproveJoinRequestRequest) GetAllocationLimit() int64 {
	if x != nil {
		return x.AllocationLimit
	}
	return 0
}

func (x *ApproveJoinRequestRequest) GetPermission() *Permission {
	if x != nil {
		return x.Permission
	}
	return nil
}

type RejectJoinRequestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JoinRequestId string                 `protobuf:"bytes,1,opt,name=join_request_id,json=joinRequestId,proto3" json:"join_request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RejectJoinRequestRequest) Reset() {
	*x = RejectJoinRequestRequest{}
	mi := &file_wallet_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RejectJoinRequestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RejectJoinRequestRequest) ProtoMessage() {}

func (x *RejectJoinRequestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RejectJoinRequestRequest.ProtoReflect.Descriptor instead.
func (*RejectJoinRequestRequest) Descriptor() ([]byte, []int) {
	return file_wallet_proto_rawDescGZIP(), []int{4}
}

func (x *RejectJoinRequestRequest) GetJoinRequestId() string {
	if x != nil {
		return x.JoinRequestId
	}
	return ""
}

type RequestJoinWalletRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	InvitationCode string                 `protobuf:"bytes,1,opt,name=invitation_code,json=invitationCode,proto3" json:"invitation_code,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RequestJoinWalletRequest) Reset() {
	*x = RequestJoinWalletRequest{}
	mi := &file_wallet_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestJoinWalletRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestJoinWalletRequest) ProtoMessage() {}

func (x *RequestJoinWalletRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestJoinWalletRequest.ProtoReflect.Descriptor instead.
func (*RequestJoinWalletRequest) Descriptor() ([]byte, []int) {
	return file_wallet_proto_rawDescGZIP(), []int{5}
}

func (x *RequestJoinWalletRequest) GetInvitationCode() string {
	if x != nil {
		return x.InvitationCode
	}
	return ""
}

type WalletJoinRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	WalletId      string                 `protobuf:"bytes,2,opt,name=wallet_id,json=walletId,proto3" json:"wallet_id,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Status        JoinRequestStatus      `protobuf:"varint,4,opt,name=status,proto3,enum=wallet.JoinRequestStatus" json:"status,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WalletJoinRequest) Reset() {
	*x = WalletJoinRequest{}
	mi := &file_wallet_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WalletJoinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WalletJoinRequest) ProtoMessage() {}

func (x *WalletJoinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WalletJoinRequest.ProtoReflect.Descriptor instead.
func (*WalletJoinRequest) Descriptor() ([]byte, []int) {
	return file_wallet_proto_rawDescGZIP(), []int{6}
}

func (x *WalletJoinRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *WalletJoinRequest) GetWalletId() string {
	if x != nil {
		return x.WalletId
	}
	return ""
}

func (x *WalletJoinRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *WalletJoinRequest) GetStatus() JoinRequestStatus {
	if x != nil {
		return x.Status
	}
	return JoinRequestStatus_JOIN_REQUEST_STATUS_UNSPECIFIED
}

func (x *WalletJoinRequest) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type GetWalletJoinRequestsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WalletId      string                 `protobuf:"bytes,1,opt,name=wallet_id,json=walletId,proto3" json:"wallet_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWalletJoinRequestsRequest) Reset() {
	*x = GetWalletJoinRequestsRequest{}
	mi := &file_wallet_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWalletJoinRequestsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWalletJoinRequestsRequest) ProtoMessage() {}

func (x *GetWalletJoinRequestsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWalletJoinRequestsRequest.ProtoReflect.Descriptor instead.
func (*GetWalletJoinRequestsRequest) Descriptor() ([]byte, []int) {
	return file_wallet_proto_rawDescGZIP(), []int{7}
}

func (x *GetWalletJoinRequestsRequest) GetWalletId() string {
	if x != nil {
		return x.WalletId
	}
	return ""
}

type GetWalletJoinRequestsResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	WalletJoinRequests []*WalletJoinRequest   `protobuf:"bytes,1,rep,name=wallet_join_requests,json=walletJoinRequests,proto3" json:"wallet_join_requests,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetWalletJoinRequestsResponse) Reset() {
	*x = GetWalletJoinRequestsResponse{}
	mi := &file_wallet_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWalletJoinRequestsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWalletJoinRequestsResponse) ProtoMessage() {}

func (x *GetWalletJoinRequestsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWalletJoinRequestsResponse.ProtoReflect.Descriptor instead.
func (*GetWalletJoinRequestsResponse) Descriptor() ([]byte, []int) {
	return file_wallet_proto_rawDescGZIP(), []int{8}
}

func (x *GetWalletJoinRequestsResponse) GetWalletJoinRequests() []*WalletJoinRequest {
	if x != nil {
		return x.WalletJoinRequests
	}
	return nil
}

type WalletInvitation struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	WalletId       string                 `protobuf:"bytes,2,opt,name=wallet_id,json=walletId,proto3" json:"wallet_id,omitempty"`
	InvitationCode string                 `protobuf:"bytes,3,opt,name=invitation_code,json=invitationCode,proto3" json:"invitation_code,omitempty"`
	CreatedBy      string                 `protobuf:"bytes,4,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *WalletInvitation) Reset() {
	*x = WalletInvitation{}
	mi := &file_wallet_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WalletInvitation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WalletInvitation) ProtoMessage() {}

func (x *WalletInvitation) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WalletInvitation.ProtoReflect.Descriptor instead.
func (*WalletInvitation) Descriptor() ([]byte, []int) {
	return file_wallet_proto_rawDescGZIP(), []int{9}
}

func (x *WalletInvitation) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *WalletInvitation) GetWalletId() string {
	if x != nil {
		return x.WalletId
	}
	return ""
}

func (x *WalletInvitation) GetInvitationCode() string {
	if x != nil {
		return x.InvitationCode
	}
	return ""
}

func (x *WalletInvitation) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

type GetWalletInvitationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WalletId      string                 `protobuf:"bytes,1,opt,name=wallet_id,json=walletId,proto3" json:"wallet_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWalletInvitationRequest) Reset() {
	*x = GetWalletInvitationRequest{}
	mi := &file_wallet_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWalletInvitationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWalletInvitationRequest) ProtoMessage() {}

func (x *GetWalletInvitationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWalletInvitationRequest.ProtoReflect.Descriptor instead.
func (*GetWalletInvitationRequest) Descriptor() ([]byte, []int) {
	return file_wallet_proto_rawDescGZIP(), []int{10}
}

func (x *GetWalletInvitationRequest) GetWalletId() string {
	if x != nil {
		return x.WalletId
	}
	return ""
}

type GetWalletInvitationResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	WalletInvitation *WalletInvitation      `protobuf:"bytes,1,opt,name=wallet_invitation,json=walletInvitation,proto3" json:"wallet_invitation,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetWalletInvitationResponse) Reset() {
	*x = GetWalletInvitationResponse{}
	mi := &file_wallet_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWalletInvitationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWalletInvitationResponse) ProtoMessage() {}

func (x *GetWalletInvitationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWalletInvitationResponse.ProtoReflect.Descriptor instead.
func (*GetWalletInvitationResponse) Descriptor() ([]byte, []int) {
	return file_wallet_proto_rawDescGZIP(), []int{11}
}

func (x *GetWalletInvitationResponse) GetWalletInvitation() *WalletInvitation {
	if x != nil {
		return x.WalletInvitation
	}
	return nil
}

type RegenerateWalletInvitationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WalletId      string                 `protobuf:"bytes,1,opt,name=wallet_id,json=walletId,proto3" json:"wallet_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegenerateWalletInvitationRequest) Reset() {
	*x = RegenerateWalletInvitationRequest{}
	mi := &file_wallet_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegenerateWalletInvitationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegenerateWalletInvitationRequest) ProtoMessage() {}

func (x *RegenerateWalletInvitationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegenerateWalletInvitationRequest.ProtoReflect.Descriptor instead.
func (*RegenerateWalletInvitationRequest) Descriptor() ([]byte, []int) {
	return file_wallet_proto_rawDescGZIP(), []int{12}
}

func (x *RegenerateWalletInvitationRequest) GetWalletId() string {
	if x != nil {
		return x.WalletId
	}
	return ""
}

type RegenerateWalletInvitationResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	WalletInvitation *WalletInvitation      `protobuf:"bytes,1,opt,name=wallet_invitation,json=walletInvitation,proto3" json:"wallet_invitation,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RegenerateWalletInvitationResponse) Reset() {
	*x = RegenerateWalletInvitationResponse{}
	mi := &file_wallet_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegenerateWalletInvitationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegenerateWalletInvitationResponse) ProtoMessage() {}

func (x *RegenerateWalletInvitationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegenerateWalletInvitationResponse.ProtoReflect.Descriptor instead.
func (*RegenerateWalletInvitationResponse) Descriptor() ([]byte, []int) {
	return file_wallet_proto_rawDescGZIP(), []int{13}
}

func (x *RegenerateWalletInvitationResponse) GetWalletInvitation() *WalletInvitation {
	if x != nil {
		return x.WalletInvitation
	}
	return nil
}

type RequestJoinWalletResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JoinRequestId string                 `protobuf:"bytes,1,opt,name=join_request_id,json=joinRequestId,proto3" json:"join_request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestJoinWalletResponse) Reset() {
	*x = RequestJoinWalletResponse{}
	mi := &file_wallet_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestJoinWalletResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestJoinWalletResponse) ProtoMessage() {}

func (x *RequestJoinWalletResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestJoinWalletResponse.ProtoReflect.Descriptor instead.
func (*RequestJoinWalletResponse) Descriptor() ([]byte, []int) {
	return file_wallet_proto_rawDescGZIP(), []int{14}
}

func (x *RequestJoinWalletResponse) GetJoinRequestId() string {
	if x != nil {
		return x.JoinRequestId
	}
	return ""
}

type Wallet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	OwnerId       string                 `protobuf:"bytes,3,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	TotalBalance  int64                  `protobuf:"varint,4,opt,name=total_balance,json=totalBalance,proto3" json:"total_balance,omitempty"`
	Currency      string                 `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Wallet) Reset() {
	*x = Wallet{}
	mi := &file_wallet_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Wallet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Wallet) ProtoMessage() {}

func (x *Wallet) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Wallet.ProtoReflect.Descriptor instead.
func (*Wallet) Descriptor() ([]byte, []int) {
	return file_wallet_proto_rawDescGZIP(), []int{15}
}

func (x *Wallet) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Wallet) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Wallet) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *Wallet) GetTotalBalance() int64 {
	if x != nil {
		return x.TotalBalance
	}
	return 0
}

func (x *Wallet) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

type Permission struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ManageUser      bool                   `protobuf:"varint,1,opt,name=manage_user,json=manageUser,proto3" json:"manage_user,omitempty"`
	AllocateBalance bool                   `protobuf:"varint,2,opt,name=allocate_balance,json=allocateBalance,proto3" json:"allocate_balance,omitempty"`
	GenerateReport  bool                   `protobuf:"varint,3,opt,name=generate_report,json=generateReport,proto3" json:"generate_report,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Permission) Reset() {
	*x = Permission{}
	mi := &file_wallet_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Permission) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Permission) ProtoMessage() {}

func (x *Permission) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Permission.ProtoReflect.Descriptor instead.
func (*Permission) Descriptor() ([]byte, []int) {
	return file_wallet_proto_rawDescGZIP(), []int{16}
}

func (x *Permission) GetManageUser() bool {
	if x != nil {
		return x.ManageUser
	}
	return false
}

func (x *Permission) GetAllocateBalance() bool {
	if x != nil {
		return x.AllocateBalance
	}
	return false
}

func (x *Permission) GetGenerateReport() bool {
	if x != nil {
		return x.GenerateReport
	}
	return false
}

type WalletMember struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	WalletId        string                 `protobuf:"bytes,1,opt,name=wallet_id,json=walletId,proto3" json:"wallet_id,omitempty"`
	UserId          string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AllocationLimit int64                  `protobuf:"varint,3,opt,name=allocation_limit,json=allocationLimit,proto3" json:"allocation_limit,omitempty"`
	AllocationUsed  int64                  `protobuf:"varint,4,opt,name=allocation_used,json=allocationUsed,proto3" json:"allocation_used,omitempty"`
	Permission      *Permission            `protobuf:"bytes,5,opt,name=permission,proto3" json:"permission,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *WalletMember) Reset() {
	*x = WalletMember{}
	mi := &file_wallet_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WalletMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WalletMember) ProtoMessage() {}

func (x *WalletMember) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WalletMember.ProtoReflect.Descriptor instead.
func (*WalletMember) Descriptor() ([]byte, []int) {
	return file_wallet_proto_rawDescGZIP(), []int{17}
}

func (x *WalletMember) GetWalletId() string {
	if x != nil {
		return x.WalletId
	}
	return ""
}

func (x *WalletMember) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *WalletMember) GetAllocationLimit() int64 {
	if x != nil {
		return x.AllocationLimit
	}
	return 0
}

func (x *WalletMember) GetAllocationUsed() int64 {
	if x != nil {
		return x.AllocationUsed
	}
	return 0
}

func (x *WalletMember) GetPermission() *Permission {
	if x != nil {
		return x.Permission
	}
	return nil
}

type DeleteWalletRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WalletId      string                 `protobuf:"bytes,1,opt,name=wallet_id,json=walletId,proto3" json:"wallet_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteWalletRequest) Reset() {
	*x = DeleteWalletRequest{}
	mi := &file_wallet_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteWalletRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteWalletRequest) ProtoMessage() {}

func (x *DeleteWalletRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteWalletRequest.ProtoReflect.Descriptor instead.
func (*DeleteWalletRequest) Descriptor() ([]byte, []int) {
	return file_wallet_proto_rawDescGZIP(), []int{18}
}

func (x *DeleteWalletRequest) GetWalletId() string {
	if x != nil {
		return x.WalletId
	}
	return ""
}

type GetWalletRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WalletId      string                 `protobuf:"bytes,1,opt,name=wallet_id,json=walletId,proto3" json:"wallet_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWalletRequest) Reset() {
	*x = GetWalletRequest{}
	mi := &file_wallet_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWalletRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWalletRequest) ProtoMessage() {}

func (x *GetWalletRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWalletRequest.ProtoReflect.Descriptor instead.
func (*GetWalletRequest) Descriptor() ([]byte, []int) {
	return file_wallet_proto_rawDescGZIP(), []int{19}
}

func (x *GetWalletRequest) GetWalletId() string {
	if x != nil {
		return x.WalletId
	}
	return ""
}

type AllocateBalanceRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	WalletId        string                 `protobuf:"bytes,1,opt,name=wallet_id,json=walletId,proto3" json:"wallet_id,omitempty"`
	UserId          string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AllocationLimit int64                  `protobuf:"varint,3,opt,name=allocation_limit,json=allocationLimit,proto3" json:"allocation_limit,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AllocateBalanceRequest) Reset() {
	*x = AllocateBalanceRequest{}
	mi := &file_wallet_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllocateBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllocateBalanceRequest) ProtoMessage() {}

func (x *AllocateBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllocateBalanceRequest.ProtoReflect.Descriptor instead.
func (*AllocateBalanceRequest) Descriptor() ([]byte, []int) {
	return file_wallet_proto_rawDescGZIP(), []int{20}
}

func (x *AllocateBalanceRequest) GetWalletId() string {
	if x != nil {
		return x.WalletId
	}
	return ""
}

func (x *AllocateBalanceRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AllocateBalanceRequest) GetAllocationLimit() int64 {
	if x != nil {
		return x.AllocationLimit
	}
	return 0
}

type CreateWalletRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	WalletName     string                 `protobuf:"bytes,1,opt,name=wallet_name,json=walletName,proto3" json:"wallet_name,omitempty"`
	InitialBalance int64                  `protobuf:"varint,2,opt,name=initial_balance,json=initialBalance,proto3" json:"initial_balance,omitempty"`
	Currency       string                 `protobuf:"bytes,3,opt,name=currency,proto3" json:"currency,omitempty"`
	OwnerId        string                 `protobuf:"bytes,4,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateWalletRequest) Reset() {
	*x = CreateWalletRequest{}
	mi := &file_wallet_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWalletRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWalletRequest) ProtoMessage() {}

func (x *CreateWalletRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWalletRequest.ProtoReflect.Descriptor instead.
func (*CreateWalletRequest) Descriptor() ([]byte, []int) {
	return file_wallet_proto_rawDescGZIP(), []int{21}
}

func (x *CreateWalletRequest) GetWalletName() string {
	if x != nil {
		return x.WalletName
	}
	return ""
}

func (x *CreateWalletRequest) GetInitialBalance() int64 {
	if x != nil {
		return x.InitialBalance
	}
	return 0
}

func (x *CreateWalletRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *CreateWalletRequest) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

type UpdateWalletRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WalletId      string                 `protobuf:"bytes,1,opt,name=wallet_id,json=walletId,proto3" json:"wallet_id,omitempty"`
	WalletName    string                 `protobuf:"bytes,2,opt,name=wallet_name,json=walletName,proto3" json:"wallet_name,omitempty"`
	Currency      string                 `protobuf:"bytes,3,opt,name=currency,proto3" json:"currency,omitempty"`
	UpdateMask    *fieldmaskpb.FieldMask `protobuf:"bytes,4,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateWalletRequest) Reset() {
	*x = UpdateWalletRequest{}
	mi := &file_wallet_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateWalletRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateWalletRequest) ProtoMessage() {}

func (x *UpdateWalletRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateWalletRequest.ProtoReflect.Descriptor instead.
func (*UpdateWalletRequest) Descriptor() ([]byte, []int) {
	return file_wallet_proto_rawDescGZIP(), []int{22}
}

func (x *UpdateWalletRequest) GetWalletId() string {
	if x != nil {
		return x.WalletId
	}
	return ""
}

func (x *UpdateWalletRequest) GetWalletName() string {
	if x != nil {
		return x.WalletName
	}
	return ""
}

func (x *UpdateWalletRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *UpdateWalletRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

type ValidateAndDeductBalanceRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	WalletId       string                 `protobuf:"bytes,1,opt,name=wallet_id,json=walletId,proto3" json:"wallet_id,omitempty"`
	UserId         string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Amount         int64                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,4,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ValidateAndDeductBalanceRequest) Reset() {
	*x = ValidateAndDeductBalanceRequest{}
	mi := &file_wallet_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateAndDeductBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateAndDeductBalanceRequest) ProtoMessage() {}

func (x *ValidateAndDeductBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateAndDeductBalanceRequest.ProtoReflect.Descriptor instead.
func (*ValidateAndDeductBalanceRequest) Descriptor() ([]byte, []int) {
	return file_wallet_proto_rawDescGZIP(), []int{23}
}

func (x *ValidateAndDeductBalanceRequest) GetWalletId() string {
	if x != nil {
		return x.WalletId
	}
	return ""
}

func (x *ValidateAndDeductBalanceRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ValidateAndDeductBalanceRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *ValidateAndDeductBalanceRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type GetWalletMembersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WalletId      string                 `protobuf:"bytes,1,opt,name=wallet_id,json=walletId,proto3" json:"wallet_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWalletMembersRequest) Reset() {
	*x = GetWalletMembersRequest{}
	mi := &file_wallet_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWalletMembersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWalletMembersRequest) ProtoMessage() {}

func (x *GetWalletMembersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWalletMembersRequest.ProtoReflect.Descriptor instead.
func (*GetWalletMembersRequest) Descriptor() ([]byte, []int) {
	return file_wallet_proto_rawDescGZIP(), []int{24}
}

func (x *GetWalletMembersRequest) GetWalletId() string {
	if x != nil {
		return x.WalletId
	}
	return ""
}

type DeleteWalletMemberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WalletId      string                 `protobuf:"bytes,1,opt,name=wallet_id,json=walletId,proto3" json:"wallet_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteWalletMemberRequest) Reset() {
	*x = DeleteWalletMemberRequest{}
	mi := &file_wallet_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteWalletMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteWalletMemberRequest) ProtoMessage() {}

func (x *DeleteWalletMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteWalletMemberRequest.ProtoReflect.Descriptor instead.
func (*DeleteWalletMemberRequest) Descriptor() ([]byte, []int) {
	return file_wallet_proto_rawDescGZIP(), []int{25}
}

func (x *DeleteWalletMemberRequest) GetWalletId() string {
	if x != nil {
		return x.WalletId
	}
	return ""
}

func (x *DeleteWalletMemberRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type AdjustBalanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WalletId      string                 `protobuf:"bytes,1,opt,name=wallet_id,json=walletId,proto3" json:"wallet_id,omitempty"`
	Amount        int64                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"` // can be + or -
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdjustBalanceRequest) Reset() {
	*x = AdjustBalanceRequest{}
	mi := &file_wallet_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdjustBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdjustBalanceRequest) ProtoMessage() {}

func (x *AdjustBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdjustBalanceRequest.ProtoReflect.Descriptor instead.
func (*AdjustBalanceRequest) Descriptor() ([]byte, []int) {
	return file_wallet_proto_rawDescGZIP(), []int{26}
}

func (x *AdjustBalanceRequest) GetWalletId() string {
	if x != nil {
		return x.WalletId
	}
	return ""
}

func (x *AdjustBalanceRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

// response nihh
type AllocateBalanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WalletMember  *WalletMember          `protobuf:"bytes,1,opt,name=wallet_member,json=walletMember,proto3" json:"wallet_member,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllocateBalanceResponse) Reset() {
	*x = AllocateBalanceResponse{}
	mi := &file_wallet_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllocateBalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllocateBalanceResponse) ProtoMessage() {}

func (x *AllocateBalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllocateBalanceResponse.ProtoReflect.Descriptor instead.
func (*AllocateBalanceResponse) Descriptor() ([]byte, []int) {
	return file_wallet_proto_rawDescGZIP(), []int{27}
}

func (x *AllocateBalanceResponse) GetWalletMember() *WalletMember {
	if x != nil {
		return x.WalletMember
	}
	return nil
}

type GetWalletResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Wallet        *Wallet                `protobuf:"bytes,1,opt,name=wallet,proto3" json:"wallet,omitempty"`
	Members       []*WalletMember        `protobuf:"bytes,2,rep,name=members,proto3" json:"members,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWalletResponse) Reset() {
	*x = GetWalletResponse{}
	mi := &file_wallet_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWalletResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWalletResponse) ProtoMessage() {}

func (x *GetWalletResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWalletResponse.ProtoReflect.Descriptor instead.
func (*GetWalletResponse) Descriptor() ([]byte, []int) {
	return file_wallet_proto_rawDescGZIP(), []int{28}
}

func (x *GetWalletResponse) GetWallet() *Wallet {
	if x != nil {
		return x.Wallet
	}
	return nil
}

func (x *GetWalletResponse) GetMembers() []*WalletMember {
	if x != nil {
		return x.Members
	}
	return nil
}

type UpdateWalletResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Wallet        *Wallet                `protobuf:"bytes,1,opt,name=wallet,proto3" json:"wallet,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateWalletResponse) Reset() {
	*x = UpdateWalletResponse{}
	mi := &file_wallet_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateWalletResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateWalletResponse) ProtoMessage() {}

func (x *UpdateWalletResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateWalletResponse.ProtoReflect.Descriptor instead.
func (*UpdateWalletResponse) Descriptor() ([]byte, []int) {
	return file_wallet_proto_rawDescGZIP(), []int{29}
}

func (x *UpdateWalletResponse) GetWallet() *Wallet {
	if x != nil {
		return x.Wallet
	}
	return nil
}

type CreateWalletResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Wallet        *Wallet                `protobuf:"bytes,1,opt,name=wallet,proto3" json:"wallet,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateWalletResponse) Reset() {
	*x = CreateWalletResponse{}
	mi := &file_wallet_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWalletResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWalletResponse) ProtoMessage() {}

func (x *CreateWalletResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWalletResponse.ProtoReflect.Descriptor instead.
func (*CreateWalletResponse) Descriptor() ([]byte, []int) {
	return file_wallet_proto_rawDescGZIP(), []int{30}
}

func (x *CreateWalletResponse) GetWallet() *Wallet {
	if x != nil {
		return x.Wallet
	}
	return nil
}

type ValidateAndDeductBalanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateAndDeductBalanceResponse) Reset() {
	*x = ValidateAndDeductBalanceResponse{}
	mi := &file_wallet_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateAndDeductBalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateAndDeductBalanceResponse) ProtoMessage() {}

func (x *ValidateAndDeductBalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateAndDeductBalanceResponse.ProtoReflect.Descriptor instead.
func (*ValidateAndDeductBalanceResponse) Descriptor() ([]byte, []int) {
	return file_wallet_proto_rawDescGZIP(), []int{31}
}

type GetWalletMembersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WalletMembers []*WalletMember        `protobuf:"bytes,1,rep,name=wallet_members,json=walletMembers,proto3" json:"wallet_members,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWalletMembersResponse) Reset() {
	*x = GetWalletMembersResponse{}
	mi := &file_wallet_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWalletMembersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWalletMembersResponse) ProtoMessage() {}

func (x *GetWalletMembersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWalletMembersResponse.ProtoReflect.Descriptor instead.
func (*GetWalletMembersResponse) Descriptor() ([]byte, []int) {
	return file_wallet_proto_rawDescGZIP(), []int{32}
}

func (x *GetWalletMembersResponse) GetWalletMembers() []*WalletMember {
	if x != nil {
		return x.WalletMembers
	}
	return nil
}

type DeleteWalletMemberResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WalletMembers []*WalletMember        `protobuf:"bytes,1,rep,name=wallet_members,json=walletMembers,proto3" json:"wallet_members,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteWalletMemberResponse) Reset() {
	*x = DeleteWalletMemberResponse{}
	mi := &file_wallet_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteWalletMemberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteWalletMemberResponse) ProtoMessage() {}

func (x *DeleteWalletMemberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteWalletMemberResponse.ProtoReflect.Descriptor instead.
func (*DeleteWalletMemberResponse) Descriptor() ([]byte, []int) {
	return file_wallet_proto_rawDescGZIP(), []int{33}
}

func (x *DeleteWalletMemberResponse) GetWalletMembers() []*WalletMember {
	if x != nil {
		return x.WalletMembers
	}
	return nil
}

type AdjustBalanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Wallet        *Wallet                `protobuf:"bytes,1,opt,name=wallet,proto3" json:"wallet,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdjustBalanceResponse) Reset() {
	*x = AdjustBalanceResponse{}
	mi := &file_wallet_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdjustBalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdjustBalanceResponse) ProtoMessage() {}

func (x *AdjustBalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdjustBalanceResponse.ProtoReflect.Descriptor instead.
func (*AdjustBalanceResponse) Descriptor() ([]byte, []int) {
	return file_wallet_proto_rawDescGZIP(), []int{34}
}

func (x *AdjustBalanceResponse) GetWallet() *Wallet {
	if x != nil {
		return x.Wallet
	}
	return nil
}

var File_wallet_proto protoreflect.FileDescriptor

const file_wallet_proto_rawDesc = "" +
	"\n" +
	"\fwallet.proto\x12\x06wallet\x1a google/protobuf/field_mask.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"4\n" +
	"\x19GetWalletsByUserIdRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"F\n" +
	"\x1aGetWalletsByUserIdResponse\x12(\n" +
	"\awallets\x18\x01 \x03(\v2\x0e.wallet.WalletR\awallets\"p\n" +
	" RefundWalletMemberBalanceRequest\x12\x1b\n" +
	"\twallet_id\x18\x01 \x01(\tR\bwalletId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x03R\x06amount\"\xa2\x01\n" +
	"\x19ApproveJoinRequestRequest\x12&\n" +
	"\x0fjoin_request_id\x18\x01 \x01(\tR\rjoinRequestId\x12)\n" +
	"\x10allocation_limit\x18\x02 \x01(\x03R\x0fallocationLimit\x122\n" +
	"\n" +
	"permission\x18\x03 \x01(\v2\x12.wallet.PermissionR\n" +
	"permission\"B\n" +
	"\x18RejectJoinRequestRequest\x12&\n" +
	"\x0fjoin_request_id\x18\x01 \x01(\tR\rjoinRequestId\"C\n" +
	"\x18RequestJoinWalletRequest\x12'\n" +
	"\x0finvitation_code\x18\x01 \x01(\tR\x0einvitationCode\"\xc7\x01\n" +
	"\x11WalletJoinRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\twallet_id\x18\x02 \x01(\tR\bwalletId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x121\n" +
	"\x06status\x18\x04 \x01(\x0e2\x19.wallet.JoinRequestStatusR\x06status\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\";\n" +
	"\x1cGetWalletJoinRequestsRequest\x12\x1b\n" +
	"\twallet_id\x18\x01 \x01(\tR\bwalletId\"l\n" +
	"\x1dGetWalletJoinRequestsResponse\x12K\n" +
	"\x14wallet_join_requests\x18\x01 \x03(\v2\x19.wallet.WalletJoinRequestR\x12walletJoinRequests\"\x87\x01\n" +
	"\x10WalletInvitation\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\twallet_id\x18\x02 \x01(\tR\bwalletId\x12'\n" +
	"\x0finvitation_code\x18\x03 \x01(\tR\x0einvitationCode\x12\x1d\n" +
	"\n" +
	"created_by\x18\x04 \x01(\tR\tcreatedBy\"9\n" +
	"\x1aGetWalletInvitationRequest\x12\x1b\n" +
	"\twallet_id\x18\x01 \x01(\tR\bwalletId\"d\n" +
	"\x1bGetWalletInvitationResponse\x12E\n" +
	"\x11wallet_invitation\x18\x01 \x01(\v2\x18.wallet.WalletInvitationR\x10walletInvitation\"@\n" +
	"!RegenerateWalletInvitationRequest\x12\x1b\n" +
	"\twallet_id\x18\x01 \x01(\tR\bwalletId\"k\n" +
	"\"RegenerateWalletInvitationResponse\x12E\n" +
	"\x11wallet_invitation\x18\x01 \x01(\v2\x18.wallet.WalletInvitationR\x10walletInvitation\"C\n" +
	"\x19RequestJoinWalletResponse\x12&\n" +
	"\x0fjoin_request_id\x18\x01 \x01(\tR\rjoinRequestId\"\x88\x01\n" +
	"\x06Wallet\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x19\n" +
	"\bowner_id\x18\x03 \x01(\tR\aownerId\x12#\n" +
	"\rtotal_balance\x18\x04 \x01(\x03R\ftotalBalance\x12\x1a\n" +
	"\bcurrency\x18\x05 \x01(\tR\bcurrency\"\x81\x01\n" +
	"\n" +
	"Permission\x12\x1f\n" +
	"\vmanage_user\x18\x01 \x01(\bR\n" +
	"manageUser\x12)\n" +
	"\x10allocate_balance\x18\x02 \x01(\bR\x0fallocateBalance\x12'\n" +
	"\x0fgenerate_report\x18\x03 \x01(\bR\x0egenerateReport\"\xcc\x01\n" +
	"\fWalletMember\x12\x1b\n" +
	"\twallet_id\x18\x01 \x01(\tR\bwalletId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12)\n" +
	"\x10allocation_limit\x18\x03 \x01(\x03R\x0fallocationLimit\x12'\n" +
	"\x0fallocation_used\x18\x04 \x01(\x03R\x0eallocationUsed\x122\n" +
	"\n" +
	"permission\x18\x05 \x01(\v2\x12.wallet.PermissionR\n" +
	"permission\"2\n" +
	"\x13DeleteWalletRequest\x12\x1b\n" +
	"\twallet_id\x18\x01 \x01(\tR\bwalletId\"/\n" +
	"\x10GetWalletRequest\x12\x1b\n" +
	"\twallet_id\x18\x01 \x01(\tR\bwalletId\"y\n" +
	"\x16AllocateBalanceRequest\x12\x1b\n" +
	"\twallet_id\x18\x01 \x01(\tR\bwalletId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12)\n" +
	"\x10allocation_limit\x18\x03 \x01(\x03R\x0fallocationLimit\"\x96\x01\n" +
	"\x13CreateWalletRequest\x12\x1f\n" +
	"\vwallet_name\x18\x01 \x01(\tR\n" +
	"walletName\x12'\n" +
	"\x0finitial_balance\x18\x02 \x01(\x03R\x0einitialBalance\x12\x1a\n" +
	"\bcurrency\x18\x03 \x01(\tR\bcurrency\x12\x19\n" +
	"\bowner_id\x18\x04 \x01(\tR\aownerId\"\xac\x01\n" +
	"\x13UpdateWalletRequest\x12\x1b\n" +
	"\twallet_id\x18\x01 \x01(\tR\bwalletId\x12\x1f\n" +
	"\vwallet_name\x18\x02 \x01(\tR\n" +
	"walletName\x12\x1a\n" +
	"\bcurrency\x18\x03 \x01(\tR\bcurrency\x12;\n" +
	"\vupdate_mask\x18\x04 \x01(\v2\x1a.google.protobuf.FieldMaskR\n" +
	"updateMask\"\x98\x01\n" +
	"\x1fValidateAndDeductBalanceRequest\x12\x1b\n" +
	"\twallet_id\x18\x01 \x01(\tR\bwalletId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x03R\x06amount\x12'\n" +
	"\x0fidempotency_key\x18\x04 \x01(\tR\x0eidempotencyKey\"6\n" +
	"\x17GetWalletMembersRequest\x12\x1b\n" +
	"\twallet_id\x18\x01 \x01(\tR\bwalletId\"Q\n" +
	"\x19DeleteWalletMemberRequest\x12\x1b\n" +
	"\twallet_id\x18\x01 \x01(\tR\bwalletId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"K\n" +
	"\x14AdjustBalanceRequest\x12\x1b\n" +
	"\twallet_id\x18\x01 \x01(\tR\bwalletId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x03R\x06amount\"T\n" +
	"\x17AllocateBalanceResponse\x129\n" +
	"\rwallet_member\x18\x01 \x01(\v2\x14.wallet.WalletMemberR\fwalletMember\"k\n" +
	"\x11GetWalletResponse\x12&\n" +
	"\x06wallet\x18\x01 \x01(\v2\x0e.wallet.WalletR\x06wallet\x12.\n" +
	"\amembers\x18\x02 \x03(\v2\x14.wallet.WalletMemberR\amembers\">\n" +
	"\x14UpdateWalletResponse\x12&\n" +
	"\x06wallet\x18\x01 \x01(\v2\x0e.wallet.WalletR\x06wallet\">\n" +
	"\x14CreateWalletResponse\x12&\n" +
	"\x06wallet\x18\x01 \x01(\v2\x0e.wallet.WalletR\x06wallet\"\"\n" +
	" ValidateAndDeductBalanceResponse\"W\n" +
	"\x18GetWalletMembersResponse\x12;\n" +
	"\x0ewallet_members\x18\x01 \x03(\v2\x14.wallet.WalletMemberR\rwalletMembers\"Y\n" +
	"\x1aDeleteWalletMemberResponse\x12;\n" +
	"\x0ewallet_members\x18\x01 \x03(\v2\x14.wallet.WalletMemberR\rwalletMembers\"?\n" +
	"\x15AdjustBalanceResponse\x12&\n" +
	"\x06wallet\x18\x01 \x01(\v2\x0e.wallet.WalletR\x06wallet*\x9d\x01\n" +
	"\x11JoinRequestStatus\x12#\n" +
	"\x1fJOIN_REQUEST_STATUS_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bJOIN_REQUEST_STATUS_PENDING\x10\x01\x12 \n" +
	"\x1cJOIN_REQUEST_STATUS_APPROVED\x10\x02\x12 \n" +
	"\x1cJOIN_REQUEST_STATUS_REJECTED\x10\x032\xdd\v\n" +
	"\rWalletService\x12K\n" +
	"\fCreateWallet\x12\x1b.wallet.CreateWalletRequest\x1a\x1c.wallet.CreateWalletResponse\"\x00\x12K\n" +
	"\fUpdateWallet\x12\x1b.wallet.UpdateWalletRequest\x1a\x1c.wallet.UpdateWalletResponse\"\x00\x12E\n" +
	"\fDeleteWallet\x12\x1b.wallet.DeleteWalletRequest\x1a\x16.google.protobuf.Empty\"\x00\x12B\n" +
	"\tGetWallet\x12\x18.wallet.GetWalletRequest\x1a\x19.wallet.GetWalletResponse\"\x00\x12]\n" +
	"\x18ValidateAndDeductBalance\x12'.wallet.ValidateAndDeductBalanceRequest\x1a\x16.google.protobuf.Empty\"\x00\x12W\n" +
	"\x10GetWalletMembers\x12\x1f.wallet.GetWalletMembersRequest\x1a .wallet.GetWalletMembersResponse\"\x00\x12Q\n" +
	"\x12DeleteWalletMember\x12!.wallet.DeleteWalletMemberRequest\x1a\x16.google.protobuf.Empty\"\x00\x12K\n" +
	"\x0fAllocateBalance\x12\x1e.wallet.AllocateBalanceRequest\x1a\x16.google.protobuf.Empty\"\x00\x12N\n" +
	"\rAdjustBalance\x12\x1c.wallet.AdjustBalanceRequest\x1a\x1d.wallet.AdjustBalanceResponse\"\x00\x12`\n" +
	"\x13GetWalletInvitation\x12\".wallet.GetWalletInvitationRequest\x1a#.wallet.GetWalletInvitationResponse\"\x00\x12u\n" +
	"\x1aRegenerateWalletInvitation\x12).wallet.RegenerateWalletInvitationRequest\x1a*.wallet.RegenerateWalletInvitationResponse\"\x00\x12Z\n" +
	"\x11RequestJoinWallet\x12 .wallet.RequestJoinWalletRequest\x1a!.wallet.RequestJoinWalletResponse\"\x00\x12Q\n" +
	"\x12ApproveJoinRequest\x12!.wallet.ApproveJoinRequestRequest\x1a\x16.google.protobuf.Empty\"\x00\x12O\n" +
	"\x11RejectJoinRequest\x12 .wallet.RejectJoinRequestRequest\x1a\x16.google.protobuf.Empty\"\x00\x12f\n" +
	"\x15GetWalletJoinRequests\x12$.wallet.GetWalletJoinRequestsRequest\x1a%.wallet.GetWalletJoinRequestsResponse\"\x00\x12_\n" +
	"\x19RefundWalletMemberBalance\x12(.wallet.RefundWalletMemberBalanceRequest\x1a\x16.google.protobuf.Empty\"\x00\x12]\n" +
	"\x12GetWalletsByUserId\x12!.wallet.GetWalletsByUserIdRequest\x1a\".wallet.GetWalletsByUserIdResponse\"\x00BIZGgithub.com/raihan-faza/scriptsea-ept/backend/services/wallet_service/pbb\x06proto3"

var (
	file_wallet_proto_rawDescOnce sync.Once
	file_wallet_proto_rawDescData []byte
)

func file_wallet_proto_rawDescGZIP() []byte {
	file_wallet_proto_rawDescOnce.Do(func() {
		file_wallet_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_wallet_proto_rawDesc), len(file_wallet_proto_rawDesc)))
	})
	return file_wallet_proto_rawDescData
}

var file_wallet_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_wallet_proto_msgTypes = make([]protoimpl.MessageInfo, 35)
var file_wallet_proto_goTypes = []any{
	(JoinRequestStatus)(0),                     // 0: wallet.JoinRequestStatus
	(*GetWalletsByUserIdRequest)(nil),          // 1: wallet.GetWalletsByUserIdRequest
	(*GetWalletsByUserIdResponse)(nil),         // 2: wallet.GetWalletsByUserIdResponse
	(*RefundWalletMemberBalanceRequest)(nil),   // 3: wallet.RefundWalletMemberBalanceRequest
	(*ApproveJoinRequestRequest)(nil),          // 4: wallet.ApproveJoinRequestRequest
	(*RejectJoinRequestRequest)(nil),           // 5: wallet.RejectJoinRequestRequest
	(*RequestJoinWalletRequest)(nil),           // 6: wallet.RequestJoinWalletRequest
	(*WalletJoinRequest)(nil),                  // 7: wallet.WalletJoinRequest
	(*GetWalletJoinRequestsRequest)(nil),       // 8: wallet.GetWalletJoinRequestsRequest
	(*GetWalletJoinRequestsResponse)(nil),      // 9: wallet.GetWalletJoinRequestsResponse
	(*WalletInvitation)(nil),                   // 10: wallet.WalletInvitation
	(*GetWalletInvitationRequest)(nil),         // 11: wallet.GetWalletInvitationRequest
	(*GetWalletInvitationResponse)(nil),        // 12: wallet.GetWalletInvitationResponse
	(*RegenerateWalletInvitationRequest)(nil),  // 13: wallet.RegenerateWalletInvitationRequest
	(*RegenerateWalletInvitationResponse)(nil), // 14: wallet.RegenerateWalletInvitationResponse
	(*RequestJoinWalletResponse)(nil),          // 15: wallet.RequestJoinWalletResponse
	(*Wallet)(nil),                             // 16: wallet.Wallet
	(*Permission)(nil),                         // 17: wallet.Permission
	(*WalletMember)(nil),                       // 18: wallet.WalletMember
	(*DeleteWalletRequest)(nil),                // 19: wallet.DeleteWalletRequest
	(*GetWalletRequest)(nil),                   // 20: wallet.GetWalletRequest
	(*AllocateBalanceRequest)(nil),             // 21: wallet.AllocateBalanceRequest
	(*CreateWalletRequest)(nil),                // 22: wallet.CreateWalletRequest
	(*UpdateWalletRequest)(nil),                // 23: wallet.UpdateWalletRequest
	(*ValidateAndDeductBalanceRequest)(nil),    // 24: wallet.ValidateAndDeductBalanceRequest
	(*GetWalletMembersRequest)(nil),            // 25: wallet.GetWalletMembersRequest
	(*DeleteWalletMemberRequest)(nil),          // 26: wallet.DeleteWalletMemberRequest
	(*AdjustBalanceRequest)(nil),               // 27: wallet.AdjustBalanceRequest
	(*AllocateBalanceResponse)(nil),            // 28: wallet.AllocateBalanceResponse
	(*GetWalletResponse)(nil),                  // 29: wallet.GetWalletResponse
	(*UpdateWalletResponse)(nil),               // 30: wallet.UpdateWalletResponse
	(*CreateWalletResponse)(nil),               // 31: wallet.CreateWalletResponse
	(*ValidateAndDeductBalanceResponse)(nil),   // 32: wallet.ValidateAndDeductBalanceResponse
	(*GetWalletMembersResponse)(nil),           // 33: wallet.GetWalletMembersResponse
	(*DeleteWalletMemberResponse)(nil),         // 34: wallet.DeleteWalletMemberResponse
	(*AdjustBalanceResponse)(nil),              // 35: wallet.AdjustBalanceResponse
	(*timestamppb.Timestamp)(nil),              // 36: google.protobuf.Timestamp
	(*fieldmaskpb.FieldMask)(nil),              // 37: google.protobuf.FieldMask
	(*emptypb.Empty)(nil),                      // 38: google.protobuf.Empty
}
var file_wallet_proto_depIdxs = []int32{
	16, // 0: wallet.GetWalletsByUserIdResponse.wallets:type_name -> wallet.Wallet
	17, // 1: wallet.ApproveJoinRequestRequest.permission:type_name -> wallet.Permission
	0,  // 2: wallet.WalletJoinRequest.status:type_name -> wallet.JoinRequestStatus
	36, // 3: wallet.WalletJoinRequest.created_at:type_name -> google.protobuf.Timestamp
	7,  // 4: wallet.GetWalletJoinRequestsResponse.wallet_join_requests:type_name -> wallet.WalletJoinRequest
	10, // 5: wallet.GetWalletInvitationResponse.wallet_invitation:type_name -> wallet.WalletInvitation
	10, // 6: wallet.RegenerateWalletInvitationResponse.wallet_invitation:type_name -> wallet.WalletInvitation
	17, // 7: wallet.WalletMember.permission:type_name -> wallet.Permission
	37, // 8: wallet.UpdateWalletRequest.update_mask:type_name -> google.protobuf.FieldMask
	18, // 9: wallet.AllocateBalanceResponse.wallet_member:type_name -> wallet.WalletMember
	16, // 10: wallet.GetWalletResponse.wallet:type_name -> wallet.Wallet
	18, // 11: wallet.GetWalletResponse.members:type_name -> wallet.WalletMember
	16, // 12: wallet.UpdateWalletResponse.wallet:type_name -> wallet.Wallet
	16, // 13: wallet.CreateWalletResponse.wallet:type_name -> wallet.Wallet
	18, // 14: wallet.GetWalletMembersResponse.wallet_members:type_name -> wallet.WalletMember
	18, // 15: wallet.DeleteWalletMemberResponse.wallet_members:type_name -> wallet.WalletMember
	16, // 16: wallet.AdjustBalanceResponse.wallet:type_name -> wallet.Wallet
	22, // 17: wallet.WalletService.CreateWallet:input_type -> wallet.CreateWalletRequest
	23, // 18: wallet.WalletService.UpdateWallet:input_type -> wallet.UpdateWalletRequest
	19, // 19: wallet.WalletService.DeleteWallet:input_type -> wallet.DeleteWalletRequest
	20, // 20: wallet.WalletService.GetWallet:input_type -> wallet.GetWalletRequest
	24, // 21: wallet.WalletService.ValidateAndDeductBalance:input_type -> wallet.ValidateAndDeductBalanceRequest
	25, // 22: wallet.WalletService.GetWalletMembers:input_type -> wallet.GetWalletMembersRequest
	26, // 23: wallet.WalletService.DeleteWalletMember:input_type -> wallet.DeleteWalletMemberRequest
	21, // 24: wallet.WalletService.AllocateBalance:input_type -> wallet.AllocateBalanceRequest
	27, // 25: wallet.WalletService.AdjustBalance:input_type -> wallet.AdjustBalanceRequest
	11, // 26: wallet.WalletService.GetWalletInvitation:input_type -> wallet.GetWalletInvitationRequest
	13, // 27: wallet.WalletService.RegenerateWalletInvitation:input_type -> wallet.RegenerateWalletInvitationRequest
	6,  // 28: wallet.WalletService.RequestJoinWallet:input_type -> wallet.RequestJoinWalletRequest
	4,  // 29: wallet.WalletService.ApproveJoinRequest:input_type -> wallet.ApproveJoinRequestRequest
	5,  // 30: wallet.WalletService.RejectJoinRequest:input_type -> wallet.RejectJoinRequestRequest
	8,  // 31: wallet.WalletService.GetWalletJoinRequests:input_type -> wallet.GetWalletJoinRequestsRequest
	3,  // 32: wallet.WalletService.RefundWalletMemberBalance:input_type -> wallet.RefundWalletMemberBalanceRequest
	1,  // 33: wallet.WalletService.GetWalletsByUserId:input_type -> wallet.GetWalletsByUserIdRequest
	31, // 34: wallet.WalletService.CreateWallet:output_type -> wallet.CreateWalletResponse
	30, // 35: wallet.WalletService.UpdateWallet:output_type -> wallet.UpdateWalletResponse
	38, // 36: wallet.WalletService.DeleteWallet:output_type -> google.protobuf.Empty
	29, // 37: wallet.WalletService.GetWallet:output_type -> wallet.GetWalletResponse
	38, // 38: wallet.WalletService.ValidateAndDeductBalance:output_type -> google.protobuf.Empty
	33, // 39: wallet.WalletService.GetWalletMembers:output_type -> wallet.GetWalletMembersResponse
	38, // 40: wallet.WalletService.DeleteWalletMember:output_type -> google.protobuf.Empty
	38, // 41: wallet.WalletService.AllocateBalance:output_type -> google.protobuf.Empty
	35, // 42: wallet.WalletService.AdjustBalance:output_type -> wallet.AdjustBalanceResponse
	12, // 43: wallet.WalletService.GetWalletInvitation:output_type -> wallet.GetWalletInvitationResponse
	14, // 44: wallet.WalletService.RegenerateWalletInvitation:output_type -> wallet.RegenerateWalletInvitationResponse
	15, // 45: wallet.WalletService.RequestJoinWallet:output_type -> wallet.RequestJoinWalletResponse
	38, // 46: wallet.WalletService.ApproveJoinRequest:output_type -> google.protobuf.Empty
	38, // 47: wallet.WalletService.RejectJoinRequest:output_type -> google.protobuf.Empty
	9,  // 48: wallet.WalletService.GetWalletJoinRequests:output_type -> wallet.GetWalletJoinRequestsResponse
	38, // 49: wallet.WalletService.RefundWalletMemberBalance:output_type -> google.protobuf.Empty
	2,  // 50: wallet.WalletService.GetWalletsByUserId:output_type -> wallet.GetWalletsByUserIdResponse
	34, // [34:51] is the sub-list for method output_type
	17, // [17:34] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_wallet_proto_init() }
func file_wallet_proto_init() {
	if File_wallet_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wallet_proto_rawDesc), len(file_wallet_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   35,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_wallet_proto_goTypes,
		DependencyIndexes: file_wallet_proto_depIdxs,
		EnumInfos:         file_wallet_proto_enumTypes,
		MessageInfos:      file_wallet_proto_msgTypes,
	}.Build()
	File_wallet_proto = out.File
	file_wallet_proto_goTypes = nil
	file_wallet_proto_depIdxs = nil
}
