// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.19.6
// source: wallet.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WalletService_CreateWallet_FullMethodName                = "/wallet.WalletService/CreateWallet"
	WalletService_UpdateWallet_FullMethodName                = "/wallet.WalletService/UpdateWallet"
	WalletService_DeleteWallet_FullMethodName                = "/wallet.WalletService/DeleteWallet"
	WalletService_GetWallet_FullMethodName                   = "/wallet.WalletService/GetWallet"
	WalletService_ValidateAndDeductBalance_FullMethodName    = "/wallet.WalletService/ValidateAndDeductBalance"
	WalletService_GetWalletMembers_FullMethodName            = "/wallet.WalletService/GetWalletMembers"
	WalletService_DeleteWalletMember_FullMethodName          = "/wallet.WalletService/DeleteWalletMember"
	WalletService_AllocateBalance_FullMethodName             = "/wallet.WalletService/AllocateBalance"
	WalletService_AdjustBalance_FullMethodName               = "/wallet.WalletService/AdjustBalance"
	WalletService_GetWalletInvitation_FullMethodName         = "/wallet.WalletService/GetWalletInvitation"
	WalletService_RegenerateWalletInvitation_FullMethodName  = "/wallet.WalletService/RegenerateWalletInvitation"
	WalletService_RequestJoinWallet_FullMethodName           = "/wallet.WalletService/RequestJoinWallet"
	WalletService_ApproveJoinRequest_FullMethodName          = "/wallet.WalletService/ApproveJoinRequest"
	WalletService_RejectJoinRequest_FullMethodName           = "/wallet.WalletService/RejectJoinRequest"
	WalletService_GetWalletJoinRequests_FullMethodName       = "/wallet.WalletService/GetWalletJoinRequests"
	WalletService_RefundWalletMemberBalance_FullMethodName   = "/wallet.WalletService/RefundWalletMemberBalance"
	WalletService_GetWalletsByUserId_FullMethodName          = "/wallet.WalletService/GetWalletsByUserId"
	WalletService_GetWalletPendingJoinRequest_FullMethodName = "/wallet.WalletService/GetWalletPendingJoinRequest"
)

// WalletServiceClient is the client API for WalletService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WalletServiceClient interface {
	CreateWallet(ctx context.Context, in *CreateWalletRequest, opts ...grpc.CallOption) (*CreateWalletResponse, error)
	UpdateWallet(ctx context.Context, in *UpdateWalletRequest, opts ...grpc.CallOption) (*UpdateWalletResponse, error)
	DeleteWallet(ctx context.Context, in *DeleteWalletRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetWallet(ctx context.Context, in *GetWalletRequest, opts ...grpc.CallOption) (*GetWalletResponse, error)
	ValidateAndDeductBalance(ctx context.Context, in *ValidateAndDeductBalanceRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetWalletMembers(ctx context.Context, in *GetWalletMembersRequest, opts ...grpc.CallOption) (*GetWalletMembersResponse, error)
	DeleteWalletMember(ctx context.Context, in *DeleteWalletMemberRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	AllocateBalance(ctx context.Context, in *AllocateBalanceRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	AdjustBalance(ctx context.Context, in *AdjustBalanceRequest, opts ...grpc.CallOption) (*AdjustBalanceResponse, error)
	GetWalletInvitation(ctx context.Context, in *GetWalletInvitationRequest, opts ...grpc.CallOption) (*GetWalletInvitationResponse, error)
	RegenerateWalletInvitation(ctx context.Context, in *RegenerateWalletInvitationRequest, opts ...grpc.CallOption) (*RegenerateWalletInvitationResponse, error)
	RequestJoinWallet(ctx context.Context, in *RequestJoinWalletRequest, opts ...grpc.CallOption) (*RequestJoinWalletResponse, error)
	ApproveJoinRequest(ctx context.Context, in *ApproveJoinRequestRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	RejectJoinRequest(ctx context.Context, in *RejectJoinRequestRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetWalletJoinRequests(ctx context.Context, in *GetWalletJoinRequestsRequest, opts ...grpc.CallOption) (*GetWalletJoinRequestsResponse, error)
	RefundWalletMemberBalance(ctx context.Context, in *RefundWalletMemberBalanceRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetWalletsByUserId(ctx context.Context, in *GetWalletsByUserIdRequest, opts ...grpc.CallOption) (*GetWalletsByUserIdResponse, error)
	GetWalletPendingJoinRequest(ctx context.Context, in *GetWalletPendingJoinRequestRequest, opts ...grpc.CallOption) (*GetWalletPendingJoinRequestResponse, error)
}

type walletServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWalletServiceClient(cc grpc.ClientConnInterface) WalletServiceClient {
	return &walletServiceClient{cc}
}

func (c *walletServiceClient) CreateWallet(ctx context.Context, in *CreateWalletRequest, opts ...grpc.CallOption) (*CreateWalletResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateWalletResponse)
	err := c.cc.Invoke(ctx, WalletService_CreateWallet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) UpdateWallet(ctx context.Context, in *UpdateWalletRequest, opts ...grpc.CallOption) (*UpdateWalletResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateWalletResponse)
	err := c.cc.Invoke(ctx, WalletService_UpdateWallet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) DeleteWallet(ctx context.Context, in *DeleteWalletRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, WalletService_DeleteWallet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) GetWallet(ctx context.Context, in *GetWalletRequest, opts ...grpc.CallOption) (*GetWalletResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetWalletResponse)
	err := c.cc.Invoke(ctx, WalletService_GetWallet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) ValidateAndDeductBalance(ctx context.Context, in *ValidateAndDeductBalanceRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, WalletService_ValidateAndDeductBalance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) GetWalletMembers(ctx context.Context, in *GetWalletMembersRequest, opts ...grpc.CallOption) (*GetWalletMembersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetWalletMembersResponse)
	err := c.cc.Invoke(ctx, WalletService_GetWalletMembers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) DeleteWalletMember(ctx context.Context, in *DeleteWalletMemberRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, WalletService_DeleteWalletMember_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) AllocateBalance(ctx context.Context, in *AllocateBalanceRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, WalletService_AllocateBalance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) AdjustBalance(ctx context.Context, in *AdjustBalanceRequest, opts ...grpc.CallOption) (*AdjustBalanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdjustBalanceResponse)
	err := c.cc.Invoke(ctx, WalletService_AdjustBalance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) GetWalletInvitation(ctx context.Context, in *GetWalletInvitationRequest, opts ...grpc.CallOption) (*GetWalletInvitationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetWalletInvitationResponse)
	err := c.cc.Invoke(ctx, WalletService_GetWalletInvitation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) RegenerateWalletInvitation(ctx context.Context, in *RegenerateWalletInvitationRequest, opts ...grpc.CallOption) (*RegenerateWalletInvitationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegenerateWalletInvitationResponse)
	err := c.cc.Invoke(ctx, WalletService_RegenerateWalletInvitation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) RequestJoinWallet(ctx context.Context, in *RequestJoinWalletRequest, opts ...grpc.CallOption) (*RequestJoinWalletResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RequestJoinWalletResponse)
	err := c.cc.Invoke(ctx, WalletService_RequestJoinWallet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) ApproveJoinRequest(ctx context.Context, in *ApproveJoinRequestRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, WalletService_ApproveJoinRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) RejectJoinRequest(ctx context.Context, in *RejectJoinRequestRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, WalletService_RejectJoinRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) GetWalletJoinRequests(ctx context.Context, in *GetWalletJoinRequestsRequest, opts ...grpc.CallOption) (*GetWalletJoinRequestsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetWalletJoinRequestsResponse)
	err := c.cc.Invoke(ctx, WalletService_GetWalletJoinRequests_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) RefundWalletMemberBalance(ctx context.Context, in *RefundWalletMemberBalanceRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, WalletService_RefundWalletMemberBalance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) GetWalletsByUserId(ctx context.Context, in *GetWalletsByUserIdRequest, opts ...grpc.CallOption) (*GetWalletsByUserIdResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetWalletsByUserIdResponse)
	err := c.cc.Invoke(ctx, WalletService_GetWalletsByUserId_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) GetWalletPendingJoinRequest(ctx context.Context, in *GetWalletPendingJoinRequestRequest, opts ...grpc.CallOption) (*GetWalletPendingJoinRequestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetWalletPendingJoinRequestResponse)
	err := c.cc.Invoke(ctx, WalletService_GetWalletPendingJoinRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WalletServiceServer is the server API for WalletService service.
// All implementations must embed UnimplementedWalletServiceServer
// for forward compatibility.
type WalletServiceServer interface {
	CreateWallet(context.Context, *CreateWalletRequest) (*CreateWalletResponse, error)
	UpdateWallet(context.Context, *UpdateWalletRequest) (*UpdateWalletResponse, error)
	DeleteWallet(context.Context, *DeleteWalletRequest) (*emptypb.Empty, error)
	GetWallet(context.Context, *GetWalletRequest) (*GetWalletResponse, error)
	ValidateAndDeductBalance(context.Context, *ValidateAndDeductBalanceRequest) (*emptypb.Empty, error)
	GetWalletMembers(context.Context, *GetWalletMembersRequest) (*GetWalletMembersResponse, error)
	DeleteWalletMember(context.Context, *DeleteWalletMemberRequest) (*emptypb.Empty, error)
	AllocateBalance(context.Context, *AllocateBalanceRequest) (*emptypb.Empty, error)
	AdjustBalance(context.Context, *AdjustBalanceRequest) (*AdjustBalanceResponse, error)
	GetWalletInvitation(context.Context, *GetWalletInvitationRequest) (*GetWalletInvitationResponse, error)
	RegenerateWalletInvitation(context.Context, *RegenerateWalletInvitationRequest) (*RegenerateWalletInvitationResponse, error)
	RequestJoinWallet(context.Context, *RequestJoinWalletRequest) (*RequestJoinWalletResponse, error)
	ApproveJoinRequest(context.Context, *ApproveJoinRequestRequest) (*emptypb.Empty, error)
	RejectJoinRequest(context.Context, *RejectJoinRequestRequest) (*emptypb.Empty, error)
	GetWalletJoinRequests(context.Context, *GetWalletJoinRequestsRequest) (*GetWalletJoinRequestsResponse, error)
	RefundWalletMemberBalance(context.Context, *RefundWalletMemberBalanceRequest) (*emptypb.Empty, error)
	GetWalletsByUserId(context.Context, *GetWalletsByUserIdRequest) (*GetWalletsByUserIdResponse, error)
	GetWalletPendingJoinRequest(context.Context, *GetWalletPendingJoinRequestRequest) (*GetWalletPendingJoinRequestResponse, error)
	mustEmbedUnimplementedWalletServiceServer()
}

// UnimplementedWalletServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWalletServiceServer struct{}

func (UnimplementedWalletServiceServer) CreateWallet(context.Context, *CreateWalletRequest) (*CreateWalletResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateWallet not implemented")
}
func (UnimplementedWalletServiceServer) UpdateWallet(context.Context, *UpdateWalletRequest) (*UpdateWalletResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateWallet not implemented")
}
func (UnimplementedWalletServiceServer) DeleteWallet(context.Context, *DeleteWalletRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteWallet not implemented")
}
func (UnimplementedWalletServiceServer) GetWallet(context.Context, *GetWalletRequest) (*GetWalletResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetWallet not implemented")
}
func (UnimplementedWalletServiceServer) ValidateAndDeductBalance(context.Context, *ValidateAndDeductBalanceRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method ValidateAndDeductBalance not implemented")
}
func (UnimplementedWalletServiceServer) GetWalletMembers(context.Context, *GetWalletMembersRequest) (*GetWalletMembersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetWalletMembers not implemented")
}
func (UnimplementedWalletServiceServer) DeleteWalletMember(context.Context, *DeleteWalletMemberRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteWalletMember not implemented")
}
func (UnimplementedWalletServiceServer) AllocateBalance(context.Context, *AllocateBalanceRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method AllocateBalance not implemented")
}
func (UnimplementedWalletServiceServer) AdjustBalance(context.Context, *AdjustBalanceRequest) (*AdjustBalanceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AdjustBalance not implemented")
}
func (UnimplementedWalletServiceServer) GetWalletInvitation(context.Context, *GetWalletInvitationRequest) (*GetWalletInvitationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetWalletInvitation not implemented")
}
func (UnimplementedWalletServiceServer) RegenerateWalletInvitation(context.Context, *RegenerateWalletInvitationRequest) (*RegenerateWalletInvitationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegenerateWalletInvitation not implemented")
}
func (UnimplementedWalletServiceServer) RequestJoinWallet(context.Context, *RequestJoinWalletRequest) (*RequestJoinWalletResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RequestJoinWallet not implemented")
}
func (UnimplementedWalletServiceServer) ApproveJoinRequest(context.Context, *ApproveJoinRequestRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method ApproveJoinRequest not implemented")
}
func (UnimplementedWalletServiceServer) RejectJoinRequest(context.Context, *RejectJoinRequestRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method RejectJoinRequest not implemented")
}
func (UnimplementedWalletServiceServer) GetWalletJoinRequests(context.Context, *GetWalletJoinRequestsRequest) (*GetWalletJoinRequestsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetWalletJoinRequests not implemented")
}
func (UnimplementedWalletServiceServer) RefundWalletMemberBalance(context.Context, *RefundWalletMemberBalanceRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method RefundWalletMemberBalance not implemented")
}
func (UnimplementedWalletServiceServer) GetWalletsByUserId(context.Context, *GetWalletsByUserIdRequest) (*GetWalletsByUserIdResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetWalletsByUserId not implemented")
}
func (UnimplementedWalletServiceServer) GetWalletPendingJoinRequest(context.Context, *GetWalletPendingJoinRequestRequest) (*GetWalletPendingJoinRequestResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetWalletPendingJoinRequest not implemented")
}
func (UnimplementedWalletServiceServer) mustEmbedUnimplementedWalletServiceServer() {}
func (UnimplementedWalletServiceServer) testEmbeddedByValue()                       {}

// UnsafeWalletServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WalletServiceServer will
// result in compilation errors.
type UnsafeWalletServiceServer interface {
	mustEmbedUnimplementedWalletServiceServer()
}

func RegisterWalletServiceServer(s grpc.ServiceRegistrar, srv WalletServiceServer) {
	// If the following call panics, it indicates UnimplementedWalletServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WalletService_ServiceDesc, srv)
}

func _WalletService_CreateWallet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateWalletRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).CreateWallet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalletService_CreateWallet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).CreateWallet(ctx, req.(*CreateWalletRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_UpdateWallet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateWalletRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).UpdateWallet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalletService_UpdateWallet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).UpdateWallet(ctx, req.(*UpdateWalletRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_DeleteWallet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteWalletRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).DeleteWallet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalletService_DeleteWallet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).DeleteWallet(ctx, req.(*DeleteWalletRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_GetWallet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWalletRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).GetWallet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalletService_GetWallet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).GetWallet(ctx, req.(*GetWalletRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_ValidateAndDeductBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateAndDeductBalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).ValidateAndDeductBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalletService_ValidateAndDeductBalance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).ValidateAndDeductBalance(ctx, req.(*ValidateAndDeductBalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_GetWalletMembers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWalletMembersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).GetWalletMembers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalletService_GetWalletMembers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).GetWalletMembers(ctx, req.(*GetWalletMembersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_DeleteWalletMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteWalletMemberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).DeleteWalletMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalletService_DeleteWalletMember_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).DeleteWalletMember(ctx, req.(*DeleteWalletMemberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_AllocateBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AllocateBalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).AllocateBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalletService_AllocateBalance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).AllocateBalance(ctx, req.(*AllocateBalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_AdjustBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdjustBalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).AdjustBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalletService_AdjustBalance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).AdjustBalance(ctx, req.(*AdjustBalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_GetWalletInvitation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWalletInvitationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).GetWalletInvitation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalletService_GetWalletInvitation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).GetWalletInvitation(ctx, req.(*GetWalletInvitationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_RegenerateWalletInvitation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegenerateWalletInvitationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).RegenerateWalletInvitation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalletService_RegenerateWalletInvitation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).RegenerateWalletInvitation(ctx, req.(*RegenerateWalletInvitationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_RequestJoinWallet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestJoinWalletRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).RequestJoinWallet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalletService_RequestJoinWallet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).RequestJoinWallet(ctx, req.(*RequestJoinWalletRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_ApproveJoinRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApproveJoinRequestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).ApproveJoinRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalletService_ApproveJoinRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).ApproveJoinRequest(ctx, req.(*ApproveJoinRequestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_RejectJoinRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RejectJoinRequestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).RejectJoinRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalletService_RejectJoinRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).RejectJoinRequest(ctx, req.(*RejectJoinRequestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_GetWalletJoinRequests_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWalletJoinRequestsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).GetWalletJoinRequests(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalletService_GetWalletJoinRequests_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).GetWalletJoinRequests(ctx, req.(*GetWalletJoinRequestsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_RefundWalletMemberBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefundWalletMemberBalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).RefundWalletMemberBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalletService_RefundWalletMemberBalance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).RefundWalletMemberBalance(ctx, req.(*RefundWalletMemberBalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_GetWalletsByUserId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWalletsByUserIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).GetWalletsByUserId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalletService_GetWalletsByUserId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).GetWalletsByUserId(ctx, req.(*GetWalletsByUserIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_GetWalletPendingJoinRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWalletPendingJoinRequestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).GetWalletPendingJoinRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalletService_GetWalletPendingJoinRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).GetWalletPendingJoinRequest(ctx, req.(*GetWalletPendingJoinRequestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WalletService_ServiceDesc is the grpc.ServiceDesc for WalletService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WalletService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "wallet.WalletService",
	HandlerType: (*WalletServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateWallet",
			Handler:    _WalletService_CreateWallet_Handler,
		},
		{
			MethodName: "UpdateWallet",
			Handler:    _WalletService_UpdateWallet_Handler,
		},
		{
			MethodName: "DeleteWallet",
			Handler:    _WalletService_DeleteWallet_Handler,
		},
		{
			MethodName: "GetWallet",
			Handler:    _WalletService_GetWallet_Handler,
		},
		{
			MethodName: "ValidateAndDeductBalance",
			Handler:    _WalletService_ValidateAndDeductBalance_Handler,
		},
		{
			MethodName: "GetWalletMembers",
			Handler:    _WalletService_GetWalletMembers_Handler,
		},
		{
			MethodName: "DeleteWalletMember",
			Handler:    _WalletService_DeleteWalletMember_Handler,
		},
		{
			MethodName: "AllocateBalance",
			Handler:    _WalletService_AllocateBalance_Handler,
		},
		{
			MethodName: "AdjustBalance",
			Handler:    _WalletService_AdjustBalance_Handler,
		},
		{
			MethodName: "GetWalletInvitation",
			Handler:    _WalletService_GetWalletInvitation_Handler,
		},
		{
			MethodName: "RegenerateWalletInvitation",
			Handler:    _WalletService_RegenerateWalletInvitation_Handler,
		},
		{
			MethodName: "RequestJoinWallet",
			Handler:    _WalletService_RequestJoinWallet_Handler,
		},
		{
			MethodName: "ApproveJoinRequest",
			Handler:    _WalletService_ApproveJoinRequest_Handler,
		},
		{
			MethodName: "RejectJoinRequest",
			Handler:    _WalletService_RejectJoinRequest_Handler,
		},
		{
			MethodName: "GetWalletJoinRequests",
			Handler:    _WalletService_GetWalletJoinRequests_Handler,
		},
		{
			MethodName: "RefundWalletMemberBalance",
			Handler:    _WalletService_RefundWalletMemberBalance_Handler,
		},
		{
			MethodName: "GetWalletsByUserId",
			Handler:    _WalletService_GetWalletsByUserId_Handler,
		},
		{
			MethodName: "GetWalletPendingJoinRequest",
			Handler:    _WalletService_GetWalletPendingJoinRequest_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "wallet.proto",
}
