// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.19.6
// source: expense.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExpenseCategory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExpenseCategory) Reset() {
	*x = ExpenseCategory{}
	mi := &file_expense_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExpenseCategory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpenseCategory) ProtoMessage() {}

func (x *ExpenseCategory) ProtoReflect() protoreflect.Message {
	mi := &file_expense_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpenseCategory.ProtoReflect.Descriptor instead.
func (*ExpenseCategory) Descriptor() ([]byte, []int) {
	return file_expense_proto_rawDescGZIP(), []int{0}
}

func (x *ExpenseCategory) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ExpenseCategory) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ExpenseCategory) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ExpenseCategory) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ExpenseCategory) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ExpenseCategory) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type ExpenseItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemName      string                 `protobuf:"bytes,1,opt,name=item_name,json=itemName,proto3" json:"item_name,omitempty"`
	ItemQuantity  int64                  `protobuf:"varint,2,opt,name=item_quantity,json=itemQuantity,proto3" json:"item_quantity,omitempty"`
	TotalPrice    int64                  `protobuf:"varint,3,opt,name=total_price,json=totalPrice,proto3" json:"total_price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExpenseItem) Reset() {
	*x = ExpenseItem{}
	mi := &file_expense_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExpenseItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpenseItem) ProtoMessage() {}

func (x *ExpenseItem) ProtoReflect() protoreflect.Message {
	mi := &file_expense_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpenseItem.ProtoReflect.Descriptor instead.
func (*ExpenseItem) Descriptor() ([]byte, []int) {
	return file_expense_proto_rawDescGZIP(), []int{1}
}

func (x *ExpenseItem) GetItemName() string {
	if x != nil {
		return x.ItemName
	}
	return ""
}

func (x *ExpenseItem) GetItemQuantity() int64 {
	if x != nil {
		return x.ItemQuantity
	}
	return 0
}

func (x *ExpenseItem) GetTotalPrice() int64 {
	if x != nil {
		return x.TotalPrice
	}
	return 0
}

type Expense struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId         string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	WalletId       string                 `protobuf:"bytes,3,opt,name=wallet_id,json=walletId,proto3" json:"wallet_id,omitempty"`
	CategoryId     uint64                 `protobuf:"varint,4,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	ExpenseName    string                 `protobuf:"bytes,5,opt,name=expense_name,json=expenseName,proto3" json:"expense_name,omitempty"`
	ExpenseDetails string                 `protobuf:"bytes,6,opt,name=expense_details,json=expenseDetails,proto3" json:"expense_details,omitempty"`
	ExpenseItems   []*ExpenseItem         `protobuf:"bytes,7,rep,name=expense_items,json=expenseItems,proto3" json:"expense_items,omitempty"`
	Amount         int64                  `protobuf:"varint,8,opt,name=amount,proto3" json:"amount,omitempty"`
	Status         string                 `protobuf:"bytes,9,opt,name=status,proto3" json:"status,omitempty"`
	Date           string                 `protobuf:"bytes,10,opt,name=date,proto3" json:"date,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,11,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Expense) Reset() {
	*x = Expense{}
	mi := &file_expense_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Expense) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Expense) ProtoMessage() {}

func (x *Expense) ProtoReflect() protoreflect.Message {
	mi := &file_expense_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Expense.ProtoReflect.Descriptor instead.
func (*Expense) Descriptor() ([]byte, []int) {
	return file_expense_proto_rawDescGZIP(), []int{2}
}

func (x *Expense) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Expense) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Expense) GetWalletId() string {
	if x != nil {
		return x.WalletId
	}
	return ""
}

func (x *Expense) GetCategoryId() uint64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *Expense) GetExpenseName() string {
	if x != nil {
		return x.ExpenseName
	}
	return ""
}

func (x *Expense) GetExpenseDetails() string {
	if x != nil {
		return x.ExpenseDetails
	}
	return ""
}

func (x *Expense) GetExpenseItems() []*ExpenseItem {
	if x != nil {
		return x.ExpenseItems
	}
	return nil
}

func (x *Expense) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Expense) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Expense) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *Expense) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *Expense) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Expense) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CreateExpenseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Expense       *Expense               `protobuf:"bytes,1,opt,name=expense,proto3" json:"expense,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateExpenseRequest) Reset() {
	*x = CreateExpenseRequest{}
	mi := &file_expense_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateExpenseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateExpenseRequest) ProtoMessage() {}

func (x *CreateExpenseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_expense_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateExpenseRequest.ProtoReflect.Descriptor instead.
func (*CreateExpenseRequest) Descriptor() ([]byte, []int) {
	return file_expense_proto_rawDescGZIP(), []int{3}
}

func (x *CreateExpenseRequest) GetExpense() *Expense {
	if x != nil {
		return x.Expense
	}
	return nil
}

type UpdateExpenseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Expense       *Expense               `protobuf:"bytes,1,opt,name=expense,proto3" json:"expense,omitempty"`
	UpdateMask    *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateExpenseRequest) Reset() {
	*x = UpdateExpenseRequest{}
	mi := &file_expense_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateExpenseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateExpenseRequest) ProtoMessage() {}

func (x *UpdateExpenseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_expense_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateExpenseRequest.ProtoReflect.Descriptor instead.
func (*UpdateExpenseRequest) Descriptor() ([]byte, []int) {
	return file_expense_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateExpenseRequest) GetExpense() *Expense {
	if x != nil {
		return x.Expense
	}
	return nil
}

func (x *UpdateExpenseRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

type DeleteExpenseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExpenseId     string                 `protobuf:"bytes,1,opt,name=expense_id,json=expenseId,proto3" json:"expense_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	WalletId      string                 `protobuf:"bytes,3,opt,name=wallet_id,json=walletId,proto3" json:"wallet_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteExpenseRequest) Reset() {
	*x = DeleteExpenseRequest{}
	mi := &file_expense_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteExpenseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteExpenseRequest) ProtoMessage() {}

func (x *DeleteExpenseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_expense_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteExpenseRequest.ProtoReflect.Descriptor instead.
func (*DeleteExpenseRequest) Descriptor() ([]byte, []int) {
	return file_expense_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteExpenseRequest) GetExpenseId() string {
	if x != nil {
		return x.ExpenseId
	}
	return ""
}

func (x *DeleteExpenseRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DeleteExpenseRequest) GetWalletId() string {
	if x != nil {
		return x.WalletId
	}
	return ""
}

type CreateExpenseCategoryRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ExpenseCategory *ExpenseCategory       `protobuf:"bytes,1,opt,name=expense_category,json=expenseCategory,proto3" json:"expense_category,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateExpenseCategoryRequest) Reset() {
	*x = CreateExpenseCategoryRequest{}
	mi := &file_expense_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateExpenseCategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateExpenseCategoryRequest) ProtoMessage() {}

func (x *CreateExpenseCategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_expense_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateExpenseCategoryRequest.ProtoReflect.Descriptor instead.
func (*CreateExpenseCategoryRequest) Descriptor() ([]byte, []int) {
	return file_expense_proto_rawDescGZIP(), []int{6}
}

func (x *CreateExpenseCategoryRequest) GetExpenseCategory() *ExpenseCategory {
	if x != nil {
		return x.ExpenseCategory
	}
	return nil
}

type UpdateExpenseCategoryRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ExpenseCategory *ExpenseCategory       `protobuf:"bytes,1,opt,name=expense_category,json=expenseCategory,proto3" json:"expense_category,omitempty"`
	UpdateMask      *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateExpenseCategoryRequest) Reset() {
	*x = UpdateExpenseCategoryRequest{}
	mi := &file_expense_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateExpenseCategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateExpenseCategoryRequest) ProtoMessage() {}

func (x *UpdateExpenseCategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_expense_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateExpenseCategoryRequest.ProtoReflect.Descriptor instead.
func (*UpdateExpenseCategoryRequest) Descriptor() ([]byte, []int) {
	return file_expense_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateExpenseCategoryRequest) GetExpenseCategory() *ExpenseCategory {
	if x != nil {
		return x.ExpenseCategory
	}
	return nil
}

func (x *UpdateExpenseCategoryRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

type DeleteExpenseCategoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteExpenseCategoryRequest) Reset() {
	*x = DeleteExpenseCategoryRequest{}
	mi := &file_expense_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteExpenseCategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteExpenseCategoryRequest) ProtoMessage() {}

func (x *DeleteExpenseCategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_expense_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteExpenseCategoryRequest.ProtoReflect.Descriptor instead.
func (*DeleteExpenseCategoryRequest) Descriptor() ([]byte, []int) {
	return file_expense_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteExpenseCategoryRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DeleteExpenseCategoryRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetAllExpensesByWalletIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WalletId      string                 `protobuf:"bytes,1,opt,name=wallet_id,json=walletId,proto3" json:"wallet_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllExpensesByWalletIdRequest) Reset() {
	*x = GetAllExpensesByWalletIdRequest{}
	mi := &file_expense_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllExpensesByWalletIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllExpensesByWalletIdRequest) ProtoMessage() {}

func (x *GetAllExpensesByWalletIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_expense_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllExpensesByWalletIdRequest.ProtoReflect.Descriptor instead.
func (*GetAllExpensesByWalletIdRequest) Descriptor() ([]byte, []int) {
	return file_expense_proto_rawDescGZIP(), []int{9}
}

func (x *GetAllExpensesByWalletIdRequest) GetWalletId() string {
	if x != nil {
		return x.WalletId
	}
	return ""
}

type GetAllExpensesByUserIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllExpensesByUserIdRequest) Reset() {
	*x = GetAllExpensesByUserIdRequest{}
	mi := &file_expense_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllExpensesByUserIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllExpensesByUserIdRequest) ProtoMessage() {}

func (x *GetAllExpensesByUserIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_expense_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllExpensesByUserIdRequest.ProtoReflect.Descriptor instead.
func (*GetAllExpensesByUserIdRequest) Descriptor() ([]byte, []int) {
	return file_expense_proto_rawDescGZIP(), []int{10}
}

func (x *GetAllExpensesByUserIdRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetAllExpensesCategoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllExpensesCategoryRequest) Reset() {
	*x = GetAllExpensesCategoryRequest{}
	mi := &file_expense_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllExpensesCategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllExpensesCategoryRequest) ProtoMessage() {}

func (x *GetAllExpensesCategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_expense_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllExpensesCategoryRequest.ProtoReflect.Descriptor instead.
func (*GetAllExpensesCategoryRequest) Descriptor() ([]byte, []int) {
	return file_expense_proto_rawDescGZIP(), []int{11}
}

func (x *GetAllExpensesCategoryRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetExpenseByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExpenseId     string                 `protobuf:"bytes,1,opt,name=expense_id,json=expenseId,proto3" json:"expense_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExpenseByIDRequest) Reset() {
	*x = GetExpenseByIDRequest{}
	mi := &file_expense_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExpenseByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExpenseByIDRequest) ProtoMessage() {}

func (x *GetExpenseByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_expense_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExpenseByIDRequest.ProtoReflect.Descriptor instead.
func (*GetExpenseByIDRequest) Descriptor() ([]byte, []int) {
	return file_expense_proto_rawDescGZIP(), []int{12}
}

func (x *GetExpenseByIDRequest) GetExpenseId() string {
	if x != nil {
		return x.ExpenseId
	}
	return ""
}

type GetExpenseByIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Expense       *Expense               `protobuf:"bytes,1,opt,name=expense,proto3" json:"expense,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExpenseByIDResponse) Reset() {
	*x = GetExpenseByIDResponse{}
	mi := &file_expense_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExpenseByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExpenseByIDResponse) ProtoMessage() {}

func (x *GetExpenseByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_expense_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExpenseByIDResponse.ProtoReflect.Descriptor instead.
func (*GetExpenseByIDResponse) Descriptor() ([]byte, []int) {
	return file_expense_proto_rawDescGZIP(), []int{13}
}

func (x *GetExpenseByIDResponse) GetExpense() *Expense {
	if x != nil {
		return x.Expense
	}
	return nil
}

type CreateExpenseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Expense       *Expense               `protobuf:"bytes,1,opt,name=expense,proto3" json:"expense,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateExpenseResponse) Reset() {
	*x = CreateExpenseResponse{}
	mi := &file_expense_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateExpenseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateExpenseResponse) ProtoMessage() {}

func (x *CreateExpenseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_expense_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateExpenseResponse.ProtoReflect.Descriptor instead.
func (*CreateExpenseResponse) Descriptor() ([]byte, []int) {
	return file_expense_proto_rawDescGZIP(), []int{14}
}

func (x *CreateExpenseResponse) GetExpense() *Expense {
	if x != nil {
		return x.Expense
	}
	return nil
}

type UpdateExpenseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Expense       *Expense               `protobuf:"bytes,1,opt,name=expense,proto3" json:"expense,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateExpenseResponse) Reset() {
	*x = UpdateExpenseResponse{}
	mi := &file_expense_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateExpenseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateExpenseResponse) ProtoMessage() {}

func (x *UpdateExpenseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_expense_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateExpenseResponse.ProtoReflect.Descriptor instead.
func (*UpdateExpenseResponse) Descriptor() ([]byte, []int) {
	return file_expense_proto_rawDescGZIP(), []int{15}
}

func (x *UpdateExpenseResponse) GetExpense() *Expense {
	if x != nil {
		return x.Expense
	}
	return nil
}

type CreateExpenseCategoryResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ExpenseCategory *ExpenseCategory       `protobuf:"bytes,1,opt,name=expense_category,json=expenseCategory,proto3" json:"expense_category,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateExpenseCategoryResponse) Reset() {
	*x = CreateExpenseCategoryResponse{}
	mi := &file_expense_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateExpenseCategoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateExpenseCategoryResponse) ProtoMessage() {}

func (x *CreateExpenseCategoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_expense_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateExpenseCategoryResponse.ProtoReflect.Descriptor instead.
func (*CreateExpenseCategoryResponse) Descriptor() ([]byte, []int) {
	return file_expense_proto_rawDescGZIP(), []int{16}
}

func (x *CreateExpenseCategoryResponse) GetExpenseCategory() *ExpenseCategory {
	if x != nil {
		return x.ExpenseCategory
	}
	return nil
}

type UpdateExpenseCategoryResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ExpenseCategory *ExpenseCategory       `protobuf:"bytes,1,opt,name=expense_category,json=expenseCategory,proto3" json:"expense_category,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateExpenseCategoryResponse) Reset() {
	*x = UpdateExpenseCategoryResponse{}
	mi := &file_expense_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateExpenseCategoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateExpenseCategoryResponse) ProtoMessage() {}

func (x *UpdateExpenseCategoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_expense_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateExpenseCategoryResponse.ProtoReflect.Descriptor instead.
func (*UpdateExpenseCategoryResponse) Descriptor() ([]byte, []int) {
	return file_expense_proto_rawDescGZIP(), []int{17}
}

func (x *UpdateExpenseCategoryResponse) GetExpenseCategory() *ExpenseCategory {
	if x != nil {
		return x.ExpenseCategory
	}
	return nil
}

type GetAllExpensesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Expenses      []*Expense             `protobuf:"bytes,1,rep,name=expenses,proto3" json:"expenses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllExpensesResponse) Reset() {
	*x = GetAllExpensesResponse{}
	mi := &file_expense_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllExpensesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllExpensesResponse) ProtoMessage() {}

func (x *GetAllExpensesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_expense_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllExpensesResponse.ProtoReflect.Descriptor instead.
func (*GetAllExpensesResponse) Descriptor() ([]byte, []int) {
	return file_expense_proto_rawDescGZIP(), []int{18}
}

func (x *GetAllExpensesResponse) GetExpenses() []*Expense {
	if x != nil {
		return x.Expenses
	}
	return nil
}

type GetAllExpensesCategoryResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ExpenseCategories []*ExpenseCategory     `protobuf:"bytes,1,rep,name=expense_categories,json=expenseCategories,proto3" json:"expense_categories,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetAllExpensesCategoryResponse) Reset() {
	*x = GetAllExpensesCategoryResponse{}
	mi := &file_expense_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllExpensesCategoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllExpensesCategoryResponse) ProtoMessage() {}

func (x *GetAllExpensesCategoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_expense_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllExpensesCategoryResponse.ProtoReflect.Descriptor instead.
func (*GetAllExpensesCategoryResponse) Descriptor() ([]byte, []int) {
	return file_expense_proto_rawDescGZIP(), []int{19}
}

func (x *GetAllExpensesCategoryResponse) GetExpenseCategories() []*ExpenseCategory {
	if x != nil {
		return x.ExpenseCategories
	}
	return nil
}

var File_expense_proto protoreflect.FileDescriptor

const file_expense_proto_rawDesc = "" +
	"\n" +
	"\rexpense.proto\x12\aexpense\x1a google/protobuf/field_mask.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xe6\x01\n" +
	"\x0fExpenseCategory\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"p\n" +
	"\vExpenseItem\x12\x1b\n" +
	"\titem_name\x18\x01 \x01(\tR\bitemName\x12#\n" +
	"\ritem_quantity\x18\x02 \x01(\x03R\fitemQuantity\x12\x1f\n" +
	"\vtotal_price\x18\x03 \x01(\x03R\n" +
	"totalPrice\"\xda\x03\n" +
	"\aExpense\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1b\n" +
	"\twallet_id\x18\x03 \x01(\tR\bwalletId\x12\x1f\n" +
	"\vcategory_id\x18\x04 \x01(\x04R\n" +
	"categoryId\x12!\n" +
	"\fexpense_name\x18\x05 \x01(\tR\vexpenseName\x12'\n" +
	"\x0fexpense_details\x18\x06 \x01(\tR\x0eexpenseDetails\x129\n" +
	"\rexpense_items\x18\a \x03(\v2\x14.expense.ExpenseItemR\fexpenseItems\x12\x16\n" +
	"\x06amount\x18\b \x01(\x03R\x06amount\x12\x16\n" +
	"\x06status\x18\t \x01(\tR\x06status\x12\x12\n" +
	"\x04date\x18\n" +
	" \x01(\tR\x04date\x12'\n" +
	"\x0fidempotency_key\x18\v \x01(\tR\x0eidempotencyKey\x129\n" +
	"\n" +
	"created_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"B\n" +
	"\x14CreateExpenseRequest\x12*\n" +
	"\aexpense\x18\x01 \x01(\v2\x10.expense.ExpenseR\aexpense\"\x7f\n" +
	"\x14UpdateExpenseRequest\x12*\n" +
	"\aexpense\x18\x01 \x01(\v2\x10.expense.ExpenseR\aexpense\x12;\n" +
	"\vupdate_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskR\n" +
	"updateMask\"k\n" +
	"\x14DeleteExpenseRequest\x12\x1d\n" +
	"\n" +
	"expense_id\x18\x01 \x01(\tR\texpenseId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1b\n" +
	"\twallet_id\x18\x03 \x01(\tR\bwalletId\"c\n" +
	"\x1cCreateExpenseCategoryRequest\x12C\n" +
	"\x10expense_category\x18\x01 \x01(\v2\x18.expense.ExpenseCategoryR\x0fexpenseCategory\"\xa0\x01\n" +
	"\x1cUpdateExpenseCategoryRequest\x12C\n" +
	"\x10expense_category\x18\x01 \x01(\v2\x18.expense.ExpenseCategoryR\x0fexpenseCategory\x12;\n" +
	"\vupdate_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskR\n" +
	"updateMask\"G\n" +
	"\x1cDeleteExpenseCategoryRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\">\n" +
	"\x1fGetAllExpensesByWalletIdRequest\x12\x1b\n" +
	"\twallet_id\x18\x01 \x01(\tR\bwalletId\"8\n" +
	"\x1dGetAllExpensesByUserIdRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"8\n" +
	"\x1dGetAllExpensesCategoryRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"6\n" +
	"\x15GetExpenseByIDRequest\x12\x1d\n" +
	"\n" +
	"expense_id\x18\x01 \x01(\tR\texpenseId\"D\n" +
	"\x16GetExpenseByIDResponse\x12*\n" +
	"\aexpense\x18\x01 \x01(\v2\x10.expense.ExpenseR\aexpense\"C\n" +
	"\x15CreateExpenseResponse\x12*\n" +
	"\aexpense\x18\x01 \x01(\v2\x10.expense.ExpenseR\aexpense\"C\n" +
	"\x15UpdateExpenseResponse\x12*\n" +
	"\aexpense\x18\x01 \x01(\v2\x10.expense.ExpenseR\aexpense\"d\n" +
	"\x1dCreateExpenseCategoryResponse\x12C\n" +
	"\x10expense_category\x18\x01 \x01(\v2\x18.expense.ExpenseCategoryR\x0fexpenseCategory\"d\n" +
	"\x1dUpdateExpenseCategoryResponse\x12C\n" +
	"\x10expense_category\x18\x01 \x01(\v2\x18.expense.ExpenseCategoryR\x0fexpenseCategory\"F\n" +
	"\x16GetAllExpensesResponse\x12,\n" +
	"\bexpenses\x18\x01 \x03(\v2\x10.expense.ExpenseR\bexpenses\"i\n" +
	"\x1eGetAllExpensesCategoryResponse\x12G\n" +
	"\x12expense_categories\x18\x01 \x03(\v2\x18.expense.ExpenseCategoryR\x11expenseCategories2\xbc\a\n" +
	"\x0eExpenseService\x12P\n" +
	"\rCreateExpense\x12\x1d.expense.CreateExpenseRequest\x1a\x1e.expense.CreateExpenseResponse\"\x00\x12P\n" +
	"\rUpdateExpense\x12\x1d.expense.UpdateExpenseRequest\x1a\x1e.expense.UpdateExpenseResponse\"\x00\x12H\n" +
	"\rDeleteExpense\x12\x1d.expense.DeleteExpenseRequest\x1a\x16.google.protobuf.Empty\"\x00\x12g\n" +
	"\x18GetAllExpensesByWalletId\x12(.expense.GetAllExpensesByWalletIdRequest\x1a\x1f.expense.GetAllExpensesResponse\"\x00\x12c\n" +
	"\x16GetAllExpensesByUserId\x12&.expense.GetAllExpensesByUserIdRequest\x1a\x1f.expense.GetAllExpensesResponse\"\x00\x12S\n" +
	"\x0eGetExpenseByID\x12\x1e.expense.GetExpenseByIDRequest\x1a\x1f.expense.GetExpenseByIDResponse\"\x00\x12h\n" +
	"\x15CreateExpenseCategory\x12%.expense.CreateExpenseCategoryRequest\x1a&.expense.CreateExpenseCategoryResponse\"\x00\x12h\n" +
	"\x15UpdateExpenseCategory\x12%.expense.UpdateExpenseCategoryRequest\x1a&.expense.UpdateExpenseCategoryResponse\"\x00\x12X\n" +
	"\x15DeleteExpenseCategory\x12%.expense.DeleteExpenseCategoryRequest\x1a\x16.google.protobuf.Empty\"\x00\x12k\n" +
	"\x16GetAllExpensesCategory\x12&.expense.GetAllExpensesCategoryRequest\x1a'.expense.GetAllExpensesCategoryResponse\"\x00BJZHgithub.com/raihan-faza/scriptsea-ept/backend/services/expense_service/pbb\x06proto3"

var (
	file_expense_proto_rawDescOnce sync.Once
	file_expense_proto_rawDescData []byte
)

func file_expense_proto_rawDescGZIP() []byte {
	file_expense_proto_rawDescOnce.Do(func() {
		file_expense_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_expense_proto_rawDesc), len(file_expense_proto_rawDesc)))
	})
	return file_expense_proto_rawDescData
}

var file_expense_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_expense_proto_goTypes = []any{
	(*ExpenseCategory)(nil),                 // 0: expense.ExpenseCategory
	(*ExpenseItem)(nil),                     // 1: expense.ExpenseItem
	(*Expense)(nil),                         // 2: expense.Expense
	(*CreateExpenseRequest)(nil),            // 3: expense.CreateExpenseRequest
	(*UpdateExpenseRequest)(nil),            // 4: expense.UpdateExpenseRequest
	(*DeleteExpenseRequest)(nil),            // 5: expense.DeleteExpenseRequest
	(*CreateExpenseCategoryRequest)(nil),    // 6: expense.CreateExpenseCategoryRequest
	(*UpdateExpenseCategoryRequest)(nil),    // 7: expense.UpdateExpenseCategoryRequest
	(*DeleteExpenseCategoryRequest)(nil),    // 8: expense.DeleteExpenseCategoryRequest
	(*GetAllExpensesByWalletIdRequest)(nil), // 9: expense.GetAllExpensesByWalletIdRequest
	(*GetAllExpensesByUserIdRequest)(nil),   // 10: expense.GetAllExpensesByUserIdRequest
	(*GetAllExpensesCategoryRequest)(nil),   // 11: expense.GetAllExpensesCategoryRequest
	(*GetExpenseByIDRequest)(nil),           // 12: expense.GetExpenseByIDRequest
	(*GetExpenseByIDResponse)(nil),          // 13: expense.GetExpenseByIDResponse
	(*CreateExpenseResponse)(nil),           // 14: expense.CreateExpenseResponse
	(*UpdateExpenseResponse)(nil),           // 15: expense.UpdateExpenseResponse
	(*CreateExpenseCategoryResponse)(nil),   // 16: expense.CreateExpenseCategoryResponse
	(*UpdateExpenseCategoryResponse)(nil),   // 17: expense.UpdateExpenseCategoryResponse
	(*GetAllExpensesResponse)(nil),          // 18: expense.GetAllExpensesResponse
	(*GetAllExpensesCategoryResponse)(nil),  // 19: expense.GetAllExpensesCategoryResponse
	(*timestamppb.Timestamp)(nil),           // 20: google.protobuf.Timestamp
	(*fieldmaskpb.FieldMask)(nil),           // 21: google.protobuf.FieldMask
	(*emptypb.Empty)(nil),                   // 22: google.protobuf.Empty
}
var file_expense_proto_depIdxs = []int32{
	20, // 0: expense.ExpenseCategory.created_at:type_name -> google.protobuf.Timestamp
	20, // 1: expense.ExpenseCategory.updated_at:type_name -> google.protobuf.Timestamp
	1,  // 2: expense.Expense.expense_items:type_name -> expense.ExpenseItem
	20, // 3: expense.Expense.created_at:type_name -> google.protobuf.Timestamp
	20, // 4: expense.Expense.updated_at:type_name -> google.protobuf.Timestamp
	2,  // 5: expense.CreateExpenseRequest.expense:type_name -> expense.Expense
	2,  // 6: expense.UpdateExpenseRequest.expense:type_name -> expense.Expense
	21, // 7: expense.UpdateExpenseRequest.update_mask:type_name -> google.protobuf.FieldMask
	0,  // 8: expense.CreateExpenseCategoryRequest.expense_category:type_name -> expense.ExpenseCategory
	0,  // 9: expense.UpdateExpenseCategoryRequest.expense_category:type_name -> expense.ExpenseCategory
	21, // 10: expense.UpdateExpenseCategoryRequest.update_mask:type_name -> google.protobuf.FieldMask
	2,  // 11: expense.GetExpenseByIDResponse.expense:type_name -> expense.Expense
	2,  // 12: expense.CreateExpenseResponse.expense:type_name -> expense.Expense
	2,  // 13: expense.UpdateExpenseResponse.expense:type_name -> expense.Expense
	0,  // 14: expense.CreateExpenseCategoryResponse.expense_category:type_name -> expense.ExpenseCategory
	0,  // 15: expense.UpdateExpenseCategoryResponse.expense_category:type_name -> expense.ExpenseCategory
	2,  // 16: expense.GetAllExpensesResponse.expenses:type_name -> expense.Expense
	0,  // 17: expense.GetAllExpensesCategoryResponse.expense_categories:type_name -> expense.ExpenseCategory
	3,  // 18: expense.ExpenseService.CreateExpense:input_type -> expense.CreateExpenseRequest
	4,  // 19: expense.ExpenseService.UpdateExpense:input_type -> expense.UpdateExpenseRequest
	5,  // 20: expense.ExpenseService.DeleteExpense:input_type -> expense.DeleteExpenseRequest
	9,  // 21: expense.ExpenseService.GetAllExpensesByWalletId:input_type -> expense.GetAllExpensesByWalletIdRequest
	10, // 22: expense.ExpenseService.GetAllExpensesByUserId:input_type -> expense.GetAllExpensesByUserIdRequest
	12, // 23: expense.ExpenseService.GetExpenseByID:input_type -> expense.GetExpenseByIDRequest
	6,  // 24: expense.ExpenseService.CreateExpenseCategory:input_type -> expense.CreateExpenseCategoryRequest
	7,  // 25: expense.ExpenseService.UpdateExpenseCategory:input_type -> expense.UpdateExpenseCategoryRequest
	8,  // 26: expense.ExpenseService.DeleteExpenseCategory:input_type -> expense.DeleteExpenseCategoryRequest
	11, // 27: expense.ExpenseService.GetAllExpensesCategory:input_type -> expense.GetAllExpensesCategoryRequest
	14, // 28: expense.ExpenseService.CreateExpense:output_type -> expense.CreateExpenseResponse
	15, // 29: expense.ExpenseService.UpdateExpense:output_type -> expense.UpdateExpenseResponse
	22, // 30: expense.ExpenseService.DeleteExpense:output_type -> google.protobuf.Empty
	18, // 31: expense.ExpenseService.GetAllExpensesByWalletId:output_type -> expense.GetAllExpensesResponse
	18, // 32: expense.ExpenseService.GetAllExpensesByUserId:output_type -> expense.GetAllExpensesResponse
	13, // 33: expense.ExpenseService.GetExpenseByID:output_type -> expense.GetExpenseByIDResponse
	16, // 34: expense.ExpenseService.CreateExpenseCategory:output_type -> expense.CreateExpenseCategoryResponse
	17, // 35: expense.ExpenseService.UpdateExpenseCategory:output_type -> expense.UpdateExpenseCategoryResponse
	22, // 36: expense.ExpenseService.DeleteExpenseCategory:output_type -> google.protobuf.Empty
	19, // 37: expense.ExpenseService.GetAllExpensesCategory:output_type -> expense.GetAllExpensesCategoryResponse
	28, // [28:38] is the sub-list for method output_type
	18, // [18:28] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_expense_proto_init() }
func file_expense_proto_init() {
	if File_expense_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_expense_proto_rawDesc), len(file_expense_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_expense_proto_goTypes,
		DependencyIndexes: file_expense_proto_depIdxs,
		MessageInfos:      file_expense_proto_msgTypes,
	}.Build()
	File_expense_proto = out.File
	file_expense_proto_goTypes = nil
	file_expense_proto_depIdxs = nil
}
