// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.19.6
// source: llm.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExtractExpenseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	WalletId      string                 `protobuf:"bytes,2,opt,name=wallet_id,json=walletId,proto3" json:"wallet_id,omitempty"`
	UserInput     string                 `protobuf:"bytes,3,opt,name=user_input,json=userInput,proto3" json:"user_input,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtractExpenseRequest) Reset() {
	*x = ExtractExpenseRequest{}
	mi := &file_llm_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtractExpenseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtractExpenseRequest) ProtoMessage() {}

func (x *ExtractExpenseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_llm_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtractExpenseRequest.ProtoReflect.Descriptor instead.
func (*ExtractExpenseRequest) Descriptor() ([]byte, []int) {
	return file_llm_proto_rawDescGZIP(), []int{0}
}

func (x *ExtractExpenseRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ExtractExpenseRequest) GetWalletId() string {
	if x != nil {
		return x.WalletId
	}
	return ""
}

func (x *ExtractExpenseRequest) GetUserInput() string {
	if x != nil {
		return x.UserInput
	}
	return ""
}

type GetLLMJobsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLLMJobsRequest) Reset() {
	*x = GetLLMJobsRequest{}
	mi := &file_llm_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLLMJobsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLLMJobsRequest) ProtoMessage() {}

func (x *GetLLMJobsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_llm_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLLMJobsRequest.ProtoReflect.Descriptor instead.
func (*GetLLMJobsRequest) Descriptor() ([]byte, []int) {
	return file_llm_proto_rawDescGZIP(), []int{1}
}

func (x *GetLLMJobsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type LLMJob struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId         string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	WalletId       string                 `protobuf:"bytes,3,opt,name=wallet_id,json=walletId,proto3" json:"wallet_id,omitempty"`
	UserInput      string                 `protobuf:"bytes,4,opt,name=user_input,json=userInput,proto3" json:"user_input,omitempty"`
	Status         string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	RetryCount     int32                  `protobuf:"varint,6,opt,name=retry_count,json=retryCount,proto3" json:"retry_count,omitempty"`
	ExpenseId      string                 `protobuf:"bytes,7,opt,name=expense_id,json=expenseId,proto3" json:"expense_id,omitempty"`
	ErrorMessage   string                 `protobuf:"bytes,8,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	LlmResult      string                 `protobuf:"bytes,9,opt,name=llm_result,json=llmResult,proto3" json:"llm_result,omitempty"`
	LlmStatus      string                 `protobuf:"bytes,10,opt,name=llm_status,json=llmStatus,proto3" json:"llm_status,omitempty"`
	ExpenseStatus  string                 `protobuf:"bytes,11,opt,name=expense_status,json=expenseStatus,proto3" json:"expense_status,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,12,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	CreatedAt      string                 `protobuf:"bytes,13,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      string                 `protobuf:"bytes,14,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *LLMJob) Reset() {
	*x = LLMJob{}
	mi := &file_llm_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LLMJob) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LLMJob) ProtoMessage() {}

func (x *LLMJob) ProtoReflect() protoreflect.Message {
	mi := &file_llm_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LLMJob.ProtoReflect.Descriptor instead.
func (*LLMJob) Descriptor() ([]byte, []int) {
	return file_llm_proto_rawDescGZIP(), []int{2}
}

func (x *LLMJob) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *LLMJob) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *LLMJob) GetWalletId() string {
	if x != nil {
		return x.WalletId
	}
	return ""
}

func (x *LLMJob) GetUserInput() string {
	if x != nil {
		return x.UserInput
	}
	return ""
}

func (x *LLMJob) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *LLMJob) GetRetryCount() int32 {
	if x != nil {
		return x.RetryCount
	}
	return 0
}

func (x *LLMJob) GetExpenseId() string {
	if x != nil {
		return x.ExpenseId
	}
	return ""
}

func (x *LLMJob) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *LLMJob) GetLlmResult() string {
	if x != nil {
		return x.LlmResult
	}
	return ""
}

func (x *LLMJob) GetLlmStatus() string {
	if x != nil {
		return x.LlmStatus
	}
	return ""
}

func (x *LLMJob) GetExpenseStatus() string {
	if x != nil {
		return x.ExpenseStatus
	}
	return ""
}

func (x *LLMJob) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *LLMJob) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *LLMJob) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type GetLLMJobsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Jobs          []*LLMJob              `protobuf:"bytes,1,rep,name=jobs,proto3" json:"jobs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLLMJobsResponse) Reset() {
	*x = GetLLMJobsResponse{}
	mi := &file_llm_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLLMJobsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLLMJobsResponse) ProtoMessage() {}

func (x *GetLLMJobsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_llm_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLLMJobsResponse.ProtoReflect.Descriptor instead.
func (*GetLLMJobsResponse) Descriptor() ([]byte, []int) {
	return file_llm_proto_rawDescGZIP(), []int{3}
}

func (x *GetLLMJobsResponse) GetJobs() []*LLMJob {
	if x != nil {
		return x.Jobs
	}
	return nil
}

var File_llm_proto protoreflect.FileDescriptor

const file_llm_proto_rawDesc = "" +
	"\n" +
	"\tllm.proto\x12\x03llm\x1a\x1bgoogle/protobuf/empty.proto\"l\n" +
	"\x15ExtractExpenseRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\twallet_id\x18\x02 \x01(\tR\bwalletId\x12\x1d\n" +
	"\n" +
	"user_input\x18\x03 \x01(\tR\tuserInput\",\n" +
	"\x11GetLLMJobsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\xb6\x03\n" +
	"\x06LLMJob\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1b\n" +
	"\twallet_id\x18\x03 \x01(\tR\bwalletId\x12\x1d\n" +
	"\n" +
	"user_input\x18\x04 \x01(\tR\tuserInput\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x1f\n" +
	"\vretry_count\x18\x06 \x01(\x05R\n" +
	"retryCount\x12\x1d\n" +
	"\n" +
	"expense_id\x18\a \x01(\tR\texpenseId\x12#\n" +
	"\rerror_message\x18\b \x01(\tR\ferrorMessage\x12\x1d\n" +
	"\n" +
	"llm_result\x18\t \x01(\tR\tllmResult\x12\x1d\n" +
	"\n" +
	"llm_status\x18\n" +
	" \x01(\tR\tllmStatus\x12%\n" +
	"\x0eexpense_status\x18\v \x01(\tR\rexpenseStatus\x12'\n" +
	"\x0fidempotency_key\x18\f \x01(\tR\x0eidempotencyKey\x12\x1d\n" +
	"\n" +
	"created_at\x18\r \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x0e \x01(\tR\tupdatedAt\"5\n" +
	"\x12GetLLMJobsResponse\x12\x1f\n" +
	"\x04jobs\x18\x01 \x03(\v2\v.llm.LLMJobR\x04jobs2\x95\x01\n" +
	"\n" +
	"LLMService\x12F\n" +
	"\x0eExtractExpense\x12\x1a.llm.ExtractExpenseRequest\x1a\x16.google.protobuf.Empty\"\x00\x12?\n" +
	"\n" +
	"GetLLMJobs\x12\x16.llm.GetLLMJobsRequest\x1a\x17.llm.GetLLMJobsResponse\"\x00BJZHgithub.com/raihan-faza/scriptsea-ept/backend/services/llm_job_service/pbb\x06proto3"

var (
	file_llm_proto_rawDescOnce sync.Once
	file_llm_proto_rawDescData []byte
)

func file_llm_proto_rawDescGZIP() []byte {
	file_llm_proto_rawDescOnce.Do(func() {
		file_llm_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_llm_proto_rawDesc), len(file_llm_proto_rawDesc)))
	})
	return file_llm_proto_rawDescData
}

var file_llm_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_llm_proto_goTypes = []any{
	(*ExtractExpenseRequest)(nil), // 0: llm.ExtractExpenseRequest
	(*GetLLMJobsRequest)(nil),     // 1: llm.GetLLMJobsRequest
	(*LLMJob)(nil),                // 2: llm.LLMJob
	(*GetLLMJobsResponse)(nil),    // 3: llm.GetLLMJobsResponse
	(*emptypb.Empty)(nil),         // 4: google.protobuf.Empty
}
var file_llm_proto_depIdxs = []int32{
	2, // 0: llm.GetLLMJobsResponse.jobs:type_name -> llm.LLMJob
	0, // 1: llm.LLMService.ExtractExpense:input_type -> llm.ExtractExpenseRequest
	1, // 2: llm.LLMService.GetLLMJobs:input_type -> llm.GetLLMJobsRequest
	4, // 3: llm.LLMService.ExtractExpense:output_type -> google.protobuf.Empty
	3, // 4: llm.LLMService.GetLLMJobs:output_type -> llm.GetLLMJobsResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_llm_proto_init() }
func file_llm_proto_init() {
	if File_llm_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_llm_proto_rawDesc), len(file_llm_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_llm_proto_goTypes,
		DependencyIndexes: file_llm_proto_depIdxs,
		MessageInfos:      file_llm_proto_msgTypes,
	}.Build()
	File_llm_proto = out.File
	file_llm_proto_goTypes = nil
	file_llm_proto_depIdxs = nil
}
