// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.19.6
// source: wallet.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Wallet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	OwnerId       string                 `protobuf:"bytes,3,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	TotalBalance  int64                  `protobuf:"varint,4,opt,name=total_balance,json=totalBalance,proto3" json:"total_balance,omitempty"`
	Currency      string                 `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Wallet) Reset() {
	*x = Wallet{}
	mi := &file_wallet_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Wallet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Wallet) ProtoMessage() {}

func (x *Wallet) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Wallet.ProtoReflect.Descriptor instead.
func (*Wallet) Descriptor() ([]byte, []int) {
	return file_wallet_proto_rawDescGZIP(), []int{0}
}

func (x *Wallet) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Wallet) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Wallet) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *Wallet) GetTotalBalance() int64 {
	if x != nil {
		return x.TotalBalance
	}
	return 0
}

func (x *Wallet) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

type Permission struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ManageUser      bool                   `protobuf:"varint,1,opt,name=manage_user,json=manageUser,proto3" json:"manage_user,omitempty"`
	AllocateBalance bool                   `protobuf:"varint,2,opt,name=allocate_balance,json=allocateBalance,proto3" json:"allocate_balance,omitempty"`
	GenerateReport  bool                   `protobuf:"varint,3,opt,name=generate_report,json=generateReport,proto3" json:"generate_report,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Permission) Reset() {
	*x = Permission{}
	mi := &file_wallet_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Permission) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Permission) ProtoMessage() {}

func (x *Permission) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Permission.ProtoReflect.Descriptor instead.
func (*Permission) Descriptor() ([]byte, []int) {
	return file_wallet_proto_rawDescGZIP(), []int{1}
}

func (x *Permission) GetManageUser() bool {
	if x != nil {
		return x.ManageUser
	}
	return false
}

func (x *Permission) GetAllocateBalance() bool {
	if x != nil {
		return x.AllocateBalance
	}
	return false
}

func (x *Permission) GetGenerateReport() bool {
	if x != nil {
		return x.GenerateReport
	}
	return false
}

type WalletMember struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	WalletId        string                 `protobuf:"bytes,1,opt,name=wallet_id,json=walletId,proto3" json:"wallet_id,omitempty"`
	UserId          string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AllocationLimit int64                  `protobuf:"varint,3,opt,name=allocation_limit,json=allocationLimit,proto3" json:"allocation_limit,omitempty"`
	AllocationUsed  int64                  `protobuf:"varint,4,opt,name=allocation_used,json=allocationUsed,proto3" json:"allocation_used,omitempty"`
	Permission      *Permission            `protobuf:"bytes,5,opt,name=permission,proto3" json:"permission,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *WalletMember) Reset() {
	*x = WalletMember{}
	mi := &file_wallet_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WalletMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WalletMember) ProtoMessage() {}

func (x *WalletMember) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WalletMember.ProtoReflect.Descriptor instead.
func (*WalletMember) Descriptor() ([]byte, []int) {
	return file_wallet_proto_rawDescGZIP(), []int{2}
}

func (x *WalletMember) GetWalletId() string {
	if x != nil {
		return x.WalletId
	}
	return ""
}

func (x *WalletMember) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *WalletMember) GetAllocationLimit() int64 {
	if x != nil {
		return x.AllocationLimit
	}
	return 0
}

func (x *WalletMember) GetAllocationUsed() int64 {
	if x != nil {
		return x.AllocationUsed
	}
	return 0
}

func (x *WalletMember) GetPermission() *Permission {
	if x != nil {
		return x.Permission
	}
	return nil
}

type DeleteWalletRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WalletId      string                 `protobuf:"bytes,1,opt,name=wallet_id,json=walletId,proto3" json:"wallet_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteWalletRequest) Reset() {
	*x = DeleteWalletRequest{}
	mi := &file_wallet_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteWalletRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteWalletRequest) ProtoMessage() {}

func (x *DeleteWalletRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteWalletRequest.ProtoReflect.Descriptor instead.
func (*DeleteWalletRequest) Descriptor() ([]byte, []int) {
	return file_wallet_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteWalletRequest) GetWalletId() string {
	if x != nil {
		return x.WalletId
	}
	return ""
}

type GetWalletRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WalletId      string                 `protobuf:"bytes,1,opt,name=wallet_id,json=walletId,proto3" json:"wallet_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWalletRequest) Reset() {
	*x = GetWalletRequest{}
	mi := &file_wallet_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWalletRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWalletRequest) ProtoMessage() {}

func (x *GetWalletRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWalletRequest.ProtoReflect.Descriptor instead.
func (*GetWalletRequest) Descriptor() ([]byte, []int) {
	return file_wallet_proto_rawDescGZIP(), []int{4}
}

func (x *GetWalletRequest) GetWalletId() string {
	if x != nil {
		return x.WalletId
	}
	return ""
}

type AddMemberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WalletMember  *WalletMember          `protobuf:"bytes,1,opt,name=wallet_member,json=walletMember,proto3" json:"wallet_member,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddMemberRequest) Reset() {
	*x = AddMemberRequest{}
	mi := &file_wallet_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddMemberRequest) ProtoMessage() {}

func (x *AddMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddMemberRequest.ProtoReflect.Descriptor instead.
func (*AddMemberRequest) Descriptor() ([]byte, []int) {
	return file_wallet_proto_rawDescGZIP(), []int{5}
}

func (x *AddMemberRequest) GetWalletMember() *WalletMember {
	if x != nil {
		return x.WalletMember
	}
	return nil
}

type AllocateBalanceRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	WalletId        string                 `protobuf:"bytes,1,opt,name=wallet_id,json=walletId,proto3" json:"wallet_id,omitempty"`
	MemberId        string                 `protobuf:"bytes,2,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`
	AllocationLimit int64                  `protobuf:"varint,3,opt,name=allocation_limit,json=allocationLimit,proto3" json:"allocation_limit,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AllocateBalanceRequest) Reset() {
	*x = AllocateBalanceRequest{}
	mi := &file_wallet_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllocateBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllocateBalanceRequest) ProtoMessage() {}

func (x *AllocateBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllocateBalanceRequest.ProtoReflect.Descriptor instead.
func (*AllocateBalanceRequest) Descriptor() ([]byte, []int) {
	return file_wallet_proto_rawDescGZIP(), []int{6}
}

func (x *AllocateBalanceRequest) GetWalletId() string {
	if x != nil {
		return x.WalletId
	}
	return ""
}

func (x *AllocateBalanceRequest) GetMemberId() string {
	if x != nil {
		return x.MemberId
	}
	return ""
}

func (x *AllocateBalanceRequest) GetAllocationLimit() int64 {
	if x != nil {
		return x.AllocationLimit
	}
	return 0
}

type CreateWalletRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	WalletName     string                 `protobuf:"bytes,1,opt,name=wallet_name,json=walletName,proto3" json:"wallet_name,omitempty"`
	OwnerId        string                 `protobuf:"bytes,2,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	InitialBalance int64                  `protobuf:"varint,3,opt,name=initial_balance,json=initialBalance,proto3" json:"initial_balance,omitempty"`
	Currency       string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateWalletRequest) Reset() {
	*x = CreateWalletRequest{}
	mi := &file_wallet_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWalletRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWalletRequest) ProtoMessage() {}

func (x *CreateWalletRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWalletRequest.ProtoReflect.Descriptor instead.
func (*CreateWalletRequest) Descriptor() ([]byte, []int) {
	return file_wallet_proto_rawDescGZIP(), []int{7}
}

func (x *CreateWalletRequest) GetWalletName() string {
	if x != nil {
		return x.WalletName
	}
	return ""
}

func (x *CreateWalletRequest) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *CreateWalletRequest) GetInitialBalance() int64 {
	if x != nil {
		return x.InitialBalance
	}
	return 0
}

func (x *CreateWalletRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

type UpdateWalletRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WalletId      string                 `protobuf:"bytes,1,opt,name=wallet_id,json=walletId,proto3" json:"wallet_id,omitempty"`
	WalletName    string                 `protobuf:"bytes,2,opt,name=wallet_name,json=walletName,proto3" json:"wallet_name,omitempty"`
	Currency      string                 `protobuf:"bytes,3,opt,name=currency,proto3" json:"currency,omitempty"`
	UpdateMask    *fieldmaskpb.FieldMask `protobuf:"bytes,4,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateWalletRequest) Reset() {
	*x = UpdateWalletRequest{}
	mi := &file_wallet_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateWalletRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateWalletRequest) ProtoMessage() {}

func (x *UpdateWalletRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateWalletRequest.ProtoReflect.Descriptor instead.
func (*UpdateWalletRequest) Descriptor() ([]byte, []int) {
	return file_wallet_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateWalletRequest) GetWalletId() string {
	if x != nil {
		return x.WalletId
	}
	return ""
}

func (x *UpdateWalletRequest) GetWalletName() string {
	if x != nil {
		return x.WalletName
	}
	return ""
}

func (x *UpdateWalletRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *UpdateWalletRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

type ValidateAndDeductBalanceRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	WalletId       string                 `protobuf:"bytes,1,opt,name=wallet_id,json=walletId,proto3" json:"wallet_id,omitempty"`
	UserId         string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Amount         int64                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,4,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ValidateAndDeductBalanceRequest) Reset() {
	*x = ValidateAndDeductBalanceRequest{}
	mi := &file_wallet_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateAndDeductBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateAndDeductBalanceRequest) ProtoMessage() {}

func (x *ValidateAndDeductBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateAndDeductBalanceRequest.ProtoReflect.Descriptor instead.
func (*ValidateAndDeductBalanceRequest) Descriptor() ([]byte, []int) {
	return file_wallet_proto_rawDescGZIP(), []int{9}
}

func (x *ValidateAndDeductBalanceRequest) GetWalletId() string {
	if x != nil {
		return x.WalletId
	}
	return ""
}

func (x *ValidateAndDeductBalanceRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ValidateAndDeductBalanceRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *ValidateAndDeductBalanceRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type GetWalletMembersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WalletId      string                 `protobuf:"bytes,1,opt,name=wallet_id,json=walletId,proto3" json:"wallet_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWalletMembersRequest) Reset() {
	*x = GetWalletMembersRequest{}
	mi := &file_wallet_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWalletMembersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWalletMembersRequest) ProtoMessage() {}

func (x *GetWalletMembersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWalletMembersRequest.ProtoReflect.Descriptor instead.
func (*GetWalletMembersRequest) Descriptor() ([]byte, []int) {
	return file_wallet_proto_rawDescGZIP(), []int{10}
}

func (x *GetWalletMembersRequest) GetWalletId() string {
	if x != nil {
		return x.WalletId
	}
	return ""
}

type DeleteWalletMemberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WalletId      string                 `protobuf:"bytes,1,opt,name=wallet_id,json=walletId,proto3" json:"wallet_id,omitempty"`
	MemberId      string                 `protobuf:"bytes,2,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteWalletMemberRequest) Reset() {
	*x = DeleteWalletMemberRequest{}
	mi := &file_wallet_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteWalletMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteWalletMemberRequest) ProtoMessage() {}

func (x *DeleteWalletMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteWalletMemberRequest.ProtoReflect.Descriptor instead.
func (*DeleteWalletMemberRequest) Descriptor() ([]byte, []int) {
	return file_wallet_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteWalletMemberRequest) GetWalletId() string {
	if x != nil {
		return x.WalletId
	}
	return ""
}

func (x *DeleteWalletMemberRequest) GetMemberId() string {
	if x != nil {
		return x.MemberId
	}
	return ""
}

type AdjustBalanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WalletId      string                 `protobuf:"bytes,1,opt,name=wallet_id,json=walletId,proto3" json:"wallet_id,omitempty"`
	Amount        int64                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"` // can be + or -
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdjustBalanceRequest) Reset() {
	*x = AdjustBalanceRequest{}
	mi := &file_wallet_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdjustBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdjustBalanceRequest) ProtoMessage() {}

func (x *AdjustBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdjustBalanceRequest.ProtoReflect.Descriptor instead.
func (*AdjustBalanceRequest) Descriptor() ([]byte, []int) {
	return file_wallet_proto_rawDescGZIP(), []int{12}
}

func (x *AdjustBalanceRequest) GetWalletId() string {
	if x != nil {
		return x.WalletId
	}
	return ""
}

func (x *AdjustBalanceRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

// response nihh
type AllocateBalanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WalletMember  *WalletMember          `protobuf:"bytes,1,opt,name=wallet_member,json=walletMember,proto3" json:"wallet_member,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllocateBalanceResponse) Reset() {
	*x = AllocateBalanceResponse{}
	mi := &file_wallet_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllocateBalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllocateBalanceResponse) ProtoMessage() {}

func (x *AllocateBalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllocateBalanceResponse.ProtoReflect.Descriptor instead.
func (*AllocateBalanceResponse) Descriptor() ([]byte, []int) {
	return file_wallet_proto_rawDescGZIP(), []int{13}
}

func (x *AllocateBalanceResponse) GetWalletMember() *WalletMember {
	if x != nil {
		return x.WalletMember
	}
	return nil
}

type GetWalletResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Wallet        *Wallet                `protobuf:"bytes,1,opt,name=wallet,proto3" json:"wallet,omitempty"`
	Members       []*WalletMember        `protobuf:"bytes,2,rep,name=members,proto3" json:"members,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWalletResponse) Reset() {
	*x = GetWalletResponse{}
	mi := &file_wallet_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWalletResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWalletResponse) ProtoMessage() {}

func (x *GetWalletResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWalletResponse.ProtoReflect.Descriptor instead.
func (*GetWalletResponse) Descriptor() ([]byte, []int) {
	return file_wallet_proto_rawDescGZIP(), []int{14}
}

func (x *GetWalletResponse) GetWallet() *Wallet {
	if x != nil {
		return x.Wallet
	}
	return nil
}

func (x *GetWalletResponse) GetMembers() []*WalletMember {
	if x != nil {
		return x.Members
	}
	return nil
}

type UpdateWalletResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Wallet        *Wallet                `protobuf:"bytes,1,opt,name=wallet,proto3" json:"wallet,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateWalletResponse) Reset() {
	*x = UpdateWalletResponse{}
	mi := &file_wallet_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateWalletResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateWalletResponse) ProtoMessage() {}

func (x *UpdateWalletResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateWalletResponse.ProtoReflect.Descriptor instead.
func (*UpdateWalletResponse) Descriptor() ([]byte, []int) {
	return file_wallet_proto_rawDescGZIP(), []int{15}
}

func (x *UpdateWalletResponse) GetWallet() *Wallet {
	if x != nil {
		return x.Wallet
	}
	return nil
}

type CreateWalletResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Wallet        *Wallet                `protobuf:"bytes,1,opt,name=wallet,proto3" json:"wallet,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateWalletResponse) Reset() {
	*x = CreateWalletResponse{}
	mi := &file_wallet_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWalletResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWalletResponse) ProtoMessage() {}

func (x *CreateWalletResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWalletResponse.ProtoReflect.Descriptor instead.
func (*CreateWalletResponse) Descriptor() ([]byte, []int) {
	return file_wallet_proto_rawDescGZIP(), []int{16}
}

func (x *CreateWalletResponse) GetWallet() *Wallet {
	if x != nil {
		return x.Wallet
	}
	return nil
}

type ValidateAndDeductBalanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateAndDeductBalanceResponse) Reset() {
	*x = ValidateAndDeductBalanceResponse{}
	mi := &file_wallet_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateAndDeductBalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateAndDeductBalanceResponse) ProtoMessage() {}

func (x *ValidateAndDeductBalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateAndDeductBalanceResponse.ProtoReflect.Descriptor instead.
func (*ValidateAndDeductBalanceResponse) Descriptor() ([]byte, []int) {
	return file_wallet_proto_rawDescGZIP(), []int{17}
}

type AddMemberResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddMemberResponse) Reset() {
	*x = AddMemberResponse{}
	mi := &file_wallet_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddMemberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddMemberResponse) ProtoMessage() {}

func (x *AddMemberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddMemberResponse.ProtoReflect.Descriptor instead.
func (*AddMemberResponse) Descriptor() ([]byte, []int) {
	return file_wallet_proto_rawDescGZIP(), []int{18}
}

type GetWalletMembersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WalletMembers []*WalletMember        `protobuf:"bytes,1,rep,name=wallet_members,json=walletMembers,proto3" json:"wallet_members,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWalletMembersResponse) Reset() {
	*x = GetWalletMembersResponse{}
	mi := &file_wallet_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWalletMembersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWalletMembersResponse) ProtoMessage() {}

func (x *GetWalletMembersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWalletMembersResponse.ProtoReflect.Descriptor instead.
func (*GetWalletMembersResponse) Descriptor() ([]byte, []int) {
	return file_wallet_proto_rawDescGZIP(), []int{19}
}

func (x *GetWalletMembersResponse) GetWalletMembers() []*WalletMember {
	if x != nil {
		return x.WalletMembers
	}
	return nil
}

type DeleteWalletMemberResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WalletMembers []*WalletMember        `protobuf:"bytes,1,rep,name=wallet_members,json=walletMembers,proto3" json:"wallet_members,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteWalletMemberResponse) Reset() {
	*x = DeleteWalletMemberResponse{}
	mi := &file_wallet_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteWalletMemberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteWalletMemberResponse) ProtoMessage() {}

func (x *DeleteWalletMemberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteWalletMemberResponse.ProtoReflect.Descriptor instead.
func (*DeleteWalletMemberResponse) Descriptor() ([]byte, []int) {
	return file_wallet_proto_rawDescGZIP(), []int{20}
}

func (x *DeleteWalletMemberResponse) GetWalletMembers() []*WalletMember {
	if x != nil {
		return x.WalletMembers
	}
	return nil
}

type AdjustBalanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Wallet        *Wallet                `protobuf:"bytes,1,opt,name=wallet,proto3" json:"wallet,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdjustBalanceResponse) Reset() {
	*x = AdjustBalanceResponse{}
	mi := &file_wallet_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdjustBalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdjustBalanceResponse) ProtoMessage() {}

func (x *AdjustBalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdjustBalanceResponse.ProtoReflect.Descriptor instead.
func (*AdjustBalanceResponse) Descriptor() ([]byte, []int) {
	return file_wallet_proto_rawDescGZIP(), []int{21}
}

func (x *AdjustBalanceResponse) GetWallet() *Wallet {
	if x != nil {
		return x.Wallet
	}
	return nil
}

var File_wallet_proto protoreflect.FileDescriptor

const file_wallet_proto_rawDesc = "" +
	"\n" +
	"\fwallet.proto\x12\x06wallet\x1a google/protobuf/field_mask.proto\x1a\x1bgoogle/protobuf/empty.proto\"\x88\x01\n" +
	"\x06Wallet\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x19\n" +
	"\bowner_id\x18\x03 \x01(\tR\aownerId\x12#\n" +
	"\rtotal_balance\x18\x04 \x01(\x03R\ftotalBalance\x12\x1a\n" +
	"\bcurrency\x18\x05 \x01(\tR\bcurrency\"\x81\x01\n" +
	"\n" +
	"Permission\x12\x1f\n" +
	"\vmanage_user\x18\x01 \x01(\bR\n" +
	"manageUser\x12)\n" +
	"\x10allocate_balance\x18\x02 \x01(\bR\x0fallocateBalance\x12'\n" +
	"\x0fgenerate_report\x18\x03 \x01(\bR\x0egenerateReport\"\xcc\x01\n" +
	"\fWalletMember\x12\x1b\n" +
	"\twallet_id\x18\x01 \x01(\tR\bwalletId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12)\n" +
	"\x10allocation_limit\x18\x03 \x01(\x03R\x0fallocationLimit\x12'\n" +
	"\x0fallocation_used\x18\x04 \x01(\x03R\x0eallocationUsed\x122\n" +
	"\n" +
	"permission\x18\x05 \x01(\v2\x12.wallet.PermissionR\n" +
	"permission\"2\n" +
	"\x13DeleteWalletRequest\x12\x1b\n" +
	"\twallet_id\x18\x01 \x01(\tR\bwalletId\"/\n" +
	"\x10GetWalletRequest\x12\x1b\n" +
	"\twallet_id\x18\x01 \x01(\tR\bwalletId\"M\n" +
	"\x10AddMemberRequest\x129\n" +
	"\rwallet_member\x18\x01 \x01(\v2\x14.wallet.WalletMemberR\fwalletMember\"}\n" +
	"\x16AllocateBalanceRequest\x12\x1b\n" +
	"\twallet_id\x18\x01 \x01(\tR\bwalletId\x12\x1b\n" +
	"\tmember_id\x18\x02 \x01(\tR\bmemberId\x12)\n" +
	"\x10allocation_limit\x18\x03 \x01(\x03R\x0fallocationLimit\"\x96\x01\n" +
	"\x13CreateWalletRequest\x12\x1f\n" +
	"\vwallet_name\x18\x01 \x01(\tR\n" +
	"walletName\x12\x19\n" +
	"\bowner_id\x18\x02 \x01(\tR\aownerId\x12'\n" +
	"\x0finitial_balance\x18\x03 \x01(\x03R\x0einitialBalance\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\"\xac\x01\n" +
	"\x13UpdateWalletRequest\x12\x1b\n" +
	"\twallet_id\x18\x01 \x01(\tR\bwalletId\x12\x1f\n" +
	"\vwallet_name\x18\x02 \x01(\tR\n" +
	"walletName\x12\x1a\n" +
	"\bcurrency\x18\x03 \x01(\tR\bcurrency\x12;\n" +
	"\vupdate_mask\x18\x04 \x01(\v2\x1a.google.protobuf.FieldMaskR\n" +
	"updateMask\"\x98\x01\n" +
	"\x1fValidateAndDeductBalanceRequest\x12\x1b\n" +
	"\twallet_id\x18\x01 \x01(\tR\bwalletId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x03R\x06amount\x12'\n" +
	"\x0fidempotency_key\x18\x04 \x01(\tR\x0eidempotencyKey\"6\n" +
	"\x17GetWalletMembersRequest\x12\x1b\n" +
	"\twallet_id\x18\x01 \x01(\tR\bwalletId\"U\n" +
	"\x19DeleteWalletMemberRequest\x12\x1b\n" +
	"\twallet_id\x18\x01 \x01(\tR\bwalletId\x12\x1b\n" +
	"\tmember_id\x18\x02 \x01(\tR\bmemberId\"K\n" +
	"\x14AdjustBalanceRequest\x12\x1b\n" +
	"\twallet_id\x18\x01 \x01(\tR\bwalletId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x03R\x06amount\"T\n" +
	"\x17AllocateBalanceResponse\x129\n" +
	"\rwallet_member\x18\x01 \x01(\v2\x14.wallet.WalletMemberR\fwalletMember\"k\n" +
	"\x11GetWalletResponse\x12&\n" +
	"\x06wallet\x18\x01 \x01(\v2\x0e.wallet.WalletR\x06wallet\x12.\n" +
	"\amembers\x18\x02 \x03(\v2\x14.wallet.WalletMemberR\amembers\">\n" +
	"\x14UpdateWalletResponse\x12&\n" +
	"\x06wallet\x18\x01 \x01(\v2\x0e.wallet.WalletR\x06wallet\">\n" +
	"\x14CreateWalletResponse\x12&\n" +
	"\x06wallet\x18\x01 \x01(\v2\x0e.wallet.WalletR\x06wallet\"\"\n" +
	" ValidateAndDeductBalanceResponse\"\x13\n" +
	"\x11AddMemberResponse\"W\n" +
	"\x18GetWalletMembersResponse\x12;\n" +
	"\x0ewallet_members\x18\x01 \x03(\v2\x14.wallet.WalletMemberR\rwalletMembers\"Y\n" +
	"\x1aDeleteWalletMemberResponse\x12;\n" +
	"\x0ewallet_members\x18\x01 \x03(\v2\x14.wallet.WalletMemberR\rwalletMembers\"?\n" +
	"\x15AdjustBalanceResponse\x12&\n" +
	"\x06wallet\x18\x01 \x01(\v2\x0e.wallet.WalletR\x06wallet2\xa6\x06\n" +
	"\rWalletService\x12K\n" +
	"\fCreateWallet\x12\x1b.wallet.CreateWalletRequest\x1a\x1c.wallet.CreateWalletResponse\"\x00\x12K\n" +
	"\fUpdateWallet\x12\x1b.wallet.UpdateWalletRequest\x1a\x1c.wallet.UpdateWalletResponse\"\x00\x12E\n" +
	"\fDeleteWallet\x12\x1b.wallet.DeleteWalletRequest\x1a\x16.google.protobuf.Empty\"\x00\x12B\n" +
	"\tGetWallet\x12\x18.wallet.GetWalletRequest\x1a\x19.wallet.GetWalletResponse\"\x00\x12]\n" +
	"\x18ValidateAndDeductBalance\x12'.wallet.ValidateAndDeductBalanceRequest\x1a\x16.google.protobuf.Empty\"\x00\x12?\n" +
	"\tAddMember\x12\x18.wallet.AddMemberRequest\x1a\x16.google.protobuf.Empty\"\x00\x12W\n" +
	"\x10GetWalletMembers\x12\x1f.wallet.GetWalletMembersRequest\x1a .wallet.GetWalletMembersResponse\"\x00\x12Q\n" +
	"\x12DeleteWalletMember\x12!.wallet.DeleteWalletMemberRequest\x1a\x16.google.protobuf.Empty\"\x00\x12T\n" +
	"\x0fAllocateBalance\x12\x1e.wallet.AllocateBalanceRequest\x1a\x1f.wallet.AllocateBalanceResponse\"\x00\x12N\n" +
	"\rAdjustBalance\x12\x1c.wallet.AdjustBalanceRequest\x1a\x1d.wallet.AdjustBalanceResponse\"\x00BIZGgithub.com/raihan-faza/scriptsea-ept/backend/services/wallet_service/pbb\x06proto3"

var (
	file_wallet_proto_rawDescOnce sync.Once
	file_wallet_proto_rawDescData []byte
)

func file_wallet_proto_rawDescGZIP() []byte {
	file_wallet_proto_rawDescOnce.Do(func() {
		file_wallet_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_wallet_proto_rawDesc), len(file_wallet_proto_rawDesc)))
	})
	return file_wallet_proto_rawDescData
}

var file_wallet_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_wallet_proto_goTypes = []any{
	(*Wallet)(nil),                           // 0: wallet.Wallet
	(*Permission)(nil),                       // 1: wallet.Permission
	(*WalletMember)(nil),                     // 2: wallet.WalletMember
	(*DeleteWalletRequest)(nil),              // 3: wallet.DeleteWalletRequest
	(*GetWalletRequest)(nil),                 // 4: wallet.GetWalletRequest
	(*AddMemberRequest)(nil),                 // 5: wallet.AddMemberRequest
	(*AllocateBalanceRequest)(nil),           // 6: wallet.AllocateBalanceRequest
	(*CreateWalletRequest)(nil),              // 7: wallet.CreateWalletRequest
	(*UpdateWalletRequest)(nil),              // 8: wallet.UpdateWalletRequest
	(*ValidateAndDeductBalanceRequest)(nil),  // 9: wallet.ValidateAndDeductBalanceRequest
	(*GetWalletMembersRequest)(nil),          // 10: wallet.GetWalletMembersRequest
	(*DeleteWalletMemberRequest)(nil),        // 11: wallet.DeleteWalletMemberRequest
	(*AdjustBalanceRequest)(nil),             // 12: wallet.AdjustBalanceRequest
	(*AllocateBalanceResponse)(nil),          // 13: wallet.AllocateBalanceResponse
	(*GetWalletResponse)(nil),                // 14: wallet.GetWalletResponse
	(*UpdateWalletResponse)(nil),             // 15: wallet.UpdateWalletResponse
	(*CreateWalletResponse)(nil),             // 16: wallet.CreateWalletResponse
	(*ValidateAndDeductBalanceResponse)(nil), // 17: wallet.ValidateAndDeductBalanceResponse
	(*AddMemberResponse)(nil),                // 18: wallet.AddMemberResponse
	(*GetWalletMembersResponse)(nil),         // 19: wallet.GetWalletMembersResponse
	(*DeleteWalletMemberResponse)(nil),       // 20: wallet.DeleteWalletMemberResponse
	(*AdjustBalanceResponse)(nil),            // 21: wallet.AdjustBalanceResponse
	(*fieldmaskpb.FieldMask)(nil),            // 22: google.protobuf.FieldMask
	(*emptypb.Empty)(nil),                    // 23: google.protobuf.Empty
}
var file_wallet_proto_depIdxs = []int32{
	1,  // 0: wallet.WalletMember.permission:type_name -> wallet.Permission
	2,  // 1: wallet.AddMemberRequest.wallet_member:type_name -> wallet.WalletMember
	22, // 2: wallet.UpdateWalletRequest.update_mask:type_name -> google.protobuf.FieldMask
	2,  // 3: wallet.AllocateBalanceResponse.wallet_member:type_name -> wallet.WalletMember
	0,  // 4: wallet.GetWalletResponse.wallet:type_name -> wallet.Wallet
	2,  // 5: wallet.GetWalletResponse.members:type_name -> wallet.WalletMember
	0,  // 6: wallet.UpdateWalletResponse.wallet:type_name -> wallet.Wallet
	0,  // 7: wallet.CreateWalletResponse.wallet:type_name -> wallet.Wallet
	2,  // 8: wallet.GetWalletMembersResponse.wallet_members:type_name -> wallet.WalletMember
	2,  // 9: wallet.DeleteWalletMemberResponse.wallet_members:type_name -> wallet.WalletMember
	0,  // 10: wallet.AdjustBalanceResponse.wallet:type_name -> wallet.Wallet
	7,  // 11: wallet.WalletService.CreateWallet:input_type -> wallet.CreateWalletRequest
	8,  // 12: wallet.WalletService.UpdateWallet:input_type -> wallet.UpdateWalletRequest
	3,  // 13: wallet.WalletService.DeleteWallet:input_type -> wallet.DeleteWalletRequest
	4,  // 14: wallet.WalletService.GetWallet:input_type -> wallet.GetWalletRequest
	9,  // 15: wallet.WalletService.ValidateAndDeductBalance:input_type -> wallet.ValidateAndDeductBalanceRequest
	5,  // 16: wallet.WalletService.AddMember:input_type -> wallet.AddMemberRequest
	10, // 17: wallet.WalletService.GetWalletMembers:input_type -> wallet.GetWalletMembersRequest
	11, // 18: wallet.WalletService.DeleteWalletMember:input_type -> wallet.DeleteWalletMemberRequest
	6,  // 19: wallet.WalletService.AllocateBalance:input_type -> wallet.AllocateBalanceRequest
	12, // 20: wallet.WalletService.AdjustBalance:input_type -> wallet.AdjustBalanceRequest
	16, // 21: wallet.WalletService.CreateWallet:output_type -> wallet.CreateWalletResponse
	15, // 22: wallet.WalletService.UpdateWallet:output_type -> wallet.UpdateWalletResponse
	23, // 23: wallet.WalletService.DeleteWallet:output_type -> google.protobuf.Empty
	14, // 24: wallet.WalletService.GetWallet:output_type -> wallet.GetWalletResponse
	23, // 25: wallet.WalletService.ValidateAndDeductBalance:output_type -> google.protobuf.Empty
	23, // 26: wallet.WalletService.AddMember:output_type -> google.protobuf.Empty
	19, // 27: wallet.WalletService.GetWalletMembers:output_type -> wallet.GetWalletMembersResponse
	23, // 28: wallet.WalletService.DeleteWalletMember:output_type -> google.protobuf.Empty
	13, // 29: wallet.WalletService.AllocateBalance:output_type -> wallet.AllocateBalanceResponse
	21, // 30: wallet.WalletService.AdjustBalance:output_type -> wallet.AdjustBalanceResponse
	21, // [21:31] is the sub-list for method output_type
	11, // [11:21] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_wallet_proto_init() }
func file_wallet_proto_init() {
	if File_wallet_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wallet_proto_rawDesc), len(file_wallet_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_wallet_proto_goTypes,
		DependencyIndexes: file_wallet_proto_depIdxs,
		MessageInfos:      file_wallet_proto_msgTypes,
	}.Build()
	File_wallet_proto = out.File
	file_wallet_proto_goTypes = nil
	file_wallet_proto_depIdxs = nil
}
